// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/company_settings/domain (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/company_settings/mocks/mock_repository.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/company_settings/domain RepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// DeleteAllCompanySettings mocks base method.
func (m *MockRepositoryInterface) DeleteAllCompanySettings(ctx context.Context, companyId pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllCompanySettings", ctx, companyId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllCompanySettings indicates an expected call of DeleteAllCompanySettings.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteAllCompanySettings(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllCompanySettings", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteAllCompanySettings), ctx, companyId)
}

// DeleteCompanySetting mocks base method.
func (m *MockRepositoryInterface) DeleteCompanySetting(ctx context.Context, arg db.DeleteCompanySettingParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompanySetting", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCompanySetting indicates an expected call of DeleteCompanySetting.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteCompanySetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompanySetting", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteCompanySetting), ctx, arg)
}

// GetCompanySetting mocks base method.
func (m *MockRepositoryInterface) GetCompanySetting(ctx context.Context, arg db.GetCompanySettingParams) (db.CompanySetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanySetting", ctx, arg)
	ret0, _ := ret[0].(db.CompanySetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanySetting indicates an expected call of GetCompanySetting.
func (mr *MockRepositoryInterfaceMockRecorder) GetCompanySetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanySetting", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCompanySetting), ctx, arg)
}

// ListCompanySettings mocks base method.
func (m *MockRepositoryInterface) ListCompanySettings(ctx context.Context, companyId pgtype.UUID) ([]db.CompanySetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanySettings", ctx, companyId)
	ret0, _ := ret[0].([]db.CompanySetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompanySettings indicates an expected call of ListCompanySettings.
func (mr *MockRepositoryInterfaceMockRecorder) ListCompanySettings(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanySettings", reflect.TypeOf((*MockRepositoryInterface)(nil).ListCompanySettings), ctx, companyId)
}

// UpsertCompanySetting mocks base method.
func (m *MockRepositoryInterface) UpsertCompanySetting(ctx context.Context, arg db.UpsertCompanySettingParams) (db.CompanySetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCompanySetting", ctx, arg)
	ret0, _ := ret[0].(db.CompanySetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCompanySetting indicates an expected call of UpsertCompanySetting.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertCompanySetting(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCompanySetting", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertCompanySetting), ctx, arg)
}
