// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: mock de RepositoryInterface para testes do service de sales.
package mocks

import (
	"context"
	"reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	"github.com/ProTrack-Solutions/protrack-api/internal/sales/repository"
	"github.com/jackc/pgx/v5/pgtype"
	"go.uber.org/mock/gomock"
)

// MockRepositoryInterface é o mock de RepositoryInterface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder é o recorder de chamadas do mock.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface cria uma nova instância do mock.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateSales mocks o método CreateSales.
func (m *MockRepositoryInterface) CreateSales(ctx context.Context, arg db.CreateSaleParams) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSales", ctx, arg)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CreateSales(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSales", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateSales), ctx, arg)
}

// DeleteSales mocks o método DeleteSales.
func (m *MockRepositoryInterface) DeleteSales(ctx context.Context, arg db.DeleteSaleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSales", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) DeleteSales(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSales", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteSales), ctx, arg)
}

// GetSaleById mocks o método GetSaleById.
func (m *MockRepositoryInterface) GetSaleById(ctx context.Context, arg db.GetSaleByIdParams) (db.GetSaleByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleById", ctx, arg)
	ret0, _ := ret[0].(db.GetSaleByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetSaleById(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSaleById), ctx, arg)
}

// ListSales mocks o método ListSales.
func (m *MockRepositoryInterface) ListSales(ctx context.Context, companyId pgtype.UUID) ([]db.ListSalesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSales", ctx, companyId)
	ret0, _ := ret[0].([]db.ListSalesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListSales(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSales", reflect.TypeOf((*MockRepositoryInterface)(nil).ListSales), ctx, companyId)
}

// UpdateSaleStatus mocks o método UpdateSaleStatus.
func (m *MockRepositoryInterface) UpdateSaleStatus(ctx context.Context, arg db.UpdateSaleStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSaleStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateSaleStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSaleStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateSaleStatus), ctx, arg)
}

// ListSalesByCompanyAndStatus mocks o método ListSalesByCompanyAndStatus.
func (m *MockRepositoryInterface) ListSalesByCompanyAndStatus(ctx context.Context, arg db.ListSalesByCompanyAndStatusParams) ([]db.ListSalesByCompanyAndStatusRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesByCompanyAndStatus", ctx, arg)
	ret0, _ := ret[0].([]db.ListSalesByCompanyAndStatusRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListSalesByCompanyAndStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesByCompanyAndStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).ListSalesByCompanyAndStatus), ctx, arg)
}

// CountSales mocks o método CountSales.
func (m *MockRepositoryInterface) CountSales(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSales", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CountSales(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSales", reflect.TypeOf((*MockRepositoryInterface)(nil).CountSales), ctx, companyId)
}

// GetSalesPerformanceSummary mocks o método GetSalesPerformanceSummary.
func (m *MockRepositoryInterface) GetSalesPerformanceSummary(ctx context.Context, companyId pgtype.UUID) (db.GetSalesPerformanceSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesPerformanceSummary", ctx, companyId)
	ret0, _ := ret[0].(db.GetSalesPerformanceSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetSalesPerformanceSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesPerformanceSummary", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSalesPerformanceSummary), ctx, companyId)
}

// GetTotalAmountSummary mocks o método GetTotalAmountSummary.
func (m *MockRepositoryInterface) GetTotalAmountSummary(ctx context.Context, companyId pgtype.UUID) (db.GetTotalAmountSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountSummary", ctx, companyId)
	ret0, _ := ret[0].(db.GetTotalAmountSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetTotalAmountSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountSummary", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalAmountSummary), ctx, companyId)
}

// GetTotalAmountByStatus mocks o método GetTotalAmountByStatus.
func (m *MockRepositoryInterface) GetTotalAmountByStatus(ctx context.Context, arg db.GetTotalAmountByStatusParams) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountByStatus", ctx, arg)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetTotalAmountByStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountByStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalAmountByStatus), ctx, arg)
}

// GetSaleByIdWhatsapp mocks o método GetSaleByIdWhatsapp.
func (m *MockRepositoryInterface) GetSaleByIdWhatsapp(ctx context.Context, id pgtype.UUID) (db.GetSaleByIdWhatsappRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleByIdWhatsapp", ctx, id)
	ret0, _ := ret[0].(db.GetSaleByIdWhatsappRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetSaleByIdWhatsapp(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleByIdWhatsapp", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSaleByIdWhatsapp), ctx, id)
}

// UpdateOverdueSalesAndAccounts mocks o método UpdateOverdueSalesAndAccounts.
func (m *MockRepositoryInterface) UpdateOverdueSalesAndAccounts(ctx context.Context) ([]db.UpdateOverdueSalesAndAccountsGlobalRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOverdueSalesAndAccounts", ctx)
	ret0, _ := ret[0].([]db.UpdateOverdueSalesAndAccountsGlobalRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateOverdueSalesAndAccounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOverdueSalesAndAccounts", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateOverdueSalesAndAccounts), ctx)
}

// GetSaleByIdJust mocks o método GetSaleByIdJust.
func (m *MockRepositoryInterface) GetSaleByIdJust(ctx context.Context, saleId pgtype.UUID) (db.GetSaleByIdJustRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleByIdJust", ctx, saleId)
	ret0, _ := ret[0].(db.GetSaleByIdJustRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetSaleByIdJust(ctx, saleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleByIdJust", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSaleByIdJust), ctx, saleId)
}

// ContSalesPendingAndOverdue mocks o método ContSalesPendingAndOverdue.
func (m *MockRepositoryInterface) ContSalesPendingAndOverdue(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContSalesPendingAndOverdue", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ContSalesPendingAndOverdue(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContSalesPendingAndOverdue", reflect.TypeOf((*MockRepositoryInterface)(nil).ContSalesPendingAndOverdue), ctx, companyId)
}

// ListSalesWithDetails mocks o método ListSalesWithDetails.
func (m *MockRepositoryInterface) ListSalesWithDetails(ctx context.Context, companyID pgtype.UUID) ([]db.ListSalesWithDetailsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesWithDetails", ctx, companyID)
	ret0, _ := ret[0].([]db.ListSalesWithDetailsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListSalesWithDetails(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesWithDetails", reflect.TypeOf((*MockRepositoryInterface)(nil).ListSalesWithDetails), ctx, companyID)
}

// ListSalesWithDetailsPendingOverdue mocks o método ListSalesWithDetailsPendingOverdue.
func (m *MockRepositoryInterface) ListSalesWithDetailsPendingOverdue(ctx context.Context, companyID pgtype.UUID) ([]db.ListSalesWithDetailsPendingOverdueRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesWithDetailsPendingOverdue", ctx, companyID)
	ret0, _ := ret[0].([]db.ListSalesWithDetailsPendingOverdueRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListSalesWithDetailsPendingOverdue(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesWithDetailsPendingOverdue", reflect.TypeOf((*MockRepositoryInterface)(nil).ListSalesWithDetailsPendingOverdue), ctx, companyID)
}

// GetPendingSalesDetailedReport mocks o método GetPendingSalesDetailedReport.
func (m *MockRepositoryInterface) GetPendingSalesDetailedReport(ctx context.Context, arg db.GetPendingSalesDetailedReportParams) ([]db.GetPendingSalesDetailedReportRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSalesDetailedReport", ctx, arg)
	ret0, _ := ret[0].([]db.GetPendingSalesDetailedReportRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetPendingSalesDetailedReport(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSalesDetailedReport", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPendingSalesDetailedReport), ctx, arg)
}

// ListSalesWithDetailsPaginate mocks o método ListSalesWithDetailsPaginate.
func (m *MockRepositoryInterface) ListSalesWithDetailsPaginate(ctx context.Context, arg db.ListSalesWithDetailsPaginateParams) ([]db.ListSalesWithDetailsPaginateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesWithDetailsPaginate", ctx, arg)
	ret0, _ := ret[0].([]db.ListSalesWithDetailsPaginateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListSalesWithDetailsPaginate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesWithDetailsPaginate", reflect.TypeOf((*MockRepositoryInterface)(nil).ListSalesWithDetailsPaginate), ctx, arg)
}

// CountSalesByCompany mocks o método CountSalesByCompany.
func (m *MockRepositoryInterface) CountSalesByCompany(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSalesByCompany", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CountSalesByCompany(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSalesByCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).CountSalesByCompany), ctx, companyId)
}

// UpdateSale mocks o método UpdateSale.
func (m *MockRepositoryInterface) UpdateSale(ctx context.Context, arg db.UpdateSaleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSale", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateSale(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSale", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateSale), ctx, arg)
}

// CountSalesDeletedByCompany mocks o método CountSalesDeletedByCompany.
func (m *MockRepositoryInterface) CountSalesDeletedByCompany(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSalesDeletedByCompany", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CountSalesDeletedByCompany(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSalesDeletedByCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).CountSalesDeletedByCompany), ctx, companyId)
}

// GetTotalAmountPending mocks o método GetTotalAmountPending.
func (m *MockRepositoryInterface) GetTotalAmountPending(ctx context.Context, companyId pgtype.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountPending", ctx, companyId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetTotalAmountPending(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountPending", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalAmountPending), ctx, companyId)
}

// GetTotalAmountPaid mocks o método GetTotalAmountPaid.
func (m *MockRepositoryInterface) GetTotalAmountPaid(ctx context.Context, companyId pgtype.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountPaid", ctx, companyId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetTotalAmountPaid(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountPaid", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTotalAmountPaid), ctx, companyId)
}

// WithTx mocks o método WithTx.
func (m *MockRepositoryInterface) WithTx(tx db.DBTX) *repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*repository.Repository)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTx), tx)
}
