// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: mock de ServiceInterface para testes do handler de sales.
package mocks

import (
	"context"
	"reflect"
	"time"

	globalDomain "github.com/ProTrack-Solutions/protrack-api/internal/domain"
	"github.com/ProTrack-Solutions/protrack-api/internal/sales/domain"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// ServiceInterface define o contrato de serviço que o handler consome.
// Usado apenas para geração de mocks de testes.
type ServiceInterface interface {
	DeleteSale(ctx context.Context, id uuid.UUID, req domain.DeleteSaleRequest) error
	GetSaleById(ctx context.Context, req domain.GetSaleByIdRequest) (domain.GetSaleByIdRow, error)
	ListSales(ctx context.Context, companyId uuid.UUID) ([]domain.ListSalesRow, error)
	UpdateSaleStatus(ctx context.Context, id uuid.UUID, req domain.UpdateSaleStatusRequest) error
	ListSalesByCustomerAndStatus(ctx context.Context, req domain.ListSalesByCompanyAndStatusRequest) ([]domain.ListSalesByCompanyAndStatusRow, error)
	CountSales(ctx context.Context, companyId uuid.UUID) (int64, error)
	GetSalesPerformanceSummary(ctx context.Context, companyId uuid.UUID) (float64, error)
	GetTotalAmountSummary(ctx context.Context, companyId uuid.UUID) (domain.GetTotalAmountSummaryRow, error)
	GetTotalAmountIsPending(ctx context.Context, companyId uuid.UUID) (float64, error)
	GetTotalAmountIsOverdue(ctx context.Context, req domain.GetTotalAmountByStatusRequest) (float64, error)
	ContSalesPendingAndOverdue(ctx context.Context, companyId uuid.UUID) (int64, error)
	ListSalesWithDetailsPaginate(ctx context.Context, companyId uuid.UUID, pagination globalDomain.PaginationParams) (domain.SaleResponsePaginate, error)
	ListSalesWithDetailsPendingOverdue(ctx context.Context, companyId uuid.UUID) ([]domain.ListSalesWithInstallmentsResponse, error)
	GetPendingSalesDetailedReport(ctx context.Context, companyId uuid.UUID, saleAt time.Time, saleAt2 time.Time) ([]domain.GetPendingSalesDetailedReportResponse, error)
}

// MockServiceInterface é o mock da interface de serviço de sales.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder é o recorder de chamadas.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface cria uma nova instância do mock.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteSale mocks o método DeleteSale.
func (m *MockServiceInterface) DeleteSale(ctx context.Context, id uuid.UUID, req domain.DeleteSaleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSale", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) DeleteSale(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSale", reflect.TypeOf((*MockServiceInterface)(nil).DeleteSale), ctx, id, req)
}

// GetSaleById mocks o método GetSaleById.
func (m *MockServiceInterface) GetSaleById(ctx context.Context, req domain.GetSaleByIdRequest) (domain.GetSaleByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSaleById", ctx, req)
	ret0, _ := ret[0].(domain.GetSaleByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetSaleById(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSaleById", reflect.TypeOf((*MockServiceInterface)(nil).GetSaleById), ctx, req)
}

// ListSales mocks o método ListSales.
func (m *MockServiceInterface) ListSales(ctx context.Context, companyId uuid.UUID) ([]domain.ListSalesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSales", ctx, companyId)
	ret0, _ := ret[0].([]domain.ListSalesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListSales(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSales", reflect.TypeOf((*MockServiceInterface)(nil).ListSales), ctx, companyId)
}

// UpdateSaleStatus mocks o método UpdateSaleStatus.
func (m *MockServiceInterface) UpdateSaleStatus(ctx context.Context, id uuid.UUID, req domain.UpdateSaleStatusRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSaleStatus", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) UpdateSaleStatus(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSaleStatus", reflect.TypeOf((*MockServiceInterface)(nil).UpdateSaleStatus), ctx, id, req)
}

// ListSalesByCustomerAndStatus mocks o método ListSalesByCustomerAndStatus.
func (m *MockServiceInterface) ListSalesByCustomerAndStatus(ctx context.Context, req domain.ListSalesByCompanyAndStatusRequest) ([]domain.ListSalesByCompanyAndStatusRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesByCustomerAndStatus", ctx, req)
	ret0, _ := ret[0].([]domain.ListSalesByCompanyAndStatusRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListSalesByCustomerAndStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesByCustomerAndStatus", reflect.TypeOf((*MockServiceInterface)(nil).ListSalesByCustomerAndStatus), ctx, req)
}

// CountSales mocks o método CountSales.
func (m *MockServiceInterface) CountSales(ctx context.Context, companyId uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSales", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) CountSales(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSales", reflect.TypeOf((*MockServiceInterface)(nil).CountSales), ctx, companyId)
}

// GetSalesPerformanceSummary mocks o método GetSalesPerformanceSummary.
func (m *MockServiceInterface) GetSalesPerformanceSummary(ctx context.Context, companyId uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesPerformanceSummary", ctx, companyId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetSalesPerformanceSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesPerformanceSummary", reflect.TypeOf((*MockServiceInterface)(nil).GetSalesPerformanceSummary), ctx, companyId)
}

// GetTotalAmountSummary mocks o método GetTotalAmountSummary.
func (m *MockServiceInterface) GetTotalAmountSummary(ctx context.Context, companyId uuid.UUID) (domain.GetTotalAmountSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountSummary", ctx, companyId)
	ret0, _ := ret[0].(domain.GetTotalAmountSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetTotalAmountSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountSummary", reflect.TypeOf((*MockServiceInterface)(nil).GetTotalAmountSummary), ctx, companyId)
}

// GetTotalAmountIsPending mocks o método GetTotalAmountIsPending.
func (m *MockServiceInterface) GetTotalAmountIsPending(ctx context.Context, companyId uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountIsPending", ctx, companyId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetTotalAmountIsPending(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountIsPending", reflect.TypeOf((*MockServiceInterface)(nil).GetTotalAmountIsPending), ctx, companyId)
}

// GetTotalAmountIsOverdue mocks o método GetTotalAmountIsOverdue.
func (m *MockServiceInterface) GetTotalAmountIsOverdue(ctx context.Context, req domain.GetTotalAmountByStatusRequest) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmountIsOverdue", ctx, req)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetTotalAmountIsOverdue(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmountIsOverdue", reflect.TypeOf((*MockServiceInterface)(nil).GetTotalAmountIsOverdue), ctx, req)
}

// ContSalesPendingAndOverdue mocks o método ContSalesPendingAndOverdue.
func (m *MockServiceInterface) ContSalesPendingAndOverdue(ctx context.Context, companyId uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContSalesPendingAndOverdue", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ContSalesPendingAndOverdue(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContSalesPendingAndOverdue", reflect.TypeOf((*MockServiceInterface)(nil).ContSalesPendingAndOverdue), ctx, companyId)
}

// ListSalesWithDetailsPaginate mocks o método ListSalesWithDetailsPaginate.
func (m *MockServiceInterface) ListSalesWithDetailsPaginate(ctx context.Context, companyId uuid.UUID, pagination globalDomain.PaginationParams) (domain.SaleResponsePaginate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesWithDetailsPaginate", ctx, companyId, pagination)
	ret0, _ := ret[0].(domain.SaleResponsePaginate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListSalesWithDetailsPaginate(ctx, companyId, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesWithDetailsPaginate", reflect.TypeOf((*MockServiceInterface)(nil).ListSalesWithDetailsPaginate), ctx, companyId, pagination)
}

// ListSalesWithDetailsPendingOverdue mocks o método ListSalesWithDetailsPendingOverdue.
func (m *MockServiceInterface) ListSalesWithDetailsPendingOverdue(ctx context.Context, companyId uuid.UUID) ([]domain.ListSalesWithInstallmentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesWithDetailsPendingOverdue", ctx, companyId)
	ret0, _ := ret[0].([]domain.ListSalesWithInstallmentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListSalesWithDetailsPendingOverdue(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesWithDetailsPendingOverdue", reflect.TypeOf((*MockServiceInterface)(nil).ListSalesWithDetailsPendingOverdue), ctx, companyId)
}

// GetPendingSalesDetailedReport mocks o método GetPendingSalesDetailedReport.
func (m *MockServiceInterface) GetPendingSalesDetailedReport(ctx context.Context, companyId uuid.UUID, saleAt time.Time, saleAt2 time.Time) ([]domain.GetPendingSalesDetailedReportResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingSalesDetailedReport", ctx, companyId, saleAt, saleAt2)
	ret0, _ := ret[0].([]domain.GetPendingSalesDetailedReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetPendingSalesDetailedReport(ctx, companyId, saleAt, saleAt2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingSalesDetailedReport", reflect.TypeOf((*MockServiceInterface)(nil).GetPendingSalesDetailedReport), ctx, companyId, saleAt, saleAt2)
}
