// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts_receivable.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccountsReceivableByCompany = `-- name: CountAccountsReceivableByCompany :one
SELECT COUNT(*) FROM accounts_receivable
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountAccountsReceivableByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsReceivableByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccountReceivable = `-- name: CreateAccountReceivable :exec
INSERT INTO accounts_receivable (
        company_id,
        customer_id,
        sale_id,
        total_amount,
        balance,
        due_date,
        installment_number,
        total_installments,
        status,
        created_by
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAccountReceivableParams struct {
	CompanyID         pgtype.UUID    `json:"company_id"`
	CustomerID        pgtype.UUID    `json:"customer_id"`
	SaleID            pgtype.UUID    `json:"sale_id"`
	TotalAmount       pgtype.Numeric `json:"total_amount"`
	Balance           pgtype.Numeric `json:"balance"`
	DueDate           pgtype.Date    `json:"due_date"`
	InstallmentNumber pgtype.Int4    `json:"installment_number"`
	TotalInstallments pgtype.Int4    `json:"total_installments"`
	Status            string         `json:"status"`
	CreatedBy         pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateAccountReceivable(ctx context.Context, arg CreateAccountReceivableParams) error {
	_, err := q.db.Exec(ctx, createAccountReceivable,
		arg.CompanyID,
		arg.CustomerID,
		arg.SaleID,
		arg.TotalAmount,
		arg.Balance,
		arg.DueDate,
		arg.InstallmentNumber,
		arg.TotalInstallments,
		arg.Status,
		arg.CreatedBy,
	)
	return err
}

const deleteAccountsReceivableBySaleId = `-- name: DeleteAccountsReceivableBySaleId :exec
DELETE FROM accounts_receivable 
WHERE sale_id = $1 
    AND company_id = $2
`

type DeleteAccountsReceivableBySaleIdParams struct {
	SaleID    pgtype.UUID `json:"sale_id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) DeleteAccountsReceivableBySaleId(ctx context.Context, arg DeleteAccountsReceivableBySaleIdParams) error {
	_, err := q.db.Exec(ctx, deleteAccountsReceivableBySaleId, arg.SaleID, arg.CompanyID)
	return err
}

const getCustomerDebtSummary = `-- name: GetCustomerDebtSummary :one
SELECT COUNT(id)::int AS total_count,
    COALESCE(SUM(balance), 0)::numeric AS total_balance,
    MIN(due_date)::date AS oldest_due_date
FROM accounts_receivable
WHERE customer_id = $1
    AND status IN ('pending', 'partial')
    AND deleted_at IS NULL
`

type GetCustomerDebtSummaryRow struct {
	TotalCount    int32          `json:"total_count"`
	TotalBalance  pgtype.Numeric `json:"total_balance"`
	OldestDueDate pgtype.Date    `json:"oldest_due_date"`
}

func (q *Queries) GetCustomerDebtSummary(ctx context.Context, customerID pgtype.UUID) (GetCustomerDebtSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCustomerDebtSummary, customerID)
	var i GetCustomerDebtSummaryRow
	err := row.Scan(&i.TotalCount, &i.TotalBalance, &i.OldestDueDate)
	return i, err
}

const getPendingReceivablesByCustomer = `-- name: GetPendingReceivablesByCustomer :many
SELECT id, company_id, customer_id, sale_id, total_amount, balance, due_date, installment_number, total_installments, status, created_at, created_by, updated_at, updated_by, deleted_at
FROM accounts_receivable
WHERE customer_id = $1
    AND company_id = $2
    AND status IN ('pending', 'partial')
    AND deleted_at IS NULL
ORDER BY due_date ASC
`

type GetPendingReceivablesByCustomerParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
}

func (q *Queries) GetPendingReceivablesByCustomer(ctx context.Context, arg GetPendingReceivablesByCustomerParams) ([]AccountsReceivable, error) {
	rows, err := q.db.Query(ctx, getPendingReceivablesByCustomer, arg.CustomerID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountsReceivable{}
	for rows.Next() {
		var i AccountsReceivable
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SaleID,
			&i.TotalAmount,
			&i.Balance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.TotalInstallments,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceivablesBySale = `-- name: GetReceivablesBySale :many
SELECT id, company_id, customer_id, sale_id, total_amount, balance, due_date, installment_number, total_installments, status, created_at, created_by, updated_at, updated_by, deleted_at
FROM accounts_receivable
WHERE sale_id = $1
ORDER BY installment_number ASC
`

func (q *Queries) GetReceivablesBySale(ctx context.Context, saleID pgtype.UUID) ([]AccountsReceivable, error) {
	rows, err := q.db.Query(ctx, getReceivablesBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountsReceivable{}
	for rows.Next() {
		var i AccountsReceivable
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SaleID,
			&i.TotalAmount,
			&i.Balance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.TotalInstallments,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceivablesSummary = `-- name: GetReceivablesSummary :one
SELECT 
    COALESCE(
        SUM(balance) FILTER (WHERE status != 'paid'), 
        0
    )::NUMERIC(10, 2) as total_outstanding,
    
    COALESCE(
        SUM(balance) FILTER (
            WHERE status != 'paid' 
            AND (status = 'overdue' OR due_date < CURRENT_DATE)
        ), 
        0
    )::NUMERIC(10, 2) as total_overdue

FROM accounts_receivable
WHERE company_id = $1
  AND deleted_at IS NULL
`

type GetReceivablesSummaryRow struct {
	TotalOutstanding pgtype.Numeric `json:"total_outstanding"`
	TotalOverdue     pgtype.Numeric `json:"total_overdue"`
}

func (q *Queries) GetReceivablesSummary(ctx context.Context, companyID pgtype.UUID) (GetReceivablesSummaryRow, error) {
	row := q.db.QueryRow(ctx, getReceivablesSummary, companyID)
	var i GetReceivablesSummaryRow
	err := row.Scan(&i.TotalOutstanding, &i.TotalOverdue)
	return i, err
}

const getTotalOpenAmountByCompany = `-- name: GetTotalOpenAmountByCompany :one
SELECT company_id,
    SUM(balance)::NUMERIC(10, 2) as total_open
FROM accounts_receivable
WHERE company_id = $1
    AND status IN ('pending', 'overdue')
    AND deleted_at IS NULL
GROUP BY company_id
`

type GetTotalOpenAmountByCompanyRow struct {
	CompanyID pgtype.UUID    `json:"company_id"`
	TotalOpen pgtype.Numeric `json:"total_open"`
}

func (q *Queries) GetTotalOpenAmountByCompany(ctx context.Context, companyID pgtype.UUID) (GetTotalOpenAmountByCompanyRow, error) {
	row := q.db.QueryRow(ctx, getTotalOpenAmountByCompany, companyID)
	var i GetTotalOpenAmountByCompanyRow
	err := row.Scan(&i.CompanyID, &i.TotalOpen)
	return i, err
}

const getTotalOverdueAmountByCompany = `-- name: GetTotalOverdueAmountByCompany :one
SELECT company_id,
    COALESCE(SUM(balance), 0)::NUMERIC(10, 2) as total_overdue
FROM accounts_receivable
WHERE company_id = $1
    AND (
        status = 'overdue'
        OR due_date < CURRENT_DATE
    )
    AND status != 'paid'
    AND deleted_at IS NULL
GROUP BY company_id
`

type GetTotalOverdueAmountByCompanyRow struct {
	CompanyID    pgtype.UUID    `json:"company_id"`
	TotalOverdue pgtype.Numeric `json:"total_overdue"`
}

func (q *Queries) GetTotalOverdueAmountByCompany(ctx context.Context, companyID pgtype.UUID) (GetTotalOverdueAmountByCompanyRow, error) {
	row := q.db.QueryRow(ctx, getTotalOverdueAmountByCompany, companyID)
	var i GetTotalOverdueAmountByCompanyRow
	err := row.Scan(&i.CompanyID, &i.TotalOverdue)
	return i, err
}

const listAccountsReceivables = `-- name: ListAccountsReceivables :many
SELECT ar.id, ar.company_id, ar.customer_id, ar.sale_id, ar.total_amount, ar.balance, ar.due_date, ar.installment_number, ar.total_installments, ar.status, ar.created_at, ar.created_by, ar.updated_at, ar.updated_by, ar.deleted_at,
    c.full_name as customer_name
FROM accounts_receivable ar
JOIN customers c ON ar.customer_id = c.id
WHERE ar.company_id = $1
    AND ar.deleted_at IS NULL
ORDER BY ar.due_date ASC
LIMIT $2
OFFSET $3
`

type ListAccountsReceivablesParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListAccountsReceivablesRow struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	SaleID            pgtype.UUID        `json:"sale_id"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	Balance           pgtype.Numeric     `json:"balance"`
	DueDate           pgtype.Date        `json:"due_date"`
	InstallmentNumber pgtype.Int4        `json:"installment_number"`
	TotalInstallments pgtype.Int4        `json:"total_installments"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CustomerName      string             `json:"customer_name"`
}

func (q *Queries) ListAccountsReceivables(ctx context.Context, arg ListAccountsReceivablesParams) ([]ListAccountsReceivablesRow, error) {
	rows, err := q.db.Query(ctx, listAccountsReceivables, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsReceivablesRow{}
	for rows.Next() {
		var i ListAccountsReceivablesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SaleID,
			&i.TotalAmount,
			&i.Balance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.TotalInstallments,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueReceivables = `-- name: ListOverdueReceivables :many
SELECT ar.id, ar.company_id, ar.customer_id, ar.sale_id, ar.total_amount, ar.balance, ar.due_date, ar.installment_number, ar.total_installments, ar.status, ar.created_at, ar.created_by, ar.updated_at, ar.updated_by, ar.deleted_at,
    c.full_name as customer_name,
    EXTRACT(
        DAY
        FROM (CURRENT_DATE - ar.due_date)
    )::int AS days_overdue
FROM accounts_receivable ar
    JOIN customers c ON ar.customer_id = c.id
WHERE ar.company_id = $1
    AND ar.status IN ('pending', 'partial')
    AND ar.due_date < CURRENT_DATE
    AND ar.deleted_at IS NULL
ORDER BY ar.due_date ASC
`

type ListOverdueReceivablesRow struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	SaleID            pgtype.UUID        `json:"sale_id"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	Balance           pgtype.Numeric     `json:"balance"`
	DueDate           pgtype.Date        `json:"due_date"`
	InstallmentNumber pgtype.Int4        `json:"installment_number"`
	TotalInstallments pgtype.Int4        `json:"total_installments"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CustomerName      string             `json:"customer_name"`
	DaysOverdue       int32              `json:"days_overdue"`
}

func (q *Queries) ListOverdueReceivables(ctx context.Context, companyID pgtype.UUID) ([]ListOverdueReceivablesRow, error) {
	rows, err := q.db.Query(ctx, listOverdueReceivables, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueReceivablesRow{}
	for rows.Next() {
		var i ListOverdueReceivablesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SaleID,
			&i.TotalAmount,
			&i.Balance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.TotalInstallments,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.CustomerName,
			&i.DaysOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountReceivableBalance = `-- name: UpdateAccountReceivableBalance :one
UPDATE accounts_receivable
SET balance = $1,
    status = $2,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $3
WHERE id = $4
RETURNING sale_id
`

type UpdateAccountReceivableBalanceParams struct {
	Balance   pgtype.Numeric `json:"balance"`
	Status    string         `json:"status"`
	UpdatedBy pgtype.UUID    `json:"updated_by"`
	ID        pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateAccountReceivableBalance(ctx context.Context, arg UpdateAccountReceivableBalanceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateAccountReceivableBalance,
		arg.Balance,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
	)
	var sale_id pgtype.UUID
	err := row.Scan(&sale_id)
	return sale_id, err
}
