// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: announcements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAnnoucementsByCompany = `-- name: CountAnnoucementsByCompany :one
SELECT COUNT(*) FROM announcements
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountAnnoucementsByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAnnoucementsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnnouncements = `-- name: CreateAnnouncements :exec
INSERT INTO announcements (
    company_id, 
    title, 
    content, 
    type, 
    starts_at, 
    expires_at, 
    is_active, 
    created_by
)
VALUES ($1, $2, $3, $4, COALESCE($5, NOW()), $6, $7, $8)
`

type CreateAnnouncementsParams struct {
	CompanyID pgtype.UUID        `json:"company_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Type      AnnouncementType   `json:"type"`
	Column5   interface{}        `json:"column_5"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  bool               `json:"is_active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAnnouncements(ctx context.Context, arg CreateAnnouncementsParams) error {
	_, err := q.db.Exec(ctx, createAnnouncements,
		arg.CompanyID,
		arg.Title,
		arg.Content,
		arg.Type,
		arg.Column5,
		arg.ExpiresAt,
		arg.IsActive,
		arg.CreatedBy,
	)
	return err
}

const deleteAnnoucements = `-- name: DeleteAnnoucements :exec
UPDATE announcements
SET 
    is_active = FALSE, 
    updated_at = NOW(), 
    deleted_by = $1,
    deleted_at = NOW()
WHERE id = $2 AND company_id = $3
`

type DeleteAnnoucementsParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) DeleteAnnoucements(ctx context.Context, arg DeleteAnnoucementsParams) error {
	_, err := q.db.Exec(ctx, deleteAnnoucements, arg.DeletedBy, arg.ID, arg.CompanyID)
	return err
}

const listAnnoucements = `-- name: ListAnnoucements :many
SELECT 
    id, 
    title, 
    type, 
    is_active, 
    starts_at, 
    expires_at,
    created_at
FROM announcements
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAnnoucementsParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListAnnoucementsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Type      AnnouncementType   `json:"type"`
	IsActive  bool               `json:"is_active"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAnnoucements(ctx context.Context, arg ListAnnoucementsParams) ([]ListAnnoucementsRow, error) {
	rows, err := q.db.Query(ctx, listAnnoucements, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnoucementsRow{}
	for rows.Next() {
		var i ListAnnoucementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.IsActive,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
