// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills_payable.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBillsPayableByCompany = `-- name: CountBillsPayableByCompany :one
SELECT COUNT(*) FROM bills_payable
WHERE company_id = $1
`

func (q *Queries) CountBillsPayableByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBillsPayableByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBillPayable = `-- name: CreateBillPayable :exec
INSERT INTO bills_payable (
        company_id,
        vendor_id,
        category_id,
        payment_method_id,
        amount,
        due_date,
        status,
        description,
        notes
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateBillPayableParams struct {
	CompanyID       pgtype.UUID    `json:"company_id"`
	VendorID        pgtype.UUID    `json:"vendor_id"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	DueDate         pgtype.Date    `json:"due_date"`
	Status          interface{}    `json:"status"`
	Description     pgtype.Text    `json:"description"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateBillPayable(ctx context.Context, arg CreateBillPayableParams) error {
	_, err := q.db.Exec(ctx, createBillPayable,
		arg.CompanyID,
		arg.VendorID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.DueDate,
		arg.Status,
		arg.Description,
		arg.Notes,
	)
	return err
}

const getBillsById = `-- name: GetBillsById :one
SELECT id, company_id, vendor_id, category_id, payment_method_id, amount, due_date, status, description, scheduled_date, payment_date, amount_paid, notes, created_at, updated_at
FROM bills_payable
WHERE company_id = $1
    AND id = $2
ORDER BY due_date ASC
`

type GetBillsByIdParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetBillsById(ctx context.Context, arg GetBillsByIdParams) (BillsPayable, error) {
	row := q.db.QueryRow(ctx, getBillsById, arg.CompanyID, arg.ID)
	var i BillsPayable
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VendorID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.Description,
		&i.ScheduledDate,
		&i.PaymentDate,
		&i.AmountPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillsByStatus = `-- name: GetBillsByStatus :many
SELECT id, company_id, vendor_id, category_id, payment_method_id, amount, due_date, status, description, scheduled_date, payment_date, amount_paid, notes, created_at, updated_at
FROM bills_payable
WHERE company_id = $1
    AND status = $2
ORDER BY due_date ASC
`

type GetBillsByStatusParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Status    interface{} `json:"status"`
}

func (q *Queries) GetBillsByStatus(ctx context.Context, arg GetBillsByStatusParams) ([]BillsPayable, error) {
	rows, err := q.db.Query(ctx, getBillsByStatus, arg.CompanyID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillsPayable{}
	for rows.Next() {
		var i BillsPayable
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.Description,
			&i.ScheduledDate,
			&i.PaymentDate,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillsPayableSummary = `-- name: GetBillsPayableSummary :one
SELECT COUNT(*)::INT as total_quantity,
    COALESCE(
        SUM(amount) FILTER (
            WHERE status IN ('pending', 'overdue')
        ),
        0
    )::NUMERIC(12, 2) as total_to_pay,
    COALESCE(
        SUM(amount) FILTER (
            WHERE due_date < CURRENT_DATE
                AND status != 'paid'
        ),
        0
    )::NUMERIC(12, 2) as total_overdue,
    COALESCE(
        SUM(amount) FILTER (
            WHERE scheduled_date IS NOT NULL
                AND status != 'paid'
        ),
        0
    )::NUMERIC(12, 2) as total_scheduled
FROM bills_payable
WHERE company_id = $1
`

type GetBillsPayableSummaryRow struct {
	TotalQuantity  int32          `json:"total_quantity"`
	TotalToPay     pgtype.Numeric `json:"total_to_pay"`
	TotalOverdue   pgtype.Numeric `json:"total_overdue"`
	TotalScheduled pgtype.Numeric `json:"total_scheduled"`
}

func (q *Queries) GetBillsPayableSummary(ctx context.Context, companyID pgtype.UUID) (GetBillsPayableSummaryRow, error) {
	row := q.db.QueryRow(ctx, getBillsPayableSummary, companyID)
	var i GetBillsPayableSummaryRow
	err := row.Scan(
		&i.TotalQuantity,
		&i.TotalToPay,
		&i.TotalOverdue,
		&i.TotalScheduled,
	)
	return i, err
}

const getOverdueBills = `-- name: GetOverdueBills :many
SELECT id, company_id, vendor_id, category_id, payment_method_id, amount, due_date, status, description, scheduled_date, payment_date, amount_paid, notes, created_at, updated_at
FROM bills_payable
WHERE company_id = $1
    AND due_date < CURRENT_DATE
    AND status != 'paid'
ORDER BY due_date ASC
`

func (q *Queries) GetOverdueBills(ctx context.Context, companyID pgtype.UUID) ([]BillsPayable, error) {
	rows, err := q.db.Query(ctx, getOverdueBills, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillsPayable{}
	for rows.Next() {
		var i BillsPayable
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.Description,
			&i.ScheduledDate,
			&i.PaymentDate,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillsPayable = `-- name: ListBillsPayable :many
SELECT b.id, b.company_id, b.vendor_id, b.category_id, b.payment_method_id, b.amount, b.due_date, b.status, b.description, b.scheduled_date, b.payment_date, b.amount_paid, b.notes, b.created_at, b.updated_at,
    v.name as vendor_name,
    c.name as category_name,
    pm.name as payment_method_name
FROM bills_payable b
    LEFT JOIN vendors v ON b.vendor_id = v.id
    LEFT JOIN bill_categories c ON b.category_id = c.id
    LEFT JOIN payment_methods pm ON b.payment_method_id = pm.id
WHERE b.company_id = $1
ORDER BY b.due_date ASC
`

type ListBillsPayableRow struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	VendorID          pgtype.UUID        `json:"vendor_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	PaymentMethodID   pgtype.UUID        `json:"payment_method_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	DueDate           pgtype.Date        `json:"due_date"`
	Status            interface{}        `json:"status"`
	Description       pgtype.Text        `json:"description"`
	ScheduledDate     pgtype.Date        `json:"scheduled_date"`
	PaymentDate       pgtype.Date        `json:"payment_date"`
	AmountPaid        pgtype.Numeric     `json:"amount_paid"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	VendorName        pgtype.Text        `json:"vendor_name"`
	CategoryName      pgtype.Text        `json:"category_name"`
	PaymentMethodName pgtype.Text        `json:"payment_method_name"`
}

func (q *Queries) ListBillsPayable(ctx context.Context, companyID pgtype.UUID) ([]ListBillsPayableRow, error) {
	rows, err := q.db.Query(ctx, listBillsPayable, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillsPayableRow{}
	for rows.Next() {
		var i ListBillsPayableRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.Description,
			&i.ScheduledDate,
			&i.PaymentDate,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorName,
			&i.CategoryName,
			&i.PaymentMethodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payBill = `-- name: PayBill :exec
UPDATE bills_payable
SET status = 'paid',
    payment_date = $3,
    amount_paid = $4,
    payment_method_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND company_id = $2
`

type PayBillParams struct {
	ID              pgtype.UUID    `json:"id"`
	CompanyID       pgtype.UUID    `json:"company_id"`
	PaymentDate     pgtype.Date    `json:"payment_date"`
	AmountPaid      pgtype.Numeric `json:"amount_paid"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
}

func (q *Queries) PayBill(ctx context.Context, arg PayBillParams) error {
	_, err := q.db.Exec(ctx, payBill,
		arg.ID,
		arg.CompanyID,
		arg.PaymentDate,
		arg.AmountPaid,
		arg.PaymentMethodID,
	)
	return err
}

const scheduleBill = `-- name: ScheduleBill :exec
UPDATE bills_payable
SET status = 'scheduled',
    scheduled_date = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND company_id = $2
`

type ScheduleBillParams struct {
	ID            pgtype.UUID `json:"id"`
	CompanyID     pgtype.UUID `json:"company_id"`
	ScheduledDate pgtype.Date `json:"scheduled_date"`
}

func (q *Queries) ScheduleBill(ctx context.Context, arg ScheduleBillParams) error {
	_, err := q.db.Exec(ctx, scheduleBill, arg.ID, arg.CompanyID, arg.ScheduledDate)
	return err
}

const updateBillPayable = `-- name: UpdateBillPayable :exec
UPDATE bills_payable
SET vendor_id = $3,
    category_id = $4,
    payment_method_id = $5,
    amount = $6,
    due_date = $7,
    status = $8,
    description = $9,
    notes = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND company_id = $2
`

type UpdateBillPayableParams struct {
	ID              pgtype.UUID    `json:"id"`
	CompanyID       pgtype.UUID    `json:"company_id"`
	VendorID        pgtype.UUID    `json:"vendor_id"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	DueDate         pgtype.Date    `json:"due_date"`
	Status          interface{}    `json:"status"`
	Description     pgtype.Text    `json:"description"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateBillPayable(ctx context.Context, arg UpdateBillPayableParams) error {
	_, err := q.db.Exec(ctx, updateBillPayable,
		arg.ID,
		arg.CompanyID,
		arg.VendorID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.DueDate,
		arg.Status,
		arg.Description,
		arg.Notes,
	)
	return err
}

const updateOverdueBillsPayable = `-- name: UpdateOverdueBillsPayable :exec
UPDATE bills_payable
SET status = 'overdue'
WHERE status = 'pending'
    AND due_date::DATE < CURRENT_DATE
`

func (q *Queries) UpdateOverdueBillsPayable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateOverdueBillsPayable)
	return err
}
