// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills_payable.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBillsPayableByCompany = `-- name: CountBillsPayableByCompany :one
SELECT COUNT(*) FROM bills_payable
WHERE company_id = $1
`

func (q *Queries) CountBillsPayableByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBillsPayableByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBillPayable = `-- name: CreateBillPayable :exec
INSERT INTO bills_payable (
        company_id,
        vendor_id,
        category_id,
        payment_method_id,
        amount,
        due_date,
        status,
        description,
        notes
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateBillPayableParams struct {
	CompanyID       pgtype.UUID    `json:"company_id"`
	VendorID        pgtype.UUID    `json:"vendor_id"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	DueDate         pgtype.Date    `json:"due_date"`
	Status          interface{}    `json:"status"`
	Description     pgtype.Text    `json:"description"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateBillPayable(ctx context.Context, arg CreateBillPayableParams) error {
	_, err := q.db.Exec(ctx, createBillPayable,
		arg.CompanyID,
		arg.VendorID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.DueDate,
		arg.Status,
		arg.Description,
		arg.Notes,
	)
	return err
}

const getBillsById = `-- name: GetBillsById :one
SELECT id, company_id, vendor_id, category_id, payment_method_id, amount, due_date, status, description, scheduled_date, payment_date, amount_paid, notes, created_at, updated_at
FROM bills_payable
WHERE company_id = $1
    AND id = $2
ORDER BY due_date ASC
`

type GetBillsByIdParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) GetBillsById(ctx context.Context, arg GetBillsByIdParams) (BillsPayable, error) {
	row := q.db.QueryRow(ctx, getBillsById, arg.CompanyID, arg.ID)
	var i BillsPayable
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.VendorID,
		&i.CategoryID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.DueDate,
		&i.Status,
		&i.Description,
		&i.ScheduledDate,
		&i.PaymentDate,
		&i.AmountPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillsByStatus = `-- name: GetBillsByStatus :many
SELECT id, company_id, vendor_id, category_id, payment_method_id, amount, due_date, status, description, scheduled_date, payment_date, amount_paid, notes, created_at, updated_at
FROM bills_payable
WHERE company_id = $1
    AND status = $2
ORDER BY due_date ASC
`

type GetBillsByStatusParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Status    interface{} `json:"status"`
}

func (q *Queries) GetBillsByStatus(ctx context.Context, arg GetBillsByStatusParams) ([]BillsPayable, error) {
	rows, err := q.db.Query(ctx, getBillsByStatus, arg.CompanyID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillsPayable{}
	for rows.Next() {
		var i BillsPayable
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.Description,
			&i.ScheduledDate,
			&i.PaymentDate,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillsPayableSummary = `-- name: GetBillsPayableSummary :one
SELECT COUNT(*)::INT as total_quantity,
    COALESCE(
        SUM(amount) FILTER (
            WHERE status IN ('pending', 'overdue')
        ),
        0
    )::NUMERIC(12, 2) as total_to_pay,
    COALESCE(
        SUM(amount) FILTER (
            WHERE due_date < CURRENT_DATE
                AND status != 'paid'
        ),
        0
    )::NUMERIC(12, 2) as total_overdue,
    COALESCE(
        SUM(amount) FILTER (
            WHERE scheduled_date IS NOT NULL
                AND status != 'paid'
        ),
        0
    )::NUMERIC(12, 2) as total_scheduled
FROM bills_payable
WHERE company_id = $1
`

type GetBillsPayableSummaryRow struct {
	TotalQuantity  int32          `json:"total_quantity"`
	TotalToPay     pgtype.Numeric `json:"total_to_pay"`
	TotalOverdue   pgtype.Numeric `json:"total_overdue"`
	TotalScheduled pgtype.Numeric `json:"total_scheduled"`
}

func (q *Queries) GetBillsPayableSummary(ctx context.Context, companyID pgtype.UUID) (GetBillsPayableSummaryRow, error) {
	row := q.db.QueryRow(ctx, getBillsPayableSummary, companyID)
	var i GetBillsPayableSummaryRow
	err := row.Scan(
		&i.TotalQuantity,
		&i.TotalToPay,
		&i.TotalOverdue,
		&i.TotalScheduled,
	)
	return i, err
}

const getOverdueBills = `-- name: GetOverdueBills :many
SELECT id, company_id, vendor_id, category_id, payment_method_id, amount, due_date, status, description, scheduled_date, payment_date, amount_paid, notes, created_at, updated_at
FROM bills_payable
WHERE company_id = $1
    AND due_date < CURRENT_DATE
    AND status != 'paid'
ORDER BY due_date ASC
`

func (q *Queries) GetOverdueBills(ctx context.Context, companyID pgtype.UUID) ([]BillsPayable, error) {
	rows, err := q.db.Query(ctx, getOverdueBills, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillsPayable{}
	for rows.Next() {
		var i BillsPayable
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.Description,
			&i.ScheduledDate,
			&i.PaymentDate,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillsPayable = `-- name: ListBillsPayable :many
SELECT
    b.id, b.company_id, b.vendor_id, b.category_id, b.payment_method_id, b.amount, b.due_date, b.status, b.description, b.scheduled_date, b.payment_date, b.amount_paid, b.notes, b.created_at, b.updated_at,
    v.name AS vendor_name,
    c.name AS category_name,
    pm.name AS payment_method_name,
    count(*) OVER() AS total_count
FROM bills_payable b
    LEFT JOIN vendors v ON b.vendor_id = v.id
    LEFT JOIN bill_categories c ON b.category_id = c.id
    LEFT JOIN payment_methods pm ON b.payment_method_id = pm.id
WHERE b.company_id = $1
    AND (
        $4::text = '' OR
        to_tsvector('portuguese_unaccent', coalesce(b.description, ''))
            @@ plainto_tsquery('portuguese_unaccent', $4::text)
        OR v.name ILIKE '%' || $4::text || '%'
        OR c.name ILIKE '%' || $4::text || '%'
        OR pm.name ILIKE '%' || $4::text || '%'
    )
    AND ($5::account_status_enum IS NULL OR b.status = $5::account_status_enum)
    AND ($6::date IS NULL OR b.due_date >= $6::date)
    AND ($7::date IS NULL OR b.due_date < ($7::date + INTERVAL '1 day'))
    AND ($8::date IS NULL OR b.scheduled_date >= $8::date)
    AND ($9::date IS NULL OR b.scheduled_date < ($9::date + INTERVAL '1 day'))
    AND ($10::date IS NULL OR b.payment_date >= $10::date)
    AND ($11::date IS NULL OR b.payment_date < ($11::date + INTERVAL '1 day'))
    AND ($12::date IS NULL OR b.created_at >= $12::date)
    AND ($13::date IS NULL OR b.created_at < ($13::date + INTERVAL '1 day'))
ORDER BY
    CASE WHEN $14::text = 'due_date'       AND $15::text = 'asc'  THEN b.due_date::timestamptz END ASC,
    CASE WHEN $14::text = 'due_date'       AND $15::text = 'desc' THEN b.due_date::timestamptz END DESC,
    CASE WHEN $14::text = 'scheduled_date' AND $15::text = 'asc'  THEN b.scheduled_date::timestamptz END ASC,
    CASE WHEN $14::text = 'scheduled_date' AND $15::text = 'desc' THEN b.scheduled_date::timestamptz END DESC,
    CASE WHEN $14::text = 'payment_date'   AND $15::text = 'asc'  THEN b.payment_date::timestamptz END ASC,
    CASE WHEN $14::text = 'payment_date'   AND $15::text = 'desc' THEN b.payment_date::timestamptz END DESC,
    CASE WHEN $14::text = 'created_at'     AND $15::text = 'asc'  THEN b.created_at END ASC,
    CASE WHEN $14::text = 'created_at'     AND $15::text = 'desc' THEN b.created_at END DESC
LIMIT $2
OFFSET $3
`

type ListBillsPayableParams struct {
	CompanyID          pgtype.UUID `json:"company_id"`
	Limit              int32       `json:"limit"`
	Offset             int32       `json:"offset"`
	Search             string      `json:"search"`
	Status             interface{} `json:"status"`
	StartDueDate       pgtype.Date `json:"start_due_date"`
	EndDueDate         pgtype.Date `json:"end_due_date"`
	StartScheduledDate pgtype.Date `json:"start_scheduled_date"`
	EndScheduledDate   pgtype.Date `json:"end_scheduled_date"`
	StartPaymentDate   pgtype.Date `json:"start_payment_date"`
	EndPaymentDate     pgtype.Date `json:"end_payment_date"`
	StartCreatedAt     pgtype.Date `json:"start_created_at"`
	EndCreatedAt       pgtype.Date `json:"end_created_at"`
	OrderField         string      `json:"order_field"`
	OrderBy            string      `json:"order_by"`
}

type ListBillsPayableRow struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	VendorID          pgtype.UUID        `json:"vendor_id"`
	CategoryID        pgtype.UUID        `json:"category_id"`
	PaymentMethodID   pgtype.UUID        `json:"payment_method_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	DueDate           pgtype.Date        `json:"due_date"`
	Status            interface{}        `json:"status"`
	Description       pgtype.Text        `json:"description"`
	ScheduledDate     pgtype.Date        `json:"scheduled_date"`
	PaymentDate       pgtype.Date        `json:"payment_date"`
	AmountPaid        pgtype.Numeric     `json:"amount_paid"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	VendorName        pgtype.Text        `json:"vendor_name"`
	CategoryName      pgtype.Text        `json:"category_name"`
	PaymentMethodName pgtype.Text        `json:"payment_method_name"`
	TotalCount        int64              `json:"total_count"`
}

func (q *Queries) ListBillsPayable(ctx context.Context, arg ListBillsPayableParams) ([]ListBillsPayableRow, error) {
	rows, err := q.db.Query(ctx, listBillsPayable,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Status,
		arg.StartDueDate,
		arg.EndDueDate,
		arg.StartScheduledDate,
		arg.EndScheduledDate,
		arg.StartPaymentDate,
		arg.EndPaymentDate,
		arg.StartCreatedAt,
		arg.EndCreatedAt,
		arg.OrderField,
		arg.OrderBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillsPayableRow{}
	for rows.Next() {
		var i ListBillsPayableRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.VendorID,
			&i.CategoryID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.DueDate,
			&i.Status,
			&i.Description,
			&i.ScheduledDate,
			&i.PaymentDate,
			&i.AmountPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorName,
			&i.CategoryName,
			&i.PaymentMethodName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payBill = `-- name: PayBill :exec
UPDATE bills_payable
SET status = 'paid',
    payment_date = $3,
    amount_paid = $4,
    payment_method_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND company_id = $2
`

type PayBillParams struct {
	ID              pgtype.UUID    `json:"id"`
	CompanyID       pgtype.UUID    `json:"company_id"`
	PaymentDate     pgtype.Date    `json:"payment_date"`
	AmountPaid      pgtype.Numeric `json:"amount_paid"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
}

func (q *Queries) PayBill(ctx context.Context, arg PayBillParams) error {
	_, err := q.db.Exec(ctx, payBill,
		arg.ID,
		arg.CompanyID,
		arg.PaymentDate,
		arg.AmountPaid,
		arg.PaymentMethodID,
	)
	return err
}

const scheduleBill = `-- name: ScheduleBill :exec
UPDATE bills_payable
SET status = 'scheduled',
    scheduled_date = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND company_id = $2
`

type ScheduleBillParams struct {
	ID            pgtype.UUID `json:"id"`
	CompanyID     pgtype.UUID `json:"company_id"`
	ScheduledDate pgtype.Date `json:"scheduled_date"`
}

func (q *Queries) ScheduleBill(ctx context.Context, arg ScheduleBillParams) error {
	_, err := q.db.Exec(ctx, scheduleBill, arg.ID, arg.CompanyID, arg.ScheduledDate)
	return err
}

const sumBillsPayableByCompany = `-- name: SumBillsPayableByCompany :one
SELECT COALESCE(SUM(amount), 0.0)::DOUBLE PRECISION AS total_amount
FROM bills_payable 
WHERE company_id = $1 AND status IN ('overdue','pending','partial')
`

func (q *Queries) SumBillsPayableByCompany(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, sumBillsPayableByCompany, companyID)
	var total_amount float64
	err := row.Scan(&total_amount)
	return total_amount, err
}

const sumBillsPayableOverdue = `-- name: SumBillsPayableOverdue :one
SELECT COALESCE(SUM(amount), 0.0)::DOUBLE PRECISION AS total_overdue
FROM bills_payable 
WHERE company_id = $1 AND status = 'overdue'
`

func (q *Queries) SumBillsPayableOverdue(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, sumBillsPayableOverdue, companyID)
	var total_overdue float64
	err := row.Scan(&total_overdue)
	return total_overdue, err
}

const sumBillsPayableSchedule = `-- name: SumBillsPayableSchedule :one
SELECT COALESCE(SUM(amount), 0.0)::DOUBLE PRECISION AS total_scheduled
FROM bills_payable 
WHERE company_id = $1 AND status = 'scheduled'
`

func (q *Queries) SumBillsPayableSchedule(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, sumBillsPayableSchedule, companyID)
	var total_scheduled float64
	err := row.Scan(&total_scheduled)
	return total_scheduled, err
}

const updateBillPayable = `-- name: UpdateBillPayable :exec
UPDATE bills_payable
SET vendor_id = $3,
    category_id = $4,
    payment_method_id = $5,
    amount = $6,
    due_date = $7,
    status = $8,
    description = $9,
    notes = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND company_id = $2
`

type UpdateBillPayableParams struct {
	ID              pgtype.UUID    `json:"id"`
	CompanyID       pgtype.UUID    `json:"company_id"`
	VendorID        pgtype.UUID    `json:"vendor_id"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
	Amount          pgtype.Numeric `json:"amount"`
	DueDate         pgtype.Date    `json:"due_date"`
	Status          interface{}    `json:"status"`
	Description     pgtype.Text    `json:"description"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateBillPayable(ctx context.Context, arg UpdateBillPayableParams) error {
	_, err := q.db.Exec(ctx, updateBillPayable,
		arg.ID,
		arg.CompanyID,
		arg.VendorID,
		arg.CategoryID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.DueDate,
		arg.Status,
		arg.Description,
		arg.Notes,
	)
	return err
}

const updateOverdueBillsPayable = `-- name: UpdateOverdueBillsPayable :exec
UPDATE bills_payable
SET status = 'overdue'
WHERE status = 'pending'
    AND due_date::DATE < CURRENT_DATE
`

func (q *Queries) UpdateOverdueBillsPayable(ctx context.Context) error {
	_, err := q.db.Exec(ctx, updateOverdueBillsPayable)
	return err
}
