// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_flow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCashInFlowByCategory = `-- name: GetCashInFlowByCategory :many
SELECT pc.name AS category_name,
    COALESCE(SUM(si.unit_price * si.quantity), 0)::FLOAT AS total_amount,
    COUNT(DISTINCT s.id) AS sales_count
FROM product_categories pc
    LEFT JOIN products p ON p.category_id = pc.id
    AND p.company_id = $1
    LEFT JOIN sale_items si ON si.product_id = p.id
    LEFT JOIN sales s ON s.id = si.sale_id
    AND s.company_id = $1
    AND s.status = 'paid'
WHERE pc.company_id = $1
    AND pc.status = 'ACTIVE'
GROUP BY pc.name
ORDER BY total_amount DESC
`

type GetCashInFlowByCategoryRow struct {
	CategoryName string  `json:"category_name"`
	TotalAmount  float64 `json:"total_amount"`
	SalesCount   int64   `json:"sales_count"`
}

func (q *Queries) GetCashInFlowByCategory(ctx context.Context, companyID pgtype.UUID) ([]GetCashInFlowByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getCashInFlowByCategory, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashInFlowByCategoryRow{}
	for rows.Next() {
		var i GetCashInFlowByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount, &i.SalesCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashInFlowCategoryByPeriod = `-- name: GetCashInFlowCategoryByPeriod :many
SELECT pc.name AS category_name,
    COALESCE(SUM(si.unit_price * si.quantity), 0)::FLOAT AS total_amount,
    COUNT(DISTINCT s.id) AS sales_count
FROM product_categories pc
    LEFT JOIN products p ON p.category_id = pc.id
    AND p.company_id = $1
    LEFT JOIN sale_items si ON si.product_id = p.id
    LEFT JOIN sales s ON s.id = si.sale_id
    AND s.company_id = $1
    AND s.status = 'paid'
    AND s.created_at BETWEEN $2 AND $3
WHERE pc.company_id = $1
    AND pc.status = 'ACTIVE'
GROUP BY pc.name
ORDER BY total_amount DESC
`

type GetCashInFlowCategoryByPeriodParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetCashInFlowCategoryByPeriodRow struct {
	CategoryName string  `json:"category_name"`
	TotalAmount  float64 `json:"total_amount"`
	SalesCount   int64   `json:"sales_count"`
}

func (q *Queries) GetCashInFlowCategoryByPeriod(ctx context.Context, arg GetCashInFlowCategoryByPeriodParams) ([]GetCashInFlowCategoryByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getCashInFlowCategoryByPeriod, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashInFlowCategoryByPeriodRow{}
	for rows.Next() {
		var i GetCashInFlowCategoryByPeriodRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount, &i.SalesCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashOutFlowByCategory = `-- name: GetCashOutFlowByCategory :many
SELECT bc.name AS category_name,
    COALESCE(SUM(COALESCE(b.amount_paid, b.amount)), 0)::FLOAT AS total_amount,
    COUNT(DISTINCT b.id) AS bills_count
FROM bill_categories bc
    LEFT JOIN bills_payable b ON b.category_id = bc.id
    AND b.company_id = $1
    AND b.status = 'paid'
WHERE bc.company_id = $1
    AND bc.is_active = TRUE
    AND bc.deleted_at IS NULL
GROUP BY bc.name
ORDER BY total_amount DESC
`

type GetCashOutFlowByCategoryRow struct {
	CategoryName string  `json:"category_name"`
	TotalAmount  float64 `json:"total_amount"`
	BillsCount   int64   `json:"bills_count"`
}

func (q *Queries) GetCashOutFlowByCategory(ctx context.Context, companyID pgtype.UUID) ([]GetCashOutFlowByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getCashOutFlowByCategory, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashOutFlowByCategoryRow{}
	for rows.Next() {
		var i GetCashOutFlowByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount, &i.BillsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashOutFlowCategoryByPeriod = `-- name: GetCashOutFlowCategoryByPeriod :many
SELECT bc.name AS category_name,
    COALESCE(SUM(COALESCE(b.amount_paid, b.amount)), 0)::FLOAT AS total_amount,
    COUNT(DISTINCT b.id) AS bills_count
FROM bill_categories bc
    LEFT JOIN bills_payable b ON b.category_id = bc.id
    AND b.company_id = $1
    AND b.status = 'paid'
WHERE bc.company_id = $1
    AND bc.is_active = TRUE
    AND bc.deleted_at IS NULL
    AND bc.created_at BETWEEN $2 AND $3
GROUP BY bc.name
ORDER BY total_amount DESC
`

type GetCashOutFlowCategoryByPeriodParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetCashOutFlowCategoryByPeriodRow struct {
	CategoryName string  `json:"category_name"`
	TotalAmount  float64 `json:"total_amount"`
	BillsCount   int64   `json:"bills_count"`
}

func (q *Queries) GetCashOutFlowCategoryByPeriod(ctx context.Context, arg GetCashOutFlowCategoryByPeriodParams) ([]GetCashOutFlowCategoryByPeriodRow, error) {
	rows, err := q.db.Query(ctx, getCashOutFlowCategoryByPeriod, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCashOutFlowCategoryByPeriodRow{}
	for rows.Next() {
		var i GetCashOutFlowCategoryByPeriodRow
		if err := rows.Scan(&i.CategoryName, &i.TotalAmount, &i.BillsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalInflowByPeriod = `-- name: GetTotalInflowByPeriod :one
SELECT COALESCE(SUM(total_amount), 0)::FLOAT AS total_inflow
FROM sales
WHERE company_id = $1
    AND created_at >= $2  -- Passar '2026-06-18T00:00:00Z'
    AND created_at < $3
`

type GetTotalInflowByPeriodParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetTotalInflowByPeriod(ctx context.Context, arg GetTotalInflowByPeriodParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalInflowByPeriod, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	var total_inflow float64
	err := row.Scan(&total_inflow)
	return total_inflow, err
}

const getTotalOutflowByPeriod = `-- name: GetTotalOutflowByPeriod :one
SELECT COALESCE(SUM(amount_paid), 0)::FLOAT AS total_outflow
FROM bills_payable
WHERE company_id = $1
    AND status = 'paid'
    AND payment_date BETWEEN $2 AND $3
`

type GetTotalOutflowByPeriodParams struct {
	CompanyID     pgtype.UUID `json:"company_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

func (q *Queries) GetTotalOutflowByPeriod(ctx context.Context, arg GetTotalOutflowByPeriodParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalOutflowByPeriod, arg.CompanyID, arg.PaymentDate, arg.PaymentDate_2)
	var total_outflow float64
	err := row.Scan(&total_outflow)
	return total_outflow, err
}
