// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_certificates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyCertificate = `-- name: CreateCompanyCertificate :one
INSERT INTO company_certificates(
        company_id,
        encrypted_cert_data,
        encrypted_cert_nonce,
        encrypted_password,
        encrypted_password_nonce,
        cert_subject_cn,
        expires_at,
        provider_status,
        provider_cert_id,
        created_by
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, encrypted_cert_data, encrypted_cert_nonce, encrypted_password, encrypted_password_nonce, cert_subject_cn, expires_at, provider_status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at, provider_cert_id
`

type CreateCompanyCertificateParams struct {
	CompanyID              pgtype.UUID        `json:"company_id"`
	EncryptedCertData      []byte             `json:"encrypted_cert_data"`
	EncryptedCertNonce     []byte             `json:"encrypted_cert_nonce"`
	EncryptedPassword      []byte             `json:"encrypted_password"`
	EncryptedPasswordNonce []byte             `json:"encrypted_password_nonce"`
	CertSubjectCn          pgtype.Text        `json:"cert_subject_cn"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	ProviderStatus         interface{}        `json:"provider_status"`
	ProviderCertID         pgtype.Text        `json:"provider_cert_id"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateCompanyCertificate(ctx context.Context, arg CreateCompanyCertificateParams) (CompanyCertificate, error) {
	row := q.db.QueryRow(ctx, createCompanyCertificate,
		arg.CompanyID,
		arg.EncryptedCertData,
		arg.EncryptedCertNonce,
		arg.EncryptedPassword,
		arg.EncryptedPasswordNonce,
		arg.CertSubjectCn,
		arg.ExpiresAt,
		arg.ProviderStatus,
		arg.ProviderCertID,
		arg.CreatedBy,
	)
	var i CompanyCertificate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EncryptedCertData,
		&i.EncryptedCertNonce,
		&i.EncryptedPassword,
		&i.EncryptedPasswordNonce,
		&i.CertSubjectCn,
		&i.ExpiresAt,
		&i.ProviderStatus,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProviderCertID,
	)
	return i, err
}

const deleteCompanyCertificate = `-- name: DeleteCompanyCertificate :exec
UPDATE company_certificates
SET deleted_at = NOW(),
    deleted_by = $2
WHERE company_id = $1
    AND deleted_at IS NULL
`

type DeleteCompanyCertificateParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteCompanyCertificate(ctx context.Context, arg DeleteCompanyCertificateParams) error {
	_, err := q.db.Exec(ctx, deleteCompanyCertificate, arg.CompanyID, arg.DeletedBy)
	return err
}

const getCompanyCertificateByCompanyID = `-- name: GetCompanyCertificateByCompanyID :one
SELECT id, company_id, encrypted_cert_data, encrypted_cert_nonce, encrypted_password, encrypted_password_nonce, cert_subject_cn, expires_at, provider_status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at, provider_cert_id
FROM company_certificates
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCompanyCertificateByCompanyID(ctx context.Context, companyID pgtype.UUID) (CompanyCertificate, error) {
	row := q.db.QueryRow(ctx, getCompanyCertificateByCompanyID, companyID)
	var i CompanyCertificate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EncryptedCertData,
		&i.EncryptedCertNonce,
		&i.EncryptedPassword,
		&i.EncryptedPasswordNonce,
		&i.CertSubjectCn,
		&i.ExpiresAt,
		&i.ProviderStatus,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProviderCertID,
	)
	return i, err
}

const updateCompanyCertificate = `-- name: UpdateCompanyCertificate :one
UPDATE company_certificates
SET encrypted_cert_data = $2,
    encrypted_cert_nonce = $3,
    encrypted_password = $4,
    encrypted_password_nonce = $5,
    cert_subject_cn = $6,
    expires_at = $7,
    provider_status = $8,
    provider_cert_id = $9,
    updated_by = $10,
    updated_at = NOW()
WHERE company_id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, encrypted_cert_data, encrypted_cert_nonce, encrypted_password, encrypted_password_nonce, cert_subject_cn, expires_at, provider_status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at, provider_cert_id
`

type UpdateCompanyCertificateParams struct {
	CompanyID              pgtype.UUID        `json:"company_id"`
	EncryptedCertData      []byte             `json:"encrypted_cert_data"`
	EncryptedCertNonce     []byte             `json:"encrypted_cert_nonce"`
	EncryptedPassword      []byte             `json:"encrypted_password"`
	EncryptedPasswordNonce []byte             `json:"encrypted_password_nonce"`
	CertSubjectCn          pgtype.Text        `json:"cert_subject_cn"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	ProviderStatus         interface{}        `json:"provider_status"`
	ProviderCertID         pgtype.Text        `json:"provider_cert_id"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateCompanyCertificate(ctx context.Context, arg UpdateCompanyCertificateParams) (CompanyCertificate, error) {
	row := q.db.QueryRow(ctx, updateCompanyCertificate,
		arg.CompanyID,
		arg.EncryptedCertData,
		arg.EncryptedCertNonce,
		arg.EncryptedPassword,
		arg.EncryptedPasswordNonce,
		arg.CertSubjectCn,
		arg.ExpiresAt,
		arg.ProviderStatus,
		arg.ProviderCertID,
		arg.UpdatedBy,
	)
	var i CompanyCertificate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EncryptedCertData,
		&i.EncryptedCertNonce,
		&i.EncryptedPassword,
		&i.EncryptedPasswordNonce,
		&i.CertSubjectCn,
		&i.ExpiresAt,
		&i.ProviderStatus,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProviderCertID,
	)
	return i, err
}
