// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies(
        name,
        trade_name,
        document,
        document_type,
        email,
        phone,
        website,
        address_street,
        address_number,
        address_complement,
        address_neighborhood,
        address_city,
        address_state,
        address_zipcode,
        address_country,
        timezone,
        created_by
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17
    )
RETURNING id, name, trade_name, document, document_type, email, phone, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, status, timezone, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateCompanyParams struct {
	Name                string      `json:"name"`
	TradeName           pgtype.Text `json:"trade_name"`
	Document            pgtype.Text `json:"document"`
	DocumentType        pgtype.Text `json:"document_type"`
	Email               pgtype.Text `json:"email"`
	Phone               pgtype.Text `json:"phone"`
	Website             pgtype.Text `json:"website"`
	AddressStreet       pgtype.Text `json:"address_street"`
	AddressNumber       pgtype.Text `json:"address_number"`
	AddressComplement   pgtype.Text `json:"address_complement"`
	AddressNeighborhood pgtype.Text `json:"address_neighborhood"`
	AddressCity         pgtype.Text `json:"address_city"`
	AddressState        pgtype.Text `json:"address_state"`
	AddressZipcode      pgtype.Text `json:"address_zipcode"`
	AddressCountry      pgtype.Text `json:"address_country"`
	Timezone            pgtype.Text `json:"timezone"`
	CreatedBy           pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.TradeName,
		arg.Document,
		arg.DocumentType,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.AddressStreet,
		arg.AddressNumber,
		arg.AddressComplement,
		arg.AddressNeighborhood,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZipcode,
		arg.AddressCountry,
		arg.Timezone,
		arg.CreatedBy,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TradeName,
		&i.Document,
		&i.DocumentType,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.AddressStreet,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressNeighborhood,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZipcode,
		&i.AddressCountry,
		&i.Status,
		&i.Timezone,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
UPDATE companies
SET deleted_at = NOW(),
    deleted_by = $2
WHERE id = $1
    AND deleted_at IS NULL
`

type DeleteCompanyParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteCompany(ctx context.Context, arg DeleteCompanyParams) error {
	_, err := q.db.Exec(ctx, deleteCompany, arg.ID, arg.DeletedBy)
	return err
}

const getCompanyByDocument = `-- name: GetCompanyByDocument :one
SELECT id, name, trade_name, document, document_type, email, phone, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, status, timezone, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM companies
WHERE document = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCompanyByDocument(ctx context.Context, document pgtype.Text) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByDocument, document)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TradeName,
		&i.Document,
		&i.DocumentType,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.AddressStreet,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressNeighborhood,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZipcode,
		&i.AddressCountry,
		&i.Status,
		&i.Timezone,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, trade_name, document, document_type, email, phone, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, status, timezone, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM companies
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TradeName,
		&i.Document,
		&i.DocumentType,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.AddressStreet,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressNeighborhood,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZipcode,
		&i.AddressCountry,
		&i.Status,
		&i.Timezone,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, trade_name, document, document_type, email, phone, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, status, timezone, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM companies
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TradeName,
			&i.Document,
			&i.DocumentType,
			&i.Email,
			&i.Phone,
			&i.Website,
			&i.AddressStreet,
			&i.AddressNumber,
			&i.AddressComplement,
			&i.AddressNeighborhood,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressZipcode,
			&i.AddressCountry,
			&i.Status,
			&i.Timezone,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCompanyStatus = `-- name: SetCompanyStatus :execrows
UPDATE companies
SET status = $2::status_enum
WHERE id = $1
`

type SetCompanyStatusParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) SetCompanyStatus(ctx context.Context, arg SetCompanyStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCompanyStatus, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2,
    trade_name = $3,
    document = $4,
    document_type = $5,
    email = $6,
    phone = $7,
    website = $8,
    address_street = $9,
    address_number = $10,
    address_complement = $11,
    address_neighborhood = $12,
    address_city = $13,
    address_state = $14,
    address_zipcode = $15,
    address_country = $16,
    timezone = $17,
    updated_by = $18,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, name, trade_name, document, document_type, email, phone, website, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, status, timezone, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateCompanyParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	TradeName           pgtype.Text `json:"trade_name"`
	Document            pgtype.Text `json:"document"`
	DocumentType        pgtype.Text `json:"document_type"`
	Email               pgtype.Text `json:"email"`
	Phone               pgtype.Text `json:"phone"`
	Website             pgtype.Text `json:"website"`
	AddressStreet       pgtype.Text `json:"address_street"`
	AddressNumber       pgtype.Text `json:"address_number"`
	AddressComplement   pgtype.Text `json:"address_complement"`
	AddressNeighborhood pgtype.Text `json:"address_neighborhood"`
	AddressCity         pgtype.Text `json:"address_city"`
	AddressState        pgtype.Text `json:"address_state"`
	AddressZipcode      pgtype.Text `json:"address_zipcode"`
	AddressCountry      pgtype.Text `json:"address_country"`
	Timezone            pgtype.Text `json:"timezone"`
	UpdatedBy           pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.TradeName,
		arg.Document,
		arg.DocumentType,
		arg.Email,
		arg.Phone,
		arg.Website,
		arg.AddressStreet,
		arg.AddressNumber,
		arg.AddressComplement,
		arg.AddressNeighborhood,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZipcode,
		arg.AddressCountry,
		arg.Timezone,
		arg.UpdatedBy,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TradeName,
		&i.Document,
		&i.DocumentType,
		&i.Email,
		&i.Phone,
		&i.Website,
		&i.AddressStreet,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressNeighborhood,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZipcode,
		&i.AddressCountry,
		&i.Status,
		&i.Timezone,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
