// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllCompanySettings = `-- name: DeleteAllCompanySettings :exec
DELETE FROM company_settings
WHERE company_id = $1
`

// Remove todas as configs de uma empresa — normalmente não precisa ser chamado
// manualmente (o ON DELETE CASCADE da FK já cuida disso quando a empresa é
// deletada), mas é útil pra um "reset de configurações" administrativo.
func (q *Queries) DeleteAllCompanySettings(ctx context.Context, companyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllCompanySettings, companyID)
	return err
}

const deleteCompanySetting = `-- name: DeleteCompanySetting :exec
DELETE FROM company_settings
WHERE company_id = $1 AND key = $2
`

type DeleteCompanySettingParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Key       string      `json:"key"`
}

// Remove uma config específica, voltando pro comportamento padrão do sistema
// (útil quando "ausência da linha" significa "usar o valor default").
func (q *Queries) DeleteCompanySetting(ctx context.Context, arg DeleteCompanySettingParams) error {
	_, err := q.db.Exec(ctx, deleteCompanySetting, arg.CompanyID, arg.Key)
	return err
}

const getCompanySetting = `-- name: GetCompanySetting :one
SELECT id, company_id, key, value, created_at, updated_at FROM company_settings
WHERE company_id = $1 AND key = $2
`

type GetCompanySettingParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Key       string      `json:"key"`
}

// Busca o valor de uma config específica de uma empresa.
func (q *Queries) GetCompanySetting(ctx context.Context, arg GetCompanySettingParams) (CompanySetting, error) {
	row := q.db.QueryRow(ctx, getCompanySetting, arg.CompanyID, arg.Key)
	var i CompanySetting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanySettings = `-- name: ListCompanySettings :many
SELECT id, company_id, key, value, created_at, updated_at FROM company_settings
WHERE company_id = $1
ORDER BY key
`

// Lista todas as configs de uma empresa de uma vez — útil pra telas de
// "configurações" que mostram tudo junto, evitando N chamadas separadas.
func (q *Queries) ListCompanySettings(ctx context.Context, companyID pgtype.UUID) ([]CompanySetting, error) {
	rows, err := q.db.Query(ctx, listCompanySettings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompanySetting{}
	for rows.Next() {
		var i CompanySetting
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompanySetting = `-- name: UpsertCompanySetting :one
INSERT INTO company_settings (
    company_id, key, value
) VALUES (
    $1, $2, $3
)
ON CONFLICT (company_id, key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = now()
RETURNING id, company_id, key, value, created_at, updated_at
`

type UpsertCompanySettingParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Key       string      `json:"key"`
	Value     string      `json:"value"`
}

// Cria a config se não existir, ou atualiza o valor se já existir
// (aproveita o UNIQUE (company_id, key) da tabela).
func (q *Queries) UpsertCompanySetting(ctx context.Context, arg UpsertCompanySettingParams) (CompanySetting, error) {
	row := q.db.QueryRow(ctx, upsertCompanySetting, arg.CompanyID, arg.Key, arg.Value)
	var i CompanySetting
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
