// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*)
FROM customers
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountCustomers(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomersByCompany = `-- name: CountCustomersByCompany :one
SELECT COUNT(*) FROM customers
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountCustomersByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomersByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomers = `-- name: CreateCustomers :one
INSERT INTO customers(
        company_id,
        full_name,
        birth_date,
        cpf,
        rg,
        marital_status,
        gender,
        whatsapp,
        mobile_phone,
        home_phone,
        email,
        address_street,
        address_number,
        address_complement,
        address_neighborhood,
        address_city,
        address_state,
        address_zipcode,
        address_country,
        balance_due,
        created_by
    )
VALUES(
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21
    )
RETURNING id
`

type CreateCustomersParams struct {
	CompanyID           pgtype.UUID    `json:"company_id"`
	FullName            string         `json:"full_name"`
	BirthDate           pgtype.Date    `json:"birth_date"`
	Cpf                 string         `json:"cpf"`
	Rg                  pgtype.Text    `json:"rg"`
	MaritalStatus       pgtype.Text    `json:"marital_status"`
	Gender              interface{}    `json:"gender"`
	Whatsapp            pgtype.Text    `json:"whatsapp"`
	MobilePhone         pgtype.Text    `json:"mobile_phone"`
	HomePhone           pgtype.Text    `json:"home_phone"`
	Email               string         `json:"email"`
	AddressStreet       pgtype.Text    `json:"address_street"`
	AddressNumber       pgtype.Text    `json:"address_number"`
	AddressComplement   pgtype.Text    `json:"address_complement"`
	AddressNeighborhood pgtype.Text    `json:"address_neighborhood"`
	AddressCity         pgtype.Text    `json:"address_city"`
	AddressState        pgtype.Text    `json:"address_state"`
	AddressZipcode      pgtype.Text    `json:"address_zipcode"`
	AddressCountry      pgtype.Text    `json:"address_country"`
	BalanceDue          pgtype.Numeric `json:"balance_due"`
	CreatedBy           pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateCustomers(ctx context.Context, arg CreateCustomersParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCustomers,
		arg.CompanyID,
		arg.FullName,
		arg.BirthDate,
		arg.Cpf,
		arg.Rg,
		arg.MaritalStatus,
		arg.Gender,
		arg.Whatsapp,
		arg.MobilePhone,
		arg.HomePhone,
		arg.Email,
		arg.AddressStreet,
		arg.AddressNumber,
		arg.AddressComplement,
		arg.AddressNeighborhood,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZipcode,
		arg.AddressCountry,
		arg.BalanceDue,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
UPDATE customers
SET deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $2
WHERE id = $1
    AND deleted_at IS NULL
`

type DeleteCustomerParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.DeletedBy)
	return err
}

const getCustomerByCPF = `-- name: GetCustomerByCPF :one
SELECT id, company_id, full_name, birth_date, cpf, rg, marital_status, gender, whatsapp, mobile_phone, home_phone, email, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, balance_due, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM customers
WHERE cpf = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCustomerByCPF(ctx context.Context, cpf string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByCPF, cpf)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FullName,
		&i.BirthDate,
		&i.Cpf,
		&i.Rg,
		&i.MaritalStatus,
		&i.Gender,
		&i.Whatsapp,
		&i.MobilePhone,
		&i.HomePhone,
		&i.Email,
		&i.AddressStreet,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressNeighborhood,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZipcode,
		&i.AddressCountry,
		&i.BalanceDue,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, company_id, full_name, birth_date, cpf, rg, marital_status, gender, whatsapp, mobile_phone, home_phone, email, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, balance_due, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM customers
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetCustomerById(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FullName,
		&i.BirthDate,
		&i.Cpf,
		&i.Rg,
		&i.MaritalStatus,
		&i.Gender,
		&i.Whatsapp,
		&i.MobilePhone,
		&i.HomePhone,
		&i.Email,
		&i.AddressStreet,
		&i.AddressNumber,
		&i.AddressComplement,
		&i.AddressNeighborhood,
		&i.AddressCity,
		&i.AddressState,
		&i.AddressZipcode,
		&i.AddressCountry,
		&i.BalanceDue,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomersPerformanceSummary = `-- name: GetCustomersPerformanceSummary :one
SELECT COUNT(*) FILTER (
        WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
    ) AS current_month_count,
    COUNT(*) FILTER (
        WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
    ) AS last_month_count
FROM customers
WHERE company_id = $1
    AND deleted_at IS NULL
    AND created_at >= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
`

type GetCustomersPerformanceSummaryRow struct {
	CurrentMonthCount int64 `json:"current_month_count"`
	LastMonthCount    int64 `json:"last_month_count"`
}

func (q *Queries) GetCustomersPerformanceSummary(ctx context.Context, companyID pgtype.UUID) (GetCustomersPerformanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCustomersPerformanceSummary, companyID)
	var i GetCustomersPerformanceSummaryRow
	err := row.Scan(&i.CurrentMonthCount, &i.LastMonthCount)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, company_id, full_name, birth_date, cpf, rg, marital_status, gender, whatsapp, mobile_phone, home_phone, email, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, balance_due, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM customers
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) ListCustomers(ctx context.Context, companyID pgtype.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FullName,
			&i.BirthDate,
			&i.Cpf,
			&i.Rg,
			&i.MaritalStatus,
			&i.Gender,
			&i.Whatsapp,
			&i.MobilePhone,
			&i.HomePhone,
			&i.Email,
			&i.AddressStreet,
			&i.AddressNumber,
			&i.AddressComplement,
			&i.AddressNeighborhood,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressZipcode,
			&i.AddressCountry,
			&i.BalanceDue,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersPaginate = `-- name: ListCustomersPaginate :many
SELECT id, company_id, full_name, birth_date, cpf, rg, marital_status, gender, whatsapp, mobile_phone, home_phone, email, address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zipcode, address_country, balance_due, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM customers
WHERE company_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListCustomersPaginateParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListCustomersPaginate(ctx context.Context, arg ListCustomersPaginateParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersPaginate, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FullName,
			&i.BirthDate,
			&i.Cpf,
			&i.Rg,
			&i.MaritalStatus,
			&i.Gender,
			&i.Whatsapp,
			&i.MobilePhone,
			&i.HomePhone,
			&i.Email,
			&i.AddressStreet,
			&i.AddressNumber,
			&i.AddressComplement,
			&i.AddressNeighborhood,
			&i.AddressCity,
			&i.AddressState,
			&i.AddressZipcode,
			&i.AddressCountry,
			&i.BalanceDue,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalanceDueCustomer = `-- name: UpdateBalanceDueCustomer :exec
UPDATE customers
SET balance_due = balance_due + $2,
    updated_by = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
`

type UpdateBalanceDueCustomerParams struct {
	ID         pgtype.UUID    `json:"id"`
	BalanceDue pgtype.Numeric `json:"balance_due"`
	UpdatedBy  pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpdateBalanceDueCustomer(ctx context.Context, arg UpdateBalanceDueCustomerParams) error {
	_, err := q.db.Exec(ctx, updateBalanceDueCustomer, arg.ID, arg.BalanceDue, arg.UpdatedBy)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :exec
UPDATE customers
SET full_name = $2,
    birth_date = $3,
    cpf = $4,
    rg = $5,
    marital_status = $6,
    gender = $7,
    whatsapp = $8,
    mobile_phone = $9,
    home_phone = $10,
    email = $11,
    address_street = $12,
    address_number = $13,
    address_complement = $14,
    address_neighborhood = $15,
    address_city = $16,
    address_state = $17,
    address_zipcode = $18,
    address_country = $19,
    balance_due = $20,
    updated_by = $21,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
`

type UpdateCustomerParams struct {
	ID                  pgtype.UUID    `json:"id"`
	FullName            string         `json:"full_name"`
	BirthDate           pgtype.Date    `json:"birth_date"`
	Cpf                 string         `json:"cpf"`
	Rg                  pgtype.Text    `json:"rg"`
	MaritalStatus       pgtype.Text    `json:"marital_status"`
	Gender              interface{}    `json:"gender"`
	Whatsapp            pgtype.Text    `json:"whatsapp"`
	MobilePhone         pgtype.Text    `json:"mobile_phone"`
	HomePhone           pgtype.Text    `json:"home_phone"`
	Email               string         `json:"email"`
	AddressStreet       pgtype.Text    `json:"address_street"`
	AddressNumber       pgtype.Text    `json:"address_number"`
	AddressComplement   pgtype.Text    `json:"address_complement"`
	AddressNeighborhood pgtype.Text    `json:"address_neighborhood"`
	AddressCity         pgtype.Text    `json:"address_city"`
	AddressState        pgtype.Text    `json:"address_state"`
	AddressZipcode      pgtype.Text    `json:"address_zipcode"`
	AddressCountry      pgtype.Text    `json:"address_country"`
	BalanceDue          pgtype.Numeric `json:"balance_due"`
	UpdatedBy           pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error {
	_, err := q.db.Exec(ctx, updateCustomer,
		arg.ID,
		arg.FullName,
		arg.BirthDate,
		arg.Cpf,
		arg.Rg,
		arg.MaritalStatus,
		arg.Gender,
		arg.Whatsapp,
		arg.MobilePhone,
		arg.HomePhone,
		arg.Email,
		arg.AddressStreet,
		arg.AddressNumber,
		arg.AddressComplement,
		arg.AddressNeighborhood,
		arg.AddressCity,
		arg.AddressState,
		arg.AddressZipcode,
		arg.AddressCountry,
		arg.BalanceDue,
		arg.UpdatedBy,
	)
	return err
}

const updateCustomerBalance = `-- name: UpdateCustomerBalance :exec
UPDATE customers
SET balance_due = $2,
    -- Atribui o valor final calculado no Go
    updated_by = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
    AND deleted_at IS NULL
`

type UpdateCustomerBalanceParams struct {
	ID         pgtype.UUID    `json:"id"`
	BalanceDue pgtype.Numeric `json:"balance_due"`
	UpdatedBy  pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpdateCustomerBalance(ctx context.Context, arg UpdateCustomerBalanceParams) error {
	_, err := q.db.Exec(ctx, updateCustomerBalance, arg.ID, arg.BalanceDue, arg.UpdatedBy)
	return err
}
