// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department_modules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addModuleToDepartment = `-- name: AddModuleToDepartment :exec
INSERT INTO department_modules (department_id, module_code)
VALUES ($1, $2)
ON CONFLICT (department_id, module_code) DO NOTHING
`

type AddModuleToDepartmentParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	ModuleCode   string      `json:"module_code"`
}

func (q *Queries) AddModuleToDepartment(ctx context.Context, arg AddModuleToDepartmentParams) error {
	_, err := q.db.Exec(ctx, addModuleToDepartment, arg.DepartmentID, arg.ModuleCode)
	return err
}

const departmentHasModule = `-- name: DepartmentHasModule :one
SELECT EXISTS (
    SELECT 1
    FROM department_modules
    WHERE department_id = $1
      AND module_code = $2
) AS has_access
`

type DepartmentHasModuleParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	ModuleCode   string      `json:"module_code"`
}

func (q *Queries) DepartmentHasModule(ctx context.Context, arg DepartmentHasModuleParams) (bool, error) {
	row := q.db.QueryRow(ctx, departmentHasModule, arg.DepartmentID, arg.ModuleCode)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const listModulesByDepartment = `-- name: ListModulesByDepartment :many
SELECT m.code, m.name
FROM department_modules dm
JOIN modules m ON m.code = dm.module_code
WHERE dm.department_id = $1
ORDER BY m.name
`

func (q *Queries) ListModulesByDepartment(ctx context.Context, departmentID pgtype.UUID) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeModuleFromDepartment = `-- name: RemoveModuleFromDepartment :exec
DELETE FROM department_modules
WHERE department_id = $1
  AND module_code = $2
`

type RemoveModuleFromDepartmentParams struct {
	DepartmentID pgtype.UUID `json:"department_id"`
	ModuleCode   string      `json:"module_code"`
}

func (q *Queries) RemoveModuleFromDepartment(ctx context.Context, arg RemoveModuleFromDepartmentParams) error {
	_, err := q.db.Exec(ctx, removeModuleFromDepartment, arg.DepartmentID, arg.ModuleCode)
	return err
}

const replaceDepartmentModules = `-- name: ReplaceDepartmentModules :exec
DELETE FROM department_modules
WHERE department_id = $1
`

func (q *Queries) ReplaceDepartmentModules(ctx context.Context, departmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceDepartmentModules, departmentID)
	return err
}
