// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments(
        company_id,
        name,
        description,
        created_by
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, company_id, name, description, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateDepartmentParams struct {
	CompanyID   pgtype.UUID `json:"company_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
UPDATE departments
SET deleted_at = NOW(),
    deleted_by = $2
WHERE id = $1
`

type DeleteDepartmentParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.Exec(ctx, deleteDepartment, arg.ID, arg.DeletedBy)
	return err
}

const getDepartmentById = `-- name: GetDepartmentById :one
SELECT id, company_id, name, description, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM departments
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetDepartmentById(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentById, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDepartmentsByCompanyId = `-- name: ListDepartmentsByCompanyId :many
SELECT id, company_id, name, description, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM departments
WHERE company_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDepartmentsByCompanyId(ctx context.Context, companyID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartmentsByCompanyId, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatusDepartment = `-- name: SetStatusDepartment :execrows
UPDATE departments
SET status = $2::status_enum,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1
`

type SetStatusDepartmentParams struct {
	ID        pgtype.UUID `json:"id"`
	Column2   interface{} `json:"column_2"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetStatusDepartment(ctx context.Context, arg SetStatusDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStatusDepartment, arg.ID, arg.Column2, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2,
    description = $3,
    updated_by = $4,
    updated_by = NOW()
WHERE id = $1
RETURNING id, company_id, name, description, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateDepartmentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UpdatedBy,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
