// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fiscal_invoices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFiscalInvoice = `-- name: CreateFiscalInvoice :one
INSERT INTO fiscal_invoices(
        company_id,
        sale_id,
        type,
        status,
        created_by
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateFiscalInvoiceParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	SaleID    pgtype.UUID `json:"sale_id"`
	Type      interface{} `json:"type"`
	Status    interface{} `json:"status"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateFiscalInvoice(ctx context.Context, arg CreateFiscalInvoiceParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, createFiscalInvoice,
		arg.CompanyID,
		arg.SaleID,
		arg.Type,
		arg.Status,
		arg.CreatedBy,
	)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createFiscalInvoiceEvent = `-- name: CreateFiscalInvoiceEvent :one
INSERT INTO fiscal_invoice_events(
        fiscal_invoice_id,
        event_type,
        payload
    )
VALUES ($1, $2, $3)
RETURNING id, fiscal_invoice_id, event_type, payload, created_at
`

type CreateFiscalInvoiceEventParams struct {
	FiscalInvoiceID pgtype.UUID `json:"fiscal_invoice_id"`
	EventType       interface{} `json:"event_type"`
	Payload         []byte      `json:"payload"`
}

func (q *Queries) CreateFiscalInvoiceEvent(ctx context.Context, arg CreateFiscalInvoiceEventParams) (FiscalInvoiceEvent, error) {
	row := q.db.QueryRow(ctx, createFiscalInvoiceEvent, arg.FiscalInvoiceID, arg.EventType, arg.Payload)
	var i FiscalInvoiceEvent
	err := row.Scan(
		&i.ID,
		&i.FiscalInvoiceID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getFiscalInvoiceByID = `-- name: GetFiscalInvoiceByID :one
SELECT id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM fiscal_invoices
WHERE id = $1
    AND company_id = $2
    AND deleted_at IS NULL
`

type GetFiscalInvoiceByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) GetFiscalInvoiceByID(ctx context.Context, arg GetFiscalInvoiceByIDParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, getFiscalInvoiceByID, arg.ID, arg.CompanyID)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFiscalInvoiceByProviderInvoiceID = `-- name: GetFiscalInvoiceByProviderInvoiceID :one
SELECT id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM fiscal_invoices
WHERE provider_invoice_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetFiscalInvoiceByProviderInvoiceID(ctx context.Context, providerInvoiceID pgtype.Text) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, getFiscalInvoiceByProviderInvoiceID, providerInvoiceID)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFiscalInvoiceBySaleAndType = `-- name: GetFiscalInvoiceBySaleAndType :one
SELECT id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM fiscal_invoices
WHERE sale_id = $1
    AND type = $2
    AND deleted_at IS NULL
`

type GetFiscalInvoiceBySaleAndTypeParams struct {
	SaleID pgtype.UUID `json:"sale_id"`
	Type   interface{} `json:"type"`
}

func (q *Queries) GetFiscalInvoiceBySaleAndType(ctx context.Context, arg GetFiscalInvoiceBySaleAndTypeParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, getFiscalInvoiceBySaleAndType, arg.SaleID, arg.Type)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFiscalInvoiceEventsByInvoiceID = `-- name: ListFiscalInvoiceEventsByInvoiceID :many
SELECT id, fiscal_invoice_id, event_type, payload, created_at
FROM fiscal_invoice_events
WHERE fiscal_invoice_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFiscalInvoiceEventsByInvoiceID(ctx context.Context, fiscalInvoiceID pgtype.UUID) ([]FiscalInvoiceEvent, error) {
	rows, err := q.db.Query(ctx, listFiscalInvoiceEventsByInvoiceID, fiscalInvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FiscalInvoiceEvent{}
	for rows.Next() {
		var i FiscalInvoiceEvent
		if err := rows.Scan(
			&i.ID,
			&i.FiscalInvoiceID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFiscalInvoicesBySale = `-- name: ListFiscalInvoicesBySale :many
SELECT id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM fiscal_invoices
WHERE sale_id = $1
    AND company_id = $2
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListFiscalInvoicesBySaleParams struct {
	SaleID    pgtype.UUID `json:"sale_id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) ListFiscalInvoicesBySale(ctx context.Context, arg ListFiscalInvoicesBySaleParams) ([]FiscalInvoice, error) {
	rows, err := q.db.Query(ctx, listFiscalInvoicesBySale, arg.SaleID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FiscalInvoice{}
	for rows.Next() {
		var i FiscalInvoice
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SaleID,
			&i.Type,
			&i.Status,
			&i.ProviderInvoiceID,
			&i.ChaveAcesso,
			&i.Numero,
			&i.Serie,
			&i.ProtocoloAutorizacao,
			&i.XmlUrl,
			&i.DanfeUrl,
			&i.ErrorMessage,
			&i.CancelledReason,
			&i.AuthorizedAt,
			&i.CancelledAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleProcessingFiscalInvoices = `-- name: ListStaleProcessingFiscalInvoices :many
SELECT id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM fiscal_invoices
WHERE status IN ('processing', 'cancel_processing')
    AND provider_invoice_id IS NOT NULL
    AND updated_at < $1
    AND deleted_at IS NULL
ORDER BY updated_at ASC
LIMIT 200
`

// Documentos presos em 'processing'/'cancel_processing' há mais de $1 —
// usados pela reconciliação periódica como rede de segurança para quando o
// webhook do provedor não chega (ver internal/worker).
func (q *Queries) ListStaleProcessingFiscalInvoices(ctx context.Context, updatedAt pgtype.Timestamptz) ([]FiscalInvoice, error) {
	rows, err := q.db.Query(ctx, listStaleProcessingFiscalInvoices, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FiscalInvoice{}
	for rows.Next() {
		var i FiscalInvoice
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.SaleID,
			&i.Type,
			&i.Status,
			&i.ProviderInvoiceID,
			&i.ChaveAcesso,
			&i.Numero,
			&i.Serie,
			&i.ProtocoloAutorizacao,
			&i.XmlUrl,
			&i.DanfeUrl,
			&i.ErrorMessage,
			&i.CancelledReason,
			&i.AuthorizedAt,
			&i.CancelledAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFiscalInvoiceForRetry = `-- name: ResetFiscalInvoiceForRetry :one
UPDATE fiscal_invoices
SET status = 'processing',
    provider_invoice_id = NULL,
    error_message = NULL,
    cancelled_reason = NULL,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

// Reabre um documento fiscal 'rejected'/'cancelled' para uma nova tentativa
// de emissão, reaproveitando o mesmo id (usado como idIntegracao no
// provedor) em vez de criar uma linha nova — UNIQUE(sale_id, type) impediria
// a duplicata mesmo que tentássemos.
func (q *Queries) ResetFiscalInvoiceForRetry(ctx context.Context, id pgtype.UUID) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, resetFiscalInvoiceForRetry, id)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFiscalInvoiceAuthorized = `-- name: UpdateFiscalInvoiceAuthorized :one
UPDATE fiscal_invoices
SET status = 'authorized',
    chave_acesso = $2,
    numero = $3,
    serie = $4,
    protocolo_autorizacao = $5,
    xml_url = COALESCE($6, xml_url),
    danfe_url = COALESCE($7, danfe_url),
    authorized_at = NOW(),
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateFiscalInvoiceAuthorizedParams struct {
	ID                   pgtype.UUID `json:"id"`
	ChaveAcesso          pgtype.Text `json:"chave_acesso"`
	Numero               pgtype.Text `json:"numero"`
	Serie                pgtype.Text `json:"serie"`
	ProtocoloAutorizacao pgtype.Text `json:"protocolo_autorizacao"`
	XmlUrl               pgtype.Text `json:"xml_url"`
	DanfeUrl             pgtype.Text `json:"danfe_url"`
}

// xml_url/danfe_url usam COALESCE porque a reconciliação periódica (GET
// .../resumo) não traz esses links, só o webhook traz — não pode apagar um
// link já conhecido só porque essa chamada específica não o tem.
func (q *Queries) UpdateFiscalInvoiceAuthorized(ctx context.Context, arg UpdateFiscalInvoiceAuthorizedParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, updateFiscalInvoiceAuthorized,
		arg.ID,
		arg.ChaveAcesso,
		arg.Numero,
		arg.Serie,
		arg.ProtocoloAutorizacao,
		arg.XmlUrl,
		arg.DanfeUrl,
	)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFiscalInvoiceCancelProcessing = `-- name: UpdateFiscalInvoiceCancelProcessing :one
UPDATE fiscal_invoices
SET status = 'cancel_processing',
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateFiscalInvoiceCancelProcessing(ctx context.Context, id pgtype.UUID) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, updateFiscalInvoiceCancelProcessing, id)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFiscalInvoiceCancelled = `-- name: UpdateFiscalInvoiceCancelled :one
UPDATE fiscal_invoices
SET status = 'cancelled',
    cancelled_reason = $2,
    cancelled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateFiscalInvoiceCancelledParams struct {
	ID              pgtype.UUID `json:"id"`
	CancelledReason pgtype.Text `json:"cancelled_reason"`
}

func (q *Queries) UpdateFiscalInvoiceCancelled(ctx context.Context, arg UpdateFiscalInvoiceCancelledParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, updateFiscalInvoiceCancelled, arg.ID, arg.CancelledReason)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFiscalInvoiceProcessing = `-- name: UpdateFiscalInvoiceProcessing :one
UPDATE fiscal_invoices
SET provider_invoice_id = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateFiscalInvoiceProcessingParams struct {
	ID                pgtype.UUID `json:"id"`
	ProviderInvoiceID pgtype.Text `json:"provider_invoice_id"`
	Status            interface{} `json:"status"`
}

func (q *Queries) UpdateFiscalInvoiceProcessing(ctx context.Context, arg UpdateFiscalInvoiceProcessingParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, updateFiscalInvoiceProcessing, arg.ID, arg.ProviderInvoiceID, arg.Status)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFiscalInvoiceRejected = `-- name: UpdateFiscalInvoiceRejected :one
UPDATE fiscal_invoices
SET status = 'rejected',
    error_message = $2,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, sale_id, type, status, provider_invoice_id, chave_acesso, numero, serie, protocolo_autorizacao, xml_url, danfe_url, error_message, cancelled_reason, authorized_at, cancelled_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateFiscalInvoiceRejectedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateFiscalInvoiceRejected(ctx context.Context, arg UpdateFiscalInvoiceRejectedParams) (FiscalInvoice, error) {
	row := q.db.QueryRow(ctx, updateFiscalInvoiceRejected, arg.ID, arg.ErrorMessage)
	var i FiscalInvoice
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.SaleID,
		&i.Type,
		&i.Status,
		&i.ProviderInvoiceID,
		&i.ChaveAcesso,
		&i.Numero,
		&i.Serie,
		&i.ProtocoloAutorizacao,
		&i.XmlUrl,
		&i.DanfeUrl,
		&i.ErrorMessage,
		&i.CancelledReason,
		&i.AuthorizedAt,
		&i.CancelledAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
