// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInvoices = `-- name: CountInvoices :one
SELECT COUNT(*) FROM invoice_history WHERE company_id = $1
`

func (q *Queries) CountInvoices(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoices, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoiceHistory = `-- name: CreateInvoiceHistory :exec
INSERT INTO invoice_history (
    subscription_id,
    company_id,
    payment_method_id,
    external_payment_id,
    amount_cents,
    status,
    paid_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateInvoiceHistoryParams struct {
	SubscriptionID    pgtype.UUID        `json:"subscription_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	PaymentMethodID   pgtype.UUID        `json:"payment_method_id"`
	ExternalPaymentID string             `json:"external_payment_id"`
	AmountCents       int32              `json:"amount_cents"`
	Status            string             `json:"status"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreateInvoiceHistory(ctx context.Context, arg CreateInvoiceHistoryParams) error {
	_, err := q.db.Exec(ctx, createInvoiceHistory,
		arg.SubscriptionID,
		arg.CompanyID,
		arg.PaymentMethodID,
		arg.ExternalPaymentID,
		arg.AmountCents,
		arg.Status,
		arg.PaidAt,
	)
	return err
}

const getInvoiceById = `-- name: GetInvoiceById :one
SELECT id, subscription_id, company_id, payment_method_id, external_payment_id, amount_cents, status, paid_at, created_at, updated_at FROM invoice_history
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceById(ctx context.Context, id pgtype.UUID) (InvoiceHistory, error) {
	row := q.db.QueryRow(ctx, getInvoiceById, id)
	var i InvoiceHistory
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.CompanyID,
		&i.PaymentMethodID,
		&i.ExternalPaymentID,
		&i.AmountCents,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByMpPaymentId = `-- name: GetInvoiceByMpPaymentId :one
SELECT id, subscription_id, company_id, payment_method_id, external_payment_id, amount_cents, status, paid_at, created_at, updated_at FROM invoice_history
WHERE external_payment_id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceByMpPaymentId(ctx context.Context, externalPaymentID string) (InvoiceHistory, error) {
	row := q.db.QueryRow(ctx, getInvoiceByMpPaymentId, externalPaymentID)
	var i InvoiceHistory
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.CompanyID,
		&i.PaymentMethodID,
		&i.ExternalPaymentID,
		&i.AmountCents,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoicesByCompany = `-- name: ListInvoicesByCompany :many
SELECT id, subscription_id, company_id, payment_method_id, external_payment_id, amount_cents, status, paid_at, created_at, updated_at FROM invoice_history
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesByCompanyParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListInvoicesByCompany(ctx context.Context, arg ListInvoicesByCompanyParams) ([]InvoiceHistory, error) {
	rows, err := q.db.Query(ctx, listInvoicesByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvoiceHistory{}
	for rows.Next() {
		var i InvoiceHistory
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.CompanyID,
			&i.PaymentMethodID,
			&i.ExternalPaymentID,
			&i.AmountCents,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :exec
UPDATE invoice_history
SET 
    status = $2,
    paid_at = $3,
    updated_at = NOW()
WHERE external_payment_id = $1
`

type UpdateInvoiceStatusParams struct {
	ExternalPaymentID string             `json:"external_payment_id"`
	Status            string             `json:"status"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceStatus, arg.ExternalPaymentID, arg.Status, arg.PaidAt)
	return err
}
