// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meta_whatsapp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesInPeriod = `-- name: CountMessagesInPeriod :one
SELECT COUNT(*) AS total
FROM whatsapp_messages
WHERE company_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND status IN ('sent', 'delivered', 'read')
`

type CountMessagesInPeriodParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

// Alimenta o job de sincronização de uso mensal com o Stripe.
func (q *Queries) CountMessagesInPeriod(ctx context.Context, arg CountMessagesInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesInPeriod, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createWhatsAppMessage = `-- name: CreateWhatsAppMessage :one
INSERT INTO whatsapp_messages (
    company_id, template_id, category, recipient_phone,
    meta_message_id, status, estimated_cost_cents
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, company_id, template_id, category, recipient_phone, meta_message_id, status, failure_code, failure_reason, estimated_cost_cents, sent_at, delivered_at, created_at
`

type CreateWhatsAppMessageParams struct {
	CompanyID          pgtype.UUID             `json:"company_id"`
	TemplateID         pgtype.UUID             `json:"template_id"`
	Category           WhatsappMessageCategory `json:"category"`
	RecipientPhone     string                  `json:"recipient_phone"`
	MetaMessageID      pgtype.Text             `json:"meta_message_id"`
	Status             WhatsappMessageStatus   `json:"status"`
	EstimatedCostCents pgtype.Int4             `json:"estimated_cost_cents"`
}

func (q *Queries) CreateWhatsAppMessage(ctx context.Context, arg CreateWhatsAppMessageParams) (WhatsappMessage, error) {
	row := q.db.QueryRow(ctx, createWhatsAppMessage,
		arg.CompanyID,
		arg.TemplateID,
		arg.Category,
		arg.RecipientPhone,
		arg.MetaMessageID,
		arg.Status,
		arg.EstimatedCostCents,
	)
	var i WhatsappMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TemplateID,
		&i.Category,
		&i.RecipientPhone,
		&i.MetaMessageID,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.EstimatedCostCents,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyWhatsAppConfig = `-- name: GetCompanyWhatsAppConfig :one
SELECT id, company_id, mode, waba_id, phone_number_id, display_phone_number, access_token_encrypted, monthly_message_allowance, is_active, created_at, updated_at FROM company_whatsapp_configs
WHERE company_id = $1
`

func (q *Queries) GetCompanyWhatsAppConfig(ctx context.Context, companyID pgtype.UUID) (CompanyWhatsappConfig, error) {
	row := q.db.QueryRow(ctx, getCompanyWhatsAppConfig, companyID)
	var i CompanyWhatsappConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Mode,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.DisplayPhoneNumber,
		&i.AccessTokenEncrypted,
		&i.MonthlyMessageAllowance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEligibleTemplateByName = `-- name: GetEligibleTemplateByName :one
SELECT id, meta_template_name, category, language_code, body_text, variables, is_platform_shared_eligible, meta_approval_status, created_at, updated_at FROM whatsapp_templates
WHERE meta_template_name = $1
  AND language_code = $2
  AND is_platform_shared_eligible = true
  AND meta_approval_status = 'approved'
`

type GetEligibleTemplateByNameParams struct {
	MetaTemplateName string `json:"meta_template_name"`
	LanguageCode     string `json:"language_code"`
}

// Usado pelo serviço de disparo pra validar se um template pode ser usado
// no WABA compartilhado antes de chamar a Graph API.
func (q *Queries) GetEligibleTemplateByName(ctx context.Context, arg GetEligibleTemplateByNameParams) (WhatsappTemplate, error) {
	row := q.db.QueryRow(ctx, getEligibleTemplateByName, arg.MetaTemplateName, arg.LanguageCode)
	var i WhatsappTemplate
	err := row.Scan(
		&i.ID,
		&i.MetaTemplateName,
		&i.Category,
		&i.LanguageCode,
		&i.BodyText,
		&i.Variables,
		&i.IsPlatformSharedEligible,
		&i.MetaApprovalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByMetaID = `-- name: GetMessageByMetaID :one
SELECT id, company_id, template_id, category, recipient_phone, meta_message_id, status, failure_code, failure_reason, estimated_cost_cents, sent_at, delivered_at, created_at FROM whatsapp_messages
WHERE meta_message_id = $1
`

func (q *Queries) GetMessageByMetaID(ctx context.Context, metaMessageID pgtype.Text) (WhatsappMessage, error) {
	row := q.db.QueryRow(ctx, getMessageByMetaID, metaMessageID)
	var i WhatsappMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TemplateID,
		&i.Category,
		&i.RecipientPhone,
		&i.MetaMessageID,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.EstimatedCostCents,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedTemplates = `-- name: ListApprovedTemplates :many
SELECT id, meta_template_name, category, language_code, body_text, variables, is_platform_shared_eligible, meta_approval_status, created_at, updated_at FROM whatsapp_templates
WHERE meta_approval_status = 'approved'
ORDER BY category, meta_template_name
`

func (q *Queries) ListApprovedTemplates(ctx context.Context) ([]WhatsappTemplate, error) {
	rows, err := q.db.Query(ctx, listApprovedTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WhatsappTemplate{}
	for rows.Next() {
		var i WhatsappTemplate
		if err := rows.Scan(
			&i.ID,
			&i.MetaTemplateName,
			&i.Category,
			&i.LanguageCode,
			&i.BodyText,
			&i.Variables,
			&i.IsPlatformSharedEligible,
			&i.MetaApprovalStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUsageSyncedWithStripe = `-- name: MarkUsageSyncedWithStripe :exec
UPDATE whatsapp_usage_monthly SET
    stripe_usage_record_id = $2,
    synced_at = now()
WHERE id = $1
`

type MarkUsageSyncedWithStripeParams struct {
	ID                  pgtype.UUID `json:"id"`
	StripeUsageRecordID pgtype.Text `json:"stripe_usage_record_id"`
}

func (q *Queries) MarkUsageSyncedWithStripe(ctx context.Context, arg MarkUsageSyncedWithStripeParams) error {
	_, err := q.db.Exec(ctx, markUsageSyncedWithStripe, arg.ID, arg.StripeUsageRecordID)
	return err
}

const updateWhatsAppMessageStatus = `-- name: UpdateWhatsAppMessageStatus :one
UPDATE whatsapp_messages SET
    status = $2,
    failure_code = $3,
    failure_reason = $4,
    delivered_at = CASE WHEN $2 = 'delivered' THEN now() ELSE delivered_at END,
    sent_at = CASE WHEN $2 = 'sent' AND sent_at IS NULL THEN now() ELSE sent_at END
WHERE meta_message_id = $1
RETURNING id, company_id, template_id, category, recipient_phone, meta_message_id, status, failure_code, failure_reason, estimated_cost_cents, sent_at, delivered_at, created_at
`

type UpdateWhatsAppMessageStatusParams struct {
	MetaMessageID pgtype.Text           `json:"meta_message_id"`
	Status        WhatsappMessageStatus `json:"status"`
	FailureCode   pgtype.Int4           `json:"failure_code"`
	FailureReason pgtype.Text           `json:"failure_reason"`
}

// Chamado pelo handler de webhook quando chega um status novo (sent/delivered/failed).
func (q *Queries) UpdateWhatsAppMessageStatus(ctx context.Context, arg UpdateWhatsAppMessageStatusParams) (WhatsappMessage, error) {
	row := q.db.QueryRow(ctx, updateWhatsAppMessageStatus,
		arg.MetaMessageID,
		arg.Status,
		arg.FailureCode,
		arg.FailureReason,
	)
	var i WhatsappMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TemplateID,
		&i.Category,
		&i.RecipientPhone,
		&i.MetaMessageID,
		&i.Status,
		&i.FailureCode,
		&i.FailureReason,
		&i.EstimatedCostCents,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCompanyWhatsAppConfig = `-- name: UpsertCompanyWhatsAppConfig :one
INSERT INTO company_whatsapp_configs (
    company_id, mode, waba_id, phone_number_id, display_phone_number,
    access_token_encrypted, monthly_message_allowance, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (company_id) DO UPDATE SET
    mode = EXCLUDED.mode,
    waba_id = EXCLUDED.waba_id,
    phone_number_id = EXCLUDED.phone_number_id,
    display_phone_number = EXCLUDED.display_phone_number,
    access_token_encrypted = EXCLUDED.access_token_encrypted,
    monthly_message_allowance = EXCLUDED.monthly_message_allowance,
    is_active = EXCLUDED.is_active,
    updated_at = now()
RETURNING id, company_id, mode, waba_id, phone_number_id, display_phone_number, access_token_encrypted, monthly_message_allowance, is_active, created_at, updated_at
`

type UpsertCompanyWhatsAppConfigParams struct {
	CompanyID               pgtype.UUID  `json:"company_id"`
	Mode                    WhatsappMode `json:"mode"`
	WabaID                  pgtype.Text  `json:"waba_id"`
	PhoneNumberID           pgtype.Text  `json:"phone_number_id"`
	DisplayPhoneNumber      pgtype.Text  `json:"display_phone_number"`
	AccessTokenEncrypted    pgtype.Text  `json:"access_token_encrypted"`
	MonthlyMessageAllowance int32        `json:"monthly_message_allowance"`
	IsActive                bool         `json:"is_active"`
}

func (q *Queries) UpsertCompanyWhatsAppConfig(ctx context.Context, arg UpsertCompanyWhatsAppConfigParams) (CompanyWhatsappConfig, error) {
	row := q.db.QueryRow(ctx, upsertCompanyWhatsAppConfig,
		arg.CompanyID,
		arg.Mode,
		arg.WabaID,
		arg.PhoneNumberID,
		arg.DisplayPhoneNumber,
		arg.AccessTokenEncrypted,
		arg.MonthlyMessageAllowance,
		arg.IsActive,
	)
	var i CompanyWhatsappConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Mode,
		&i.WabaID,
		&i.PhoneNumberID,
		&i.DisplayPhoneNumber,
		&i.AccessTokenEncrypted,
		&i.MonthlyMessageAllowance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMonthlyUsage = `-- name: UpsertMonthlyUsage :one
INSERT INTO whatsapp_usage_monthly (
    company_id, billing_period, messages_sent, messages_over_allowance
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (company_id, billing_period) DO UPDATE SET
    messages_sent = EXCLUDED.messages_sent,
    messages_over_allowance = EXCLUDED.messages_over_allowance
RETURNING id, company_id, billing_period, messages_sent, messages_over_allowance, stripe_usage_record_id, synced_at
`

type UpsertMonthlyUsageParams struct {
	CompanyID             pgtype.UUID `json:"company_id"`
	BillingPeriod         pgtype.Date `json:"billing_period"`
	MessagesSent          int32       `json:"messages_sent"`
	MessagesOverAllowance int32       `json:"messages_over_allowance"`
}

func (q *Queries) UpsertMonthlyUsage(ctx context.Context, arg UpsertMonthlyUsageParams) (WhatsappUsageMonthly, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyUsage,
		arg.CompanyID,
		arg.BillingPeriod,
		arg.MessagesSent,
		arg.MessagesOverAllowance,
	)
	var i WhatsappUsageMonthly
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BillingPeriod,
		&i.MessagesSent,
		&i.MessagesOverAllowance,
		&i.StripeUsageRecordID,
		&i.SyncedAt,
	)
	return i, err
}
