// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnnouncementType string

const (
	AnnouncementTypeInfo        AnnouncementType = "info"
	AnnouncementTypeWarning     AnnouncementType = "warning"
	AnnouncementTypeSuccess     AnnouncementType = "success"
	AnnouncementTypeMaintenance AnnouncementType = "maintenance"
)

func (e *AnnouncementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnnouncementType(s)
	case string:
		*e = AnnouncementType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnnouncementType: %T", src)
	}
	return nil
}

type NullAnnouncementType struct {
	AnnouncementType AnnouncementType `json:"announcement_type"`
	Valid            bool             `json:"valid"` // Valid is true if AnnouncementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnnouncementType) Scan(value interface{}) error {
	if value == nil {
		ns.AnnouncementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnnouncementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnnouncementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnnouncementType), nil
}

type UnitOfMeasure string

const (
	UnitOfMeasureUN UnitOfMeasure = "UN"
	UnitOfMeasureKG UnitOfMeasure = "KG"
	UnitOfMeasureG  UnitOfMeasure = "G"
	UnitOfMeasureL  UnitOfMeasure = "L"
	UnitOfMeasureML UnitOfMeasure = "ML"
)

func (e *UnitOfMeasure) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitOfMeasure(s)
	case string:
		*e = UnitOfMeasure(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitOfMeasure: %T", src)
	}
	return nil
}

type NullUnitOfMeasure struct {
	UnitOfMeasure UnitOfMeasure `json:"unit_of_measure"`
	Valid         bool          `json:"valid"` // Valid is true if UnitOfMeasure is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitOfMeasure) Scan(value interface{}) error {
	if value == nil {
		ns.UnitOfMeasure, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitOfMeasure.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitOfMeasure) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitOfMeasure), nil
}

type WhatsappMessageCategory string

const (
	WhatsappMessageCategoryMarketing      WhatsappMessageCategory = "marketing"
	WhatsappMessageCategoryUtility        WhatsappMessageCategory = "utility"
	WhatsappMessageCategoryAuthentication WhatsappMessageCategory = "authentication"
	WhatsappMessageCategoryService        WhatsappMessageCategory = "service"
)

func (e *WhatsappMessageCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappMessageCategory(s)
	case string:
		*e = WhatsappMessageCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappMessageCategory: %T", src)
	}
	return nil
}

type NullWhatsappMessageCategory struct {
	WhatsappMessageCategory WhatsappMessageCategory `json:"whatsapp_message_category"`
	Valid                   bool                    `json:"valid"` // Valid is true if WhatsappMessageCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappMessageCategory) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappMessageCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappMessageCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappMessageCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappMessageCategory), nil
}

type WhatsappMessageStatus string

const (
	WhatsappMessageStatusQueued    WhatsappMessageStatus = "queued"
	WhatsappMessageStatusSent      WhatsappMessageStatus = "sent"
	WhatsappMessageStatusDelivered WhatsappMessageStatus = "delivered"
	WhatsappMessageStatusRead      WhatsappMessageStatus = "read"
	WhatsappMessageStatusFailed    WhatsappMessageStatus = "failed"
)

func (e *WhatsappMessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappMessageStatus(s)
	case string:
		*e = WhatsappMessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappMessageStatus: %T", src)
	}
	return nil
}

type NullWhatsappMessageStatus struct {
	WhatsappMessageStatus WhatsappMessageStatus `json:"whatsapp_message_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if WhatsappMessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappMessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappMessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappMessageStatus), nil
}

type WhatsappMode string

const (
	WhatsappModePlatformShared WhatsappMode = "platform_shared"
	WhatsappModeOwnWaba        WhatsappMode = "own_waba"
)

func (e *WhatsappMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WhatsappMode(s)
	case string:
		*e = WhatsappMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WhatsappMode: %T", src)
	}
	return nil
}

type NullWhatsappMode struct {
	WhatsappMode WhatsappMode `json:"whatsapp_mode"`
	Valid        bool         `json:"valid"` // Valid is true if WhatsappMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWhatsappMode) Scan(value interface{}) error {
	if value == nil {
		ns.WhatsappMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WhatsappMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWhatsappMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WhatsappMode), nil
}

type AccountsReceivable struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	SaleID            pgtype.UUID        `json:"sale_id"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	Balance           pgtype.Numeric     `json:"balance"`
	DueDate           pgtype.Date        `json:"due_date"`
	InstallmentNumber pgtype.Int4        `json:"installment_number"`
	TotalInstallments pgtype.Int4        `json:"total_installments"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Announcement struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Type      AnnouncementType   `json:"type"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  bool               `json:"is_active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type BillCategory struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type BillsPayable struct {
	ID              pgtype.UUID        `json:"id"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	PaymentMethodID pgtype.UUID        `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	Status          interface{}        `json:"status"`
	Description     pgtype.Text        `json:"description"`
	ScheduledDate   pgtype.Date        `json:"scheduled_date"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	AmountPaid      pgtype.Numeric     `json:"amount_paid"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Company struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	TradeName               pgtype.Text        `json:"trade_name"`
	Document                pgtype.Text        `json:"document"`
	DocumentType            pgtype.Text        `json:"document_type"`
	Email                   pgtype.Text        `json:"email"`
	Phone                   pgtype.Text        `json:"phone"`
	Website                 pgtype.Text        `json:"website"`
	AddressStreet           pgtype.Text        `json:"address_street"`
	AddressNumber           pgtype.Text        `json:"address_number"`
	AddressComplement       pgtype.Text        `json:"address_complement"`
	AddressNeighborhood     pgtype.Text        `json:"address_neighborhood"`
	AddressCity             pgtype.Text        `json:"address_city"`
	AddressState            pgtype.Text        `json:"address_state"`
	AddressZipcode          pgtype.Text        `json:"address_zipcode"`
	AddressCountry          pgtype.Text        `json:"address_country"`
	Status                  interface{}        `json:"status"`
	Timezone                pgtype.Text        `json:"timezone"`
	CreatedBy               pgtype.UUID        `json:"created_by"`
	UpdatedBy               pgtype.UUID        `json:"updated_by"`
	DeletedBy               pgtype.UUID        `json:"deleted_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `json:"deleted_at"`
	InscricaoEstadual       pgtype.Text        `json:"inscricao_estadual"`
	InscricaoEstadualIsento bool               `json:"inscricao_estadual_isento"`
	Cnae                    pgtype.Text        `json:"cnae"`
	RegimeTributario        interface{}        `json:"regime_tributario"`
	ExternalCompanyID       string             `json:"external_company_id"`
	IsWhatsapp              bool               `json:"is_whatsapp"`
	IsExcessUsage           bool               `json:"is_excess_usage"`
}

type CompanyCertificate struct {
	ID                     pgtype.UUID        `json:"id"`
	CompanyID              pgtype.UUID        `json:"company_id"`
	EncryptedCertData      []byte             `json:"encrypted_cert_data"`
	EncryptedCertNonce     []byte             `json:"encrypted_cert_nonce"`
	EncryptedPassword      []byte             `json:"encrypted_password"`
	EncryptedPasswordNonce []byte             `json:"encrypted_password_nonce"`
	CertSubjectCn          pgtype.Text        `json:"cert_subject_cn"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	NuvemFiscalStatus      interface{}        `json:"nuvem_fiscal_status"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	DeletedBy              pgtype.UUID        `json:"deleted_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type CompanyWhatsappConfig struct {
	ID                      pgtype.UUID        `json:"id"`
	CompanyID               pgtype.UUID        `json:"company_id"`
	Mode                    WhatsappMode       `json:"mode"`
	WabaID                  pgtype.Text        `json:"waba_id"`
	PhoneNumberID           pgtype.Text        `json:"phone_number_id"`
	DisplayPhoneNumber      pgtype.Text        `json:"display_phone_number"`
	AccessTokenEncrypted    pgtype.Text        `json:"access_token_encrypted"`
	MonthlyMessageAllowance int32              `json:"monthly_message_allowance"`
	IsActive                bool               `json:"is_active"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID                  pgtype.UUID        `json:"id"`
	CompanyID           pgtype.UUID        `json:"company_id"`
	FullName            string             `json:"full_name"`
	BirthDate           pgtype.Date        `json:"birth_date"`
	Cpf                 string             `json:"cpf"`
	Rg                  pgtype.Text        `json:"rg"`
	MaritalStatus       pgtype.Text        `json:"marital_status"`
	Gender              interface{}        `json:"gender"`
	Whatsapp            pgtype.Text        `json:"whatsapp"`
	MobilePhone         pgtype.Text        `json:"mobile_phone"`
	HomePhone           pgtype.Text        `json:"home_phone"`
	Email               string             `json:"email"`
	AddressStreet       pgtype.Text        `json:"address_street"`
	AddressNumber       pgtype.Text        `json:"address_number"`
	AddressComplement   pgtype.Text        `json:"address_complement"`
	AddressNeighborhood pgtype.Text        `json:"address_neighborhood"`
	AddressCity         pgtype.Text        `json:"address_city"`
	AddressState        pgtype.Text        `json:"address_state"`
	AddressZipcode      pgtype.Text        `json:"address_zipcode"`
	AddressCountry      pgtype.Text        `json:"address_country"`
	BalanceDue          pgtype.Numeric     `json:"balance_due"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Department struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      interface{}        `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type FiscalInvoice struct {
	ID                   pgtype.UUID        `json:"id"`
	CompanyID            pgtype.UUID        `json:"company_id"`
	SaleID               pgtype.UUID        `json:"sale_id"`
	Type                 interface{}        `json:"type"`
	Status               interface{}        `json:"status"`
	NuvemFiscalID        pgtype.Text        `json:"nuvem_fiscal_id"`
	ChaveAcesso          pgtype.Text        `json:"chave_acesso"`
	Numero               pgtype.Text        `json:"numero"`
	Serie                pgtype.Text        `json:"serie"`
	ProtocoloAutorizacao pgtype.Text        `json:"protocolo_autorizacao"`
	XmlUrl               pgtype.Text        `json:"xml_url"`
	DanfeUrl             pgtype.Text        `json:"danfe_url"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	CancelledReason      pgtype.Text        `json:"cancelled_reason"`
	AuthorizedAt         pgtype.Timestamptz `json:"authorized_at"`
	CancelledAt          pgtype.Timestamptz `json:"cancelled_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	DeletedBy            pgtype.UUID        `json:"deleted_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type FiscalInvoiceEvent struct {
	ID              pgtype.UUID        `json:"id"`
	FiscalInvoiceID pgtype.UUID        `json:"fiscal_invoice_id"`
	EventType       interface{}        `json:"event_type"`
	Payload         []byte             `json:"payload"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InvoiceHistory struct {
	ID                pgtype.UUID        `json:"id"`
	SubscriptionID    pgtype.UUID        `json:"subscription_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	PaymentMethodID   pgtype.UUID        `json:"payment_method_id"`
	ExternalPaymentID string             `json:"external_payment_id"`
	AmountCents       int32              `json:"amount_cents"`
	Status            string             `json:"status"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PaymentHistory struct {
	ID              pgtype.UUID        `json:"id"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	SaleID          pgtype.UUID        `json:"sale_id"`
	PaymentMethodID pgtype.UUID        `json:"payment_method_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AmountPaid      pgtype.Numeric     `json:"amount_paid"`
	PaymentDate     pgtype.Timestamptz `json:"payment_date"`
	Notes           pgtype.Text        `json:"notes"`
}

type PaymentMethod struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Name      string             `json:"name"`
	Type      interface{}        `json:"type"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Plan struct {
	ID              pgtype.UUID        `json:"id"`
	ExternalID      string             `json:"external_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	PriceCents      int32              `json:"price_cents"`
	Currency        pgtype.Text        `json:"currency"`
	BillingCycle    string             `json:"billing_cycle"`
	Active          pgtype.Bool        `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Highlight       bool               `json:"highlight"`
	Icon            string             `json:"icon"`
	ExternalPriceID string             `json:"external_price_id"`
}

type PlanFeature struct {
	ID           pgtype.UUID        `json:"id"`
	PlanID       pgtype.UUID        `json:"plan_id"`
	Name         string             `json:"name"`
	IsEnabled    bool               `json:"is_enabled"`
	DisplayOrder int32              `json:"display_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	FeatureKey   string             `json:"feature_key"`
	LimitValue   pgtype.Int4        `json:"limit_value"`
}

type PlatformAdmin struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Status       interface{}        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Product struct {
	ID                    pgtype.UUID        `json:"id"`
	CompanyID             pgtype.UUID        `json:"company_id"`
	CategoryID            pgtype.UUID        `json:"category_id"`
	Name                  string             `json:"name"`
	Description           pgtype.Text        `json:"description"`
	Barcode               pgtype.Text        `json:"barcode"`
	Quantity              pgtype.Int4        `json:"quantity"`
	Size                  pgtype.Text        `json:"size"`
	CostPrice             pgtype.Numeric     `json:"cost_price"`
	SalePrice             pgtype.Numeric     `json:"sale_price"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	UpdatedBy             pgtype.UUID        `json:"updated_by"`
	DeletedBy             pgtype.UUID        `json:"deleted_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
	Unit                  UnitOfMeasure      `json:"unit"`
	SellInBulk            bool               `json:"sell_in_bulk"`
	Ncm                   pgtype.Text        `json:"ncm"`
	Cest                  pgtype.Text        `json:"cest"`
	Csosn                 pgtype.Text        `json:"csosn"`
	CfopSaidaDentroEstado pgtype.Text        `json:"cfop_saida_dentro_estado"`
	CfopSaidaForaEstado   pgtype.Text        `json:"cfop_saida_fora_estado"`
	OrigemMercadoria      int16              `json:"origem_mercadoria"`
}

type ProductCategory struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	Status    interface{}        `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Sale struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	SaleAt            pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	Subtotal          pgtype.Numeric     `json:"subtotal"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	DownPayment       pgtype.Numeric     `json:"down_payment"`
	InstallmentsCount int32              `json:"installments_count"`
	DueDays           pgtype.Int4        `json:"due_days"`
	PaymentMethod     interface{}        `json:"payment_method"`
	Status            interface{}        `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
	BuyerDocument     pgtype.Text        `json:"buyer_document"`
}

type SaleItem struct {
	ID        pgtype.UUID        `json:"id"`
	SaleID    pgtype.UUID        `json:"sale_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	UnitPrice pgtype.Numeric     `json:"unit_price"`
	Discount  pgtype.Numeric     `json:"discount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                     pgtype.UUID        `json:"id"`
	CompanyID              pgtype.UUID        `json:"company_id"`
	PlanID                 pgtype.UUID        `json:"plan_id"`
	PaymentMethodID        pgtype.UUID        `json:"payment_method_id"`
	ExternalSubscriptionID pgtype.Text        `json:"external_subscription_id"`
	Status                 string             `json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	CanceledAt             pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionPaymentMethod struct {
	ID                     pgtype.UUID        `json:"id"`
	CompanyID              pgtype.UUID        `json:"company_id"`
	GatewayPaymentMethodID string             `json:"gateway_payment_method_id"`
	Type                   string             `json:"type"`
	CardBrand              pgtype.Text        `json:"card_brand"`
	CardLast4              pgtype.Text        `json:"card_last4"`
	CardExpMonth           pgtype.Int4        `json:"card_exp_month"`
	CardExpYear            pgtype.Int4        `json:"card_exp_year"`
	IsDefault              pgtype.Bool        `json:"is_default"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	UpdatedBy              pgtype.UUID        `json:"updated_by"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Username     pgtype.Text        `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       interface{}        `json:"status"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Vendor struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	Name         string             `json:"name"`
	TaxID        pgtype.Text        `json:"tax_id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	PostalCode   pgtype.Text        `json:"postal_code"`
	AddressLine1 pgtype.Text        `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	Number       pgtype.Text        `json:"number"`
	Neighborhood pgtype.Text        `json:"neighborhood"`
	City         pgtype.Text        `json:"city"`
	State        pgtype.Text        `json:"state"`
	Country      pgtype.Text        `json:"country"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WhatsappMessage struct {
	ID                 pgtype.UUID             `json:"id"`
	CompanyID          pgtype.UUID             `json:"company_id"`
	TemplateID         pgtype.UUID             `json:"template_id"`
	Category           WhatsappMessageCategory `json:"category"`
	RecipientPhone     string                  `json:"recipient_phone"`
	MetaMessageID      pgtype.Text             `json:"meta_message_id"`
	Status             WhatsappMessageStatus   `json:"status"`
	FailureCode        pgtype.Int4             `json:"failure_code"`
	FailureReason      pgtype.Text             `json:"failure_reason"`
	EstimatedCostCents pgtype.Int4             `json:"estimated_cost_cents"`
	SentAt             pgtype.Timestamptz      `json:"sent_at"`
	DeliveredAt        pgtype.Timestamptz      `json:"delivered_at"`
	CreatedAt          pgtype.Timestamptz      `json:"created_at"`
}

type WhatsappTemplate struct {
	ID                       pgtype.UUID             `json:"id"`
	MetaTemplateName         string                  `json:"meta_template_name"`
	Category                 WhatsappMessageCategory `json:"category"`
	LanguageCode             string                  `json:"language_code"`
	BodyText                 string                  `json:"body_text"`
	Variables                []byte                  `json:"variables"`
	IsPlatformSharedEligible bool                    `json:"is_platform_shared_eligible"`
	MetaApprovalStatus       string                  `json:"meta_approval_status"`
	CreatedAt                pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz      `json:"updated_at"`
}

type WhatsappUsageMonthly struct {
	ID                    pgtype.UUID        `json:"id"`
	CompanyID             pgtype.UUID        `json:"company_id"`
	BillingPeriod         pgtype.Date        `json:"billing_period"`
	MessagesSent          int32              `json:"messages_sent"`
	MessagesOverAllowance int32              `json:"messages_over_allowance"`
	StripeUsageRecordID   pgtype.Text        `json:"stripe_usage_record_id"`
	SyncedAt              pgtype.Timestamptz `json:"synced_at"`
}
