// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountsReceivable struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	SaleID            pgtype.UUID        `json:"sale_id"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	Balance           pgtype.Numeric     `json:"balance"`
	DueDate           pgtype.Date        `json:"due_date"`
	InstallmentNumber pgtype.Int4        `json:"installment_number"`
	TotalInstallments pgtype.Int4        `json:"total_installments"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type BillCategory struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type BillsPayable struct {
	ID              pgtype.UUID        `json:"id"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	VendorID        pgtype.UUID        `json:"vendor_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	PaymentMethodID pgtype.UUID        `json:"payment_method_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	Status          interface{}        `json:"status"`
	Description     pgtype.Text        `json:"description"`
	ScheduledDate   pgtype.Date        `json:"scheduled_date"`
	PaymentDate     pgtype.Date        `json:"payment_date"`
	AmountPaid      pgtype.Numeric     `json:"amount_paid"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Company struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	TradeName           pgtype.Text        `json:"trade_name"`
	Document            pgtype.Text        `json:"document"`
	DocumentType        pgtype.Text        `json:"document_type"`
	Email               pgtype.Text        `json:"email"`
	Phone               pgtype.Text        `json:"phone"`
	Website             pgtype.Text        `json:"website"`
	AddressStreet       pgtype.Text        `json:"address_street"`
	AddressNumber       pgtype.Text        `json:"address_number"`
	AddressComplement   pgtype.Text        `json:"address_complement"`
	AddressNeighborhood pgtype.Text        `json:"address_neighborhood"`
	AddressCity         pgtype.Text        `json:"address_city"`
	AddressState        pgtype.Text        `json:"address_state"`
	AddressZipcode      pgtype.Text        `json:"address_zipcode"`
	AddressCountry      pgtype.Text        `json:"address_country"`
	Status              interface{}        `json:"status"`
	Timezone            pgtype.Text        `json:"timezone"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Customer struct {
	ID                  pgtype.UUID        `json:"id"`
	CompanyID           pgtype.UUID        `json:"company_id"`
	FullName            string             `json:"full_name"`
	BirthDate           pgtype.Date        `json:"birth_date"`
	Cpf                 string             `json:"cpf"`
	Rg                  pgtype.Text        `json:"rg"`
	MaritalStatus       pgtype.Text        `json:"marital_status"`
	Gender              interface{}        `json:"gender"`
	Whatsapp            pgtype.Text        `json:"whatsapp"`
	MobilePhone         pgtype.Text        `json:"mobile_phone"`
	HomePhone           pgtype.Text        `json:"home_phone"`
	Email               string             `json:"email"`
	AddressStreet       pgtype.Text        `json:"address_street"`
	AddressNumber       pgtype.Text        `json:"address_number"`
	AddressComplement   pgtype.Text        `json:"address_complement"`
	AddressNeighborhood pgtype.Text        `json:"address_neighborhood"`
	AddressCity         pgtype.Text        `json:"address_city"`
	AddressState        pgtype.Text        `json:"address_state"`
	AddressZipcode      pgtype.Text        `json:"address_zipcode"`
	AddressCountry      pgtype.Text        `json:"address_country"`
	BalanceDue          pgtype.Numeric     `json:"balance_due"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Department struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PaymentHistory struct {
	ID              pgtype.UUID        `json:"id"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	SaleID          pgtype.UUID        `json:"sale_id"`
	PaymentMethodID pgtype.UUID        `json:"payment_method_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	AmountPaid      pgtype.Numeric     `json:"amount_paid"`
	PaymentDate     pgtype.Timestamptz `json:"payment_date"`
	Notes           pgtype.Text        `json:"notes"`
}

type PaymentMethod struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Name      string             `json:"name"`
	Type      interface{}        `json:"type"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Barcode     pgtype.Text        `json:"barcode"`
	Quantity    int32              `json:"quantity"`
	Size        pgtype.Text        `json:"size"`
	CostPrice   pgtype.Numeric     `json:"cost_price"`
	SalePrice   pgtype.Numeric     `json:"sale_price"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProductCategory struct {
	ID        pgtype.UUID        `json:"id"`
	CompanyID pgtype.UUID        `json:"company_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	Status    interface{}        `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Sale struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	SaleAt            pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	Subtotal          pgtype.Numeric     `json:"subtotal"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	DownPayment       pgtype.Numeric     `json:"down_payment"`
	InstallmentsCount int32              `json:"installments_count"`
	DueDays           pgtype.Int4        `json:"due_days"`
	PaymentMethod     interface{}        `json:"payment_method"`
	Status            interface{}        `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
}

type SaleItem struct {
	ID        pgtype.UUID        `json:"id"`
	SaleID    pgtype.UUID        `json:"sale_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	UnitPrice pgtype.Numeric     `json:"unit_price"`
	Discount  pgtype.Numeric     `json:"discount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Username     pgtype.Text        `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       interface{}        `json:"status"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Vendor struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	Name         string             `json:"name"`
	TaxID        pgtype.Text        `json:"tax_id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	PostalCode   pgtype.Text        `json:"postal_code"`
	AddressLine1 pgtype.Text        `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	Number       pgtype.Text        `json:"number"`
	Neighborhood pgtype.Text        `json:"neighborhood"`
	City         pgtype.Text        `json:"city"`
	State        pgtype.Text        `json:"state"`
	Country      pgtype.Text        `json:"country"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
