// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentHistory = `-- name: CreatePaymentHistory :exec
INSERT INTO payment_history (
        company_id,
        customer_id,
        sale_id,
        payment_method_id,
        user_id,
        amount_paid,
        notes
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePaymentHistoryParams struct {
	CompanyID       pgtype.UUID    `json:"company_id"`
	CustomerID      pgtype.UUID    `json:"customer_id"`
	SaleID          pgtype.UUID    `json:"sale_id"`
	PaymentMethodID pgtype.UUID    `json:"payment_method_id"`
	UserID          pgtype.UUID    `json:"user_id"`
	AmountPaid      pgtype.Numeric `json:"amount_paid"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) CreatePaymentHistory(ctx context.Context, arg CreatePaymentHistoryParams) error {
	_, err := q.db.Exec(ctx, createPaymentHistory,
		arg.CompanyID,
		arg.CustomerID,
		arg.SaleID,
		arg.PaymentMethodID,
		arg.UserID,
		arg.AmountPaid,
		arg.Notes,
	)
	return err
}

const getPaymentsByCustomer = `-- name: GetPaymentsByCustomer :many
SELECT id, company_id, customer_id, sale_id, payment_method_id, user_id, amount_paid, payment_date, notes
FROM payment_history
WHERE company_id = $1
    AND customer_id = $2
ORDER BY payment_date DESC
`

type GetPaymentsByCustomerParams struct {
	CompanyID  pgtype.UUID `json:"company_id"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

func (q *Queries) GetPaymentsByCustomer(ctx context.Context, arg GetPaymentsByCustomerParams) ([]PaymentHistory, error) {
	rows, err := q.db.Query(ctx, getPaymentsByCustomer, arg.CompanyID, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentHistory{}
	for rows.Next() {
		var i PaymentHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SaleID,
			&i.PaymentMethodID,
			&i.UserID,
			&i.AmountPaid,
			&i.PaymentDate,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsBySale = `-- name: GetPaymentsBySale :many
SELECT id, company_id, customer_id, sale_id, payment_method_id, user_id, amount_paid, payment_date, notes
FROM payment_history
WHERE company_id = $1
    AND sale_id = $2
ORDER BY payment_date DESC
`

type GetPaymentsBySaleParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	SaleID    pgtype.UUID `json:"sale_id"`
}

func (q *Queries) GetPaymentsBySale(ctx context.Context, arg GetPaymentsBySaleParams) ([]PaymentHistory, error) {
	rows, err := q.db.Query(ctx, getPaymentsBySale, arg.CompanyID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentHistory{}
	for rows.Next() {
		var i PaymentHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CustomerID,
			&i.SaleID,
			&i.PaymentMethodID,
			&i.UserID,
			&i.AmountPaid,
			&i.PaymentDate,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsHistoryReport = `-- name: GetPaymentsHistoryReport :many
SELECT ph.id,
    ph.amount_paid,
    ph.payment_date,
    ph.notes,
    c.full_name as customer_name,
    u.name as user_name,
    pm.name as payment_method_name,
    ph.sale_id
FROM payment_history ph
    INNER JOIN customers c ON ph.customer_id = c.id
    INNER JOIN users u ON ph.user_id = u.id
    LEFT JOIN payment_methods pm ON ph.payment_method_id = pm.id
WHERE ph.company_id = $1
    AND ph.payment_date BETWEEN $2 AND $3
ORDER BY ph.payment_date DESC
`

type GetPaymentsHistoryReportParams struct {
	CompanyID     pgtype.UUID        `json:"company_id"`
	PaymentDate   pgtype.Timestamptz `json:"payment_date"`
	PaymentDate_2 pgtype.Timestamptz `json:"payment_date_2"`
}

type GetPaymentsHistoryReportRow struct {
	ID                pgtype.UUID        `json:"id"`
	AmountPaid        pgtype.Numeric     `json:"amount_paid"`
	PaymentDate       pgtype.Timestamptz `json:"payment_date"`
	Notes             pgtype.Text        `json:"notes"`
	CustomerName      string             `json:"customer_name"`
	UserName          string             `json:"user_name"`
	PaymentMethodName pgtype.Text        `json:"payment_method_name"`
	SaleID            pgtype.UUID        `json:"sale_id"`
}

func (q *Queries) GetPaymentsHistoryReport(ctx context.Context, arg GetPaymentsHistoryReportParams) ([]GetPaymentsHistoryReportRow, error) {
	rows, err := q.db.Query(ctx, getPaymentsHistoryReport, arg.CompanyID, arg.PaymentDate, arg.PaymentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentsHistoryReportRow{}
	for rows.Next() {
		var i GetPaymentsHistoryReportRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountPaid,
			&i.PaymentDate,
			&i.Notes,
			&i.CustomerName,
			&i.UserName,
			&i.PaymentMethodName,
			&i.SaleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalReceivedByPeriod = `-- name: GetTotalReceivedByPeriod :one
SELECT COALESCE(SUM(amount_paid), 0)::DECIMAL(12, 2) as total
FROM payment_history
WHERE company_id = $1
    AND payment_date BETWEEN $2 AND $3
`

type GetTotalReceivedByPeriodParams struct {
	CompanyID     pgtype.UUID        `json:"company_id"`
	PaymentDate   pgtype.Timestamptz `json:"payment_date"`
	PaymentDate_2 pgtype.Timestamptz `json:"payment_date_2"`
}

func (q *Queries) GetTotalReceivedByPeriod(ctx context.Context, arg GetTotalReceivedByPeriodParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalReceivedByPeriod, arg.CompanyID, arg.PaymentDate, arg.PaymentDate_2)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const listPaymentHistory = `-- name: ListPaymentHistory :many
SELECT ph.id,
    ph.amount_paid,
    ph.payment_date,
    ph.notes,
    c.full_name as customer_name,
    u.name as user_name,
    pm.name as payment_method_name,
    ph.sale_id
FROM payment_history ph
    INNER JOIN customers c ON ph.customer_id = c.id
    INNER JOIN users u ON ph.user_id = u.id
    LEFT JOIN payment_methods pm ON ph.payment_method_id = pm.id
WHERE ph.company_id = $1
ORDER BY ph.payment_date DESC
`

type ListPaymentHistoryRow struct {
	ID                pgtype.UUID        `json:"id"`
	AmountPaid        pgtype.Numeric     `json:"amount_paid"`
	PaymentDate       pgtype.Timestamptz `json:"payment_date"`
	Notes             pgtype.Text        `json:"notes"`
	CustomerName      string             `json:"customer_name"`
	UserName          string             `json:"user_name"`
	PaymentMethodName pgtype.Text        `json:"payment_method_name"`
	SaleID            pgtype.UUID        `json:"sale_id"`
}

func (q *Queries) ListPaymentHistory(ctx context.Context, companyID pgtype.UUID) ([]ListPaymentHistoryRow, error) {
	rows, err := q.db.Query(ctx, listPaymentHistory, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentHistoryRow{}
	for rows.Next() {
		var i ListPaymentHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountPaid,
			&i.PaymentDate,
			&i.Notes,
			&i.CustomerName,
			&i.UserName,
			&i.PaymentMethodName,
			&i.SaleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
