// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_methods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :exec
INSERT INTO payment_methods(
        company_id,
        name,
        type
    )
VALUES ($1, $2, $3)
`

type CreatePaymentMethodParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Name      string      `json:"name"`
	Type      interface{} `json:"type"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) error {
	_, err := q.db.Exec(ctx, createPaymentMethod, arg.CompanyID, arg.Name, arg.Type)
	return err
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one
SELECT id, company_id, name, type, is_active, created_at, updated_at
FROM payment_methods
WHERE id = $1
`

func (q *Queries) GetPaymentMethodByID(ctx context.Context, id pgtype.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByID, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Type,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentMethodsStats = `-- name: GetPaymentMethodsStats :many
SELECT payment_method,
    COUNT(*) as total_sales,
    SUM(total_amount)::NUMERIC(15, 2) as total_revenue
FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
GROUP BY payment_method
ORDER BY total_sales DESC
`

type GetPaymentMethodsStatsRow struct {
	PaymentMethod interface{}    `json:"payment_method"`
	TotalSales    int64          `json:"total_sales"`
	TotalRevenue  pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) GetPaymentMethodsStats(ctx context.Context, companyID pgtype.UUID) ([]GetPaymentMethodsStatsRow, error) {
	rows, err := q.db.Query(ctx, getPaymentMethodsStats, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentMethodsStatsRow{}
	for rows.Next() {
		var i GetPaymentMethodsStatsRow
		if err := rows.Scan(&i.PaymentMethod, &i.TotalSales, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethod = `-- name: ListPaymentMethod :many
SELECT id, company_id, name, type, is_active, created_at, updated_at
FROM payment_methods
WHERE company_id = $1
`

func (q *Queries) ListPaymentMethod(ctx context.Context, companyID pgtype.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethod, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Type,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethodIsActive = `-- name: ListPaymentMethodIsActive :many
SELECT id, company_id, name, type, is_active, created_at, updated_at
FROM payment_methods
WHERE company_id = $1
    AND is_active = TRUE
`

func (q *Queries) ListPaymentMethodIsActive(ctx context.Context, companyID pgtype.UUID) ([]PaymentMethod, error) {
	rows, err := q.db.Query(ctx, listPaymentMethodIsActive, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethod{}
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Type,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePaymentMethodActive = `-- name: TogglePaymentMethodActive :exec
UPDATE payment_methods
SET is_active = $2
WHERE id = $1
`

type TogglePaymentMethodActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) TogglePaymentMethodActive(ctx context.Context, arg TogglePaymentMethodActiveParams) error {
	_, err := q.db.Exec(ctx, togglePaymentMethodActive, arg.ID, arg.IsActive)
	return err
}
