// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    external_id,
    name,
    description,
    price_cents,
    currency,
    billing_cycle,
    active,
    highlight,
    icon,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
RETURNING id
`

type CreatePlanParams struct {
	ExternalID   string      `json:"external_id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PriceCents   int32       `json:"price_cents"`
	Currency     pgtype.Text `json:"currency"`
	BillingCycle string      `json:"billing_cycle"`
	Active       pgtype.Bool `json:"active"`
	Highlight    bool        `json:"highlight"`
	Icon         string      `json:"icon"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ExternalID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.BillingCycle,
		arg.Active,
		arg.Highlight,
		arg.Icon,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, external_id, name, description, price_cents, currency, billing_cycle, active, highlight, icon, created_at, updated_at
FROM plans
WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.BillingCycle,
		&i.Active,
		&i.Highlight,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, external_id, name, description, price_cents, currency, billing_cycle, active, highlight, icon, created_at, updated_at
FROM plans
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.BillingCycle,
			&i.Active,
			&i.Highlight,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByActiveStatus = `-- name: ListPlansByActiveStatus :many
SELECT id, external_id, name, description, price_cents, currency, billing_cycle, active, highlight, icon, created_at, updated_at
FROM plans
WHERE active = $1
`

func (q *Queries) ListPlansByActiveStatus(ctx context.Context, active pgtype.Bool) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByActiveStatus, active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.BillingCycle,
			&i.Active,
			&i.Highlight,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePlanActiveStatus = `-- name: TogglePlanActiveStatus :exec
UPDATE plans SET active = $2, updated_at = NOW()
WHERE id = $1
`

type TogglePlanActiveStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Active pgtype.Bool `json:"active"`
}

func (q *Queries) TogglePlanActiveStatus(ctx context.Context, arg TogglePlanActiveStatusParams) error {
	_, err := q.db.Exec(ctx, togglePlanActiveStatus, arg.ID, arg.Active)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans SET name = $2, description = $3, price_cents = $4, currency = $5, billing_cycle = $6, highlight=$7, icon=$8 ,updated_at = NOW()
WHERE id = $1
`

type UpdatePlanParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	PriceCents   int32       `json:"price_cents"`
	Currency     pgtype.Text `json:"currency"`
	BillingCycle string      `json:"billing_cycle"`
	Highlight    bool        `json:"highlight"`
	Icon         string      `json:"icon"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.Exec(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.BillingCycle,
		arg.Highlight,
		arg.Icon,
	)
	return err
}
