// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_admins.sql

package db

import (
	"context"
)

const getPlatformAdminByEmail = `-- name: GetPlatformAdminByEmail :one
SELECT id, name, email, password_hash, status, created_at, updated_at, deleted_at
FROM platform_admins
WHERE email = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByEmail, email)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
