// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO product_categories(
        company_id,
        name,
        color,
        created_by
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, company_id, name, color, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateProductCategoryParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createProductCategory,
		arg.CompanyID,
		arg.Name,
		arg.Color,
		arg.CreatedBy,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProductCategory = `-- name: DeleteProductCategory :exec
UPDATE product_categories
SET deleted_by = $2,
    deleted_at = NOW()
WHERE id = $1
`

type DeleteProductCategoryParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteProductCategory(ctx context.Context, arg DeleteProductCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteProductCategory, arg.ID, arg.DeletedBy)
	return err
}

const getProductCategoryById = `-- name: GetProductCategoryById :one
SELECT id, company_id, name, color, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM product_categories
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetProductCategoryById(ctx context.Context, id pgtype.UUID) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getProductCategoryById, id)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProductCategoryByCompanyId = `-- name: ListProductCategoryByCompanyId :many
SELECT id, company_id, name, color, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM product_categories
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) ListProductCategoryByCompanyId(ctx context.Context, companyID pgtype.UUID) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listProductCategoryByCompanyId, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductCategory{}
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Color,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductCategoryStatus = `-- name: SetProductCategoryStatus :execrows
UPDATE product_categories
SET status = $2::status_enum
WHERE id = $1
`

type SetProductCategoryStatusParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) SetProductCategoryStatus(ctx context.Context, arg SetProductCategoryStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductCategoryStatus, arg.ID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProductCategory = `-- name: UpdateProductCategory :one
UPDATE product_categories
SET name = $2,
    color = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, name, color, status, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateProductCategoryParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateProductCategory(ctx context.Context, arg UpdateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, updateProductCategory,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.UpdatedBy,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Color,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
