// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLowStockProductsByCompany = `-- name: CountLowStockProductsByCompany :one
SELECT COUNT(*) AS low_stock_count
FROM products
WHERE company_id = $1
  AND quantity < 5
  AND deleted_at IS NULL
`

func (q *Queries) CountLowStockProductsByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLowStockProductsByCompany, companyID)
	var low_stock_count int64
	err := row.Scan(&low_stock_count)
	return low_stock_count, err
}

const countProducts = `-- name: CountProducts :one
SELECT SUM(quantity)
FROM products
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountProducts(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, companyID)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const countProductsByCompany = `-- name: CountProductsByCompany :one
SELECT COUNT(*) FROM products
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountProductsByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products(
        company_id,
        name,
        description,
        category_id,
        barcode,
        quantity,
        size,
        cost_price,
        sale_price,
        created_by
    )
VALUES(
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    )
RETURNING id, company_id, category_id, name, description, barcode, quantity, size, cost_price, sale_price, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CompanyID   pgtype.UUID    `json:"company_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Barcode     pgtype.Text    `json:"barcode"`
	Quantity    int32          `json:"quantity"`
	Size        pgtype.Text    `json:"size"`
	CostPrice   pgtype.Numeric `json:"cost_price"`
	SalePrice   pgtype.Numeric `json:"sale_price"`
	CreatedBy   pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.Barcode,
		arg.Quantity,
		arg.Size,
		arg.CostPrice,
		arg.SalePrice,
		arg.CreatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Barcode,
		&i.Quantity,
		&i.Size,
		&i.CostPrice,
		&i.SalePrice,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementStock = `-- name: DecrementStock :exec
UPDATE products
SET quantity = quantity - $1
WHERE id = $2
    AND quantity >= $1
`

type DecrementStockParams struct {
	Quantity int32       `json:"quantity"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) error {
	_, err := q.db.Exec(ctx, decrementStock, arg.Quantity, arg.ID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET deleted_by = $2,
    deleted_at = NOW()
WHERE id = $1
`

type DeleteProductParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.DeletedBy)
	return err
}

const getCostTotalStock = `-- name: GetCostTotalStock :one
SELECT COALESCE(SUM(cost_price * quantity), 0)::FLOAT AS total_stock_value
FROM products
WHERE company_id = $1
    AND deleted_at IS NULL
    AND quantity > 0
`

func (q *Queries) GetCostTotalStock(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getCostTotalStock, companyID)
	var total_stock_value float64
	err := row.Scan(&total_stock_value)
	return total_stock_value, err
}

const getGeneralTotalStockValue = `-- name: GetGeneralTotalStockValue :one
SELECT 
    COALESCE(SUM(quantity * cost_price), 0.0)::DOUBLE PRECISION AS total_cost_value
FROM products
WHERE company_id = $1 
    AND deleted_at IS NULL
`

func (q *Queries) GetGeneralTotalStockValue(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getGeneralTotalStockValue, companyID)
	var total_cost_value float64
	err := row.Scan(&total_cost_value)
	return total_cost_value, err
}

const getGlobalTotalStockQuantity = `-- name: GetGlobalTotalStockQuantity :one
SELECT COALESCE(SUM(quantity), 0)::INT AS total_items
FROM products
WHERE company_id = $1 
    AND deleted_at IS NULL
`

func (q *Queries) GetGlobalTotalStockQuantity(ctx context.Context, companyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getGlobalTotalStockQuantity, companyID)
	var total_items int32
	err := row.Scan(&total_items)
	return total_items, err
}

const getInventoryReport = `-- name: GetInventoryReport :many
SELECT p.name,
    c.name AS category_name,
    p.quantity,
    p.sale_price,
    (p.quantity * p.sale_price)::NUMERIC(10, 2) AS total_value,
    p.cost_price,
    p.barcode,
    p.created_at
FROM products p
    LEFT JOIN product_categories c ON p.category_id = c.id
WHERE p.company_id = $1
    AND p.created_at BETWEEN $2 AND $3
    AND p.deleted_at IS NULL
ORDER BY p.name ASC
`

type GetInventoryReportParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetInventoryReportRow struct {
	Name         string             `json:"name"`
	CategoryName pgtype.Text        `json:"category_name"`
	Quantity     int32              `json:"quantity"`
	SalePrice    pgtype.Numeric     `json:"sale_price"`
	TotalValue   pgtype.Numeric     `json:"total_value"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Barcode      pgtype.Text        `json:"barcode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetInventoryReport(ctx context.Context, arg GetInventoryReportParams) ([]GetInventoryReportRow, error) {
	rows, err := q.db.Query(ctx, getInventoryReport, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInventoryReportRow{}
	for rows.Next() {
		var i GetInventoryReportRow
		if err := rows.Scan(
			&i.Name,
			&i.CategoryName,
			&i.Quantity,
			&i.SalePrice,
			&i.TotalValue,
			&i.CostPrice,
			&i.Barcode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT id, company_id, category_id, name, description, barcode, quantity, size, cost_price, sale_price, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM products
WHERE barcode = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetProductByBarcode(ctx context.Context, barcode pgtype.Text) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, barcode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Barcode,
		&i.Quantity,
		&i.Size,
		&i.CostPrice,
		&i.SalePrice,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT id, company_id, category_id, name, description, barcode, quantity, size, cost_price, sale_price, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM products
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetProductById(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Barcode,
		&i.Quantity,
		&i.Size,
		&i.CostPrice,
		&i.SalePrice,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductsPerformanceSummary = `-- name: GetProductsPerformanceSummary :one
SELECT COALESCE(
        SUM(quantity) FILTER (
            WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
        ),
        0
    )::FLOAT AS current_month_qty,
    COALESCE(
        SUM(quantity) FILTER (
            WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
        ),
        0
    )::FLOAT AS last_month_qty
FROM products
WHERE company_id = $1
    AND deleted_at IS NULL
    AND created_at >= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
`

type GetProductsPerformanceSummaryRow struct {
	CurrentMonthQty float64 `json:"current_month_qty"`
	LastMonthQty    float64 `json:"last_month_qty"`
}

func (q *Queries) GetProductsPerformanceSummary(ctx context.Context, companyID pgtype.UUID) (GetProductsPerformanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProductsPerformanceSummary, companyID)
	var i GetProductsPerformanceSummaryRow
	err := row.Scan(&i.CurrentMonthQty, &i.LastMonthQty)
	return i, err
}

const getTop5BestSellingProducts = `-- name: GetTop5BestSellingProducts :many
SELECT p.id,
    p.name,
    COALESCE(SUM(si.quantity), 0)::INTEGER AS total_quantity_sold
FROM products p
    INNER JOIN sale_items si ON si.product_id = p.id
    INNER JOIN sales s ON s.id = si.sale_id
WHERE s.company_id = $1
    AND s.deleted_at IS NULL
GROUP BY p.id,
    p.name
ORDER BY total_quantity_sold DESC
LIMIT 5
`

type GetTop5BestSellingProductsRow struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	TotalQuantitySold int32       `json:"total_quantity_sold"`
}

func (q *Queries) GetTop5BestSellingProducts(ctx context.Context, companyID pgtype.UUID) ([]GetTop5BestSellingProductsRow, error) {
	rows, err := q.db.Query(ctx, getTop5BestSellingProducts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTop5BestSellingProductsRow{}
	for rows.Next() {
		var i GetTop5BestSellingProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalQuantitySold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategoryAndDate = `-- name: ListProductsByCategoryAndDate :many
SELECT p.id,
    p.name,
    p.cost_price,
    p.quantity,
    p.category_id,
    p.created_at,
    c.name AS category_name
FROM products p
    INNER JOIN product_categories c ON p.category_id = c.id
WHERE p.category_id = $1
    AND p.deleted_at IS NULL
    AND p.created_at >= $2
    AND p.created_at <= $3
`

type ListProductsByCategoryAndDateParams struct {
	CategoryID  pgtype.UUID        `json:"category_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type ListProductsByCategoryAndDateRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Quantity     int32              `json:"quantity"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) ListProductsByCategoryAndDate(ctx context.Context, arg ListProductsByCategoryAndDateParams) ([]ListProductsByCategoryAndDateRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCategoryAndDate, arg.CategoryID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCategoryAndDateRow{}
	for rows.Next() {
		var i ListProductsByCategoryAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CostPrice,
			&i.Quantity,
			&i.CategoryID,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategoryId = `-- name: ListProductsByCategoryId :many
SELECT id, company_id, category_id, name, description, barcode, quantity, size, cost_price, sale_price, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM products
WHERE category_id = $1
    AND company_id = $2
    AND deleted_at IS NULL
`

type ListProductsByCategoryIdParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	CompanyID  pgtype.UUID `json:"company_id"`
}

func (q *Queries) ListProductsByCategoryId(ctx context.Context, arg ListProductsByCategoryIdParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategoryId, arg.CategoryID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Barcode,
			&i.Quantity,
			&i.Size,
			&i.CostPrice,
			&i.SalePrice,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCompany = `-- name: ListProductsByCompany :many
SELECT p.id, p.company_id, p.category_id, p.name, p.description, p.barcode, p.quantity, p.size, p.cost_price, p.sale_price, p.created_by, p.updated_by, p.deleted_by, p.created_at, p.updated_at, p.deleted_at,
    c.name AS category_name
FROM products p
    INNER JOIN product_categories c ON p.category_id = c.id
WHERE p.company_id = $1
    AND p.deleted_at IS NULL
`

type ListProductsByCompanyRow struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Barcode      pgtype.Text        `json:"barcode"`
	Quantity     int32              `json:"quantity"`
	Size         pgtype.Text        `json:"size"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	SalePrice    pgtype.Numeric     `json:"sale_price"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) ListProductsByCompany(ctx context.Context, companyID pgtype.UUID) ([]ListProductsByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCompanyRow{}
	for rows.Next() {
		var i ListProductsByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Barcode,
			&i.Quantity,
			&i.Size,
			&i.CostPrice,
			&i.SalePrice,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCompanyPaginated = `-- name: ListProductsByCompanyPaginated :many
SELECT 
    p.id, p.company_id, p.category_id, p.name, p.description, p.barcode,
    p.quantity, p.size, p.cost_price, p.sale_price,
    p.created_by, p.updated_by, p.deleted_by,
    p.created_at, p.updated_at, p.deleted_at,
    c.name AS category_name
FROM products p
JOIN product_categories c ON c.id = p.category_id
WHERE p.company_id = $1
    AND p.deleted_at IS NULL
ORDER BY p.created_at DESC
LIMIT $2
OFFSET $3
`

type ListProductsByCompanyPaginatedParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListProductsByCompanyPaginatedRow struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	Barcode      pgtype.Text        `json:"barcode"`
	Quantity     int32              `json:"quantity"`
	Size         pgtype.Text        `json:"size"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	SalePrice    pgtype.Numeric     `json:"sale_price"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) ListProductsByCompanyPaginated(ctx context.Context, arg ListProductsByCompanyPaginatedParams) ([]ListProductsByCompanyPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCompanyPaginated, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByCompanyPaginatedRow{}
	for rows.Next() {
		var i ListProductsByCompanyPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Barcode,
			&i.Quantity,
			&i.Size,
			&i.CostPrice,
			&i.SalePrice,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByDate = `-- name: ListProductsByDate :many
SELECT p.id,
    p.name,
    p.cost_price,
    p.quantity,
    p.category_id,
    p.created_at,
    c.name AS category_name
FROM products p
    INNER JOIN product_categories c ON p.category_id = c.id
WHERE p.company_id = $1
    AND p.deleted_at IS NULL
    AND p.created_at >= $2
    AND p.created_at <= $3
`

type ListProductsByDateParams struct {
	CompanyID   pgtype.UUID        `json:"company_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type ListProductsByDateRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CostPrice    pgtype.Numeric     `json:"cost_price"`
	Quantity     int32              `json:"quantity"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CategoryName string             `json:"category_name"`
}

func (q *Queries) ListProductsByDate(ctx context.Context, arg ListProductsByDateParams) ([]ListProductsByDateRow, error) {
	rows, err := q.db.Query(ctx, listProductsByDate, arg.CompanyID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsByDateRow{}
	for rows.Next() {
		var i ListProductsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CostPrice,
			&i.Quantity,
			&i.CategoryID,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2,
    description = $3,
    category_id = $4,
    barcode = $5,
    quantity = $6,
    size = $7,
    cost_price = $8,
    sale_price = $9,
    updated_by = $10,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, company_id, category_id, name, description, barcode, quantity, size, cost_price, sale_price, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Barcode     pgtype.Text    `json:"barcode"`
	Quantity    int32          `json:"quantity"`
	Size        pgtype.Text    `json:"size"`
	CostPrice   pgtype.Numeric `json:"cost_price"`
	SalePrice   pgtype.Numeric `json:"sale_price"`
	UpdatedBy   pgtype.UUID    `json:"updated_by"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CategoryID,
		arg.Barcode,
		arg.Quantity,
		arg.Size,
		arg.CostPrice,
		arg.SalePrice,
		arg.UpdatedBy,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Barcode,
		&i.Quantity,
		&i.Size,
		&i.CostPrice,
		&i.SalePrice,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
