// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contSalesPendingAndOverdue = `-- name: ContSalesPendingAndOverdue :one
SELECT COUNT(*)
FROM sales
WHERE company_id = $1
    AND status IN ('pending', 'overdue')
    AND deleted_at IS NULL
`

func (q *Queries) ContSalesPendingAndOverdue(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contSalesPendingAndOverdue, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSales = `-- name: CountSales :one
SELECT COUNT(*)
FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountSales(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSales, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSalesByCompany = `-- name: CountSalesByCompany :one
SELECT COUNT(*) FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountSalesByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSalesDeletedByCompany = `-- name: CountSalesDeletedByCompany :one
SELECT COUNT(*) FROM sales
WHERE company_id = $1
    AND deleted_at IS NOT NULL
`

func (q *Queries) CountSalesDeletedByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesDeletedByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
        customer_id,
        company_id,
        sale_at,
        discount_amount,
        subtotal,
        total_amount,
        installments_count,
        down_payment,
        due_days,
        payment_method,
        created_by,
        status,
        buyer_document
    )
VALUES (
        $1,
        $2,
        CURRENT_DATE,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
RETURNING id
`

type CreateSaleParams struct {
	CustomerID        pgtype.UUID    `json:"customer_id"`
	CompanyID         pgtype.UUID    `json:"company_id"`
	DiscountAmount    pgtype.Numeric `json:"discount_amount"`
	Subtotal          pgtype.Numeric `json:"subtotal"`
	TotalAmount       pgtype.Numeric `json:"total_amount"`
	InstallmentsCount int32          `json:"installments_count"`
	DownPayment       pgtype.Numeric `json:"down_payment"`
	DueDays           pgtype.Int4    `json:"due_days"`
	PaymentMethod     interface{}    `json:"payment_method"`
	CreatedBy         pgtype.UUID    `json:"created_by"`
	Status            interface{}    `json:"status"`
	BuyerDocument     pgtype.Text    `json:"buyer_document"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.CustomerID,
		arg.CompanyID,
		arg.DiscountAmount,
		arg.Subtotal,
		arg.TotalAmount,
		arg.InstallmentsCount,
		arg.DownPayment,
		arg.DueDays,
		arg.PaymentMethod,
		arg.CreatedBy,
		arg.Status,
		arg.BuyerDocument,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSale = `-- name: DeleteSale :exec
UPDATE sales
SET deleted_at = CURRENT_TIMESTAMP,
    deleted_by = $1
WHERE id = $2
    AND company_id = $3
`

type DeleteSaleParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) DeleteSale(ctx context.Context, arg DeleteSaleParams) error {
	_, err := q.db.Exec(ctx, deleteSale, arg.DeletedBy, arg.ID, arg.CompanyID)
	return err
}

const getPendingSalesDetailedReport = `-- name: GetPendingSalesDetailedReport :many
SELECT -- Dados da venda
    s.id AS sale_id,
    s.sale_at,
    s.subtotal,
    s.discount_amount,
    s.total_amount,
    s.installments_count,
    s.payment_method,
    s.status AS sale_status,
    -- Dados do cliente
    c.id AS customer_id,
    COALESCE(c.full_name, '') AS customer_name,
    -- Dados dos produtos (itens da venda)
    si.id AS sale_item_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount AS item_discount,
    p.name AS product_name,
    -- Parcelas (accounts_receivable)
    ar.id AS installment_id,
    ar.total_amount AS installment_total_amount,
    ar.balance AS installment_balance,
    ar.due_date,
    ar.installment_number,
    ar.status AS installment_status
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
    INNER JOIN sale_items si ON s.id = si.sale_id
    INNER JOIN products p ON si.product_id = p.id
    LEFT JOIN accounts_receivable ar ON s.id = ar.sale_id
WHERE s.company_id = $1
    AND s.deleted_at IS NULL
    AND s.status IN ('pending', 'overdue') -- Filtro de intervalo de datas (Inclusivo)
    AND s.sale_at BETWEEN $2 AND $3
ORDER BY s.sale_at DESC,
    si.id,
    ar.installment_number
`

type GetPendingSalesDetailedReportParams struct {
	CompanyID pgtype.UUID        `json:"company_id"`
	SaleAt    pgtype.Timestamptz `json:"sale_at"`
	SaleAt_2  pgtype.Timestamptz `json:"sale_at_2"`
}

type GetPendingSalesDetailedReportRow struct {
	SaleID                 pgtype.UUID        `json:"sale_id"`
	SaleAt                 pgtype.Timestamptz `json:"sale_at"`
	Subtotal               pgtype.Numeric     `json:"subtotal"`
	DiscountAmount         pgtype.Numeric     `json:"discount_amount"`
	TotalAmount            pgtype.Numeric     `json:"total_amount"`
	InstallmentsCount      int32              `json:"installments_count"`
	PaymentMethod          interface{}        `json:"payment_method"`
	SaleStatus             interface{}        `json:"sale_status"`
	CustomerID             pgtype.UUID        `json:"customer_id"`
	CustomerName           string             `json:"customer_name"`
	SaleItemID             pgtype.UUID        `json:"sale_item_id"`
	ProductID              pgtype.UUID        `json:"product_id"`
	Quantity               int32              `json:"quantity"`
	UnitPrice              pgtype.Numeric     `json:"unit_price"`
	ItemDiscount           pgtype.Numeric     `json:"item_discount"`
	ProductName            string             `json:"product_name"`
	InstallmentID          pgtype.UUID        `json:"installment_id"`
	InstallmentTotalAmount pgtype.Numeric     `json:"installment_total_amount"`
	InstallmentBalance     pgtype.Numeric     `json:"installment_balance"`
	DueDate                pgtype.Date        `json:"due_date"`
	InstallmentNumber      pgtype.Int4        `json:"installment_number"`
	InstallmentStatus      pgtype.Text        `json:"installment_status"`
}

func (q *Queries) GetPendingSalesDetailedReport(ctx context.Context, arg GetPendingSalesDetailedReportParams) ([]GetPendingSalesDetailedReportRow, error) {
	rows, err := q.db.Query(ctx, getPendingSalesDetailedReport, arg.CompanyID, arg.SaleAt, arg.SaleAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingSalesDetailedReportRow{}
	for rows.Next() {
		var i GetPendingSalesDetailedReportRow
		if err := rows.Scan(
			&i.SaleID,
			&i.SaleAt,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.InstallmentsCount,
			&i.PaymentMethod,
			&i.SaleStatus,
			&i.CustomerID,
			&i.CustomerName,
			&i.SaleItemID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.ItemDiscount,
			&i.ProductName,
			&i.InstallmentID,
			&i.InstallmentTotalAmount,
			&i.InstallmentBalance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.InstallmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSaleById = `-- name: GetSaleById :one
SELECT s.id, s.customer_id, s.company_id, s.sale_at, s.discount_amount, s.subtotal, s.total_amount, s.down_payment, s.installments_count, s.due_days, s.payment_method, s.status, s.created_at, s.created_by, s.updated_at, s.updated_by, s.deleted_at, s.deleted_by, s.buyer_document,
    COALESCE(c.full_name, '') as customer_name
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1
    AND s.company_id = $2
`

type GetSaleByIdParams struct {
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

type GetSaleByIdRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	SaleAt            pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	Subtotal          pgtype.Numeric     `json:"subtotal"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	DownPayment       pgtype.Numeric     `json:"down_payment"`
	InstallmentsCount int32              `json:"installments_count"`
	DueDays           pgtype.Int4        `json:"due_days"`
	PaymentMethod     interface{}        `json:"payment_method"`
	Status            interface{}        `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
	BuyerDocument     pgtype.Text        `json:"buyer_document"`
	CustomerName      string             `json:"customer_name"`
}

func (q *Queries) GetSaleById(ctx context.Context, arg GetSaleByIdParams) (GetSaleByIdRow, error) {
	row := q.db.QueryRow(ctx, getSaleById, arg.ID, arg.CompanyID)
	var i GetSaleByIdRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.SaleAt,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.TotalAmount,
		&i.DownPayment,
		&i.InstallmentsCount,
		&i.DueDays,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.BuyerDocument,
		&i.CustomerName,
	)
	return i, err
}

const getSaleByIdJust = `-- name: GetSaleByIdJust :one
SELECT s.id, s.customer_id, s.company_id, s.sale_at, s.discount_amount, s.subtotal, s.total_amount, s.down_payment, s.installments_count, s.due_days, s.payment_method, s.status, s.created_at, s.created_by, s.updated_at, s.updated_by, s.deleted_at, s.deleted_by, s.buyer_document,
    COALESCE(c.full_name, '') as customer_name
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1
`

type GetSaleByIdJustRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	SaleAt            pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	Subtotal          pgtype.Numeric     `json:"subtotal"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	DownPayment       pgtype.Numeric     `json:"down_payment"`
	InstallmentsCount int32              `json:"installments_count"`
	DueDays           pgtype.Int4        `json:"due_days"`
	PaymentMethod     interface{}        `json:"payment_method"`
	Status            interface{}        `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
	BuyerDocument     pgtype.Text        `json:"buyer_document"`
	CustomerName      string             `json:"customer_name"`
}

func (q *Queries) GetSaleByIdJust(ctx context.Context, id pgtype.UUID) (GetSaleByIdJustRow, error) {
	row := q.db.QueryRow(ctx, getSaleByIdJust, id)
	var i GetSaleByIdJustRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.SaleAt,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.TotalAmount,
		&i.DownPayment,
		&i.InstallmentsCount,
		&i.DueDays,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.BuyerDocument,
		&i.CustomerName,
	)
	return i, err
}

const getSaleByIdWhatsapp = `-- name: GetSaleByIdWhatsapp :one
SELECT s.id, s.customer_id, s.company_id, s.sale_at, s.discount_amount, s.subtotal, s.total_amount, s.down_payment, s.installments_count, s.due_days, s.payment_method, s.status, s.created_at, s.created_by, s.updated_at, s.updated_by, s.deleted_at, s.deleted_by, s.buyer_document,
    COALESCE(c.full_name, '') as customer_name,
    COALESCE(c.whatsapp, '') as customer_whatsApp
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1
`

type GetSaleByIdWhatsappRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	SaleAt            pgtype.Timestamptz `json:"sale_at"`
	DiscountAmount    pgtype.Numeric     `json:"discount_amount"`
	Subtotal          pgtype.Numeric     `json:"subtotal"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	DownPayment       pgtype.Numeric     `json:"down_payment"`
	InstallmentsCount int32              `json:"installments_count"`
	DueDays           pgtype.Int4        `json:"due_days"`
	PaymentMethod     interface{}        `json:"payment_method"`
	Status            interface{}        `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
	BuyerDocument     pgtype.Text        `json:"buyer_document"`
	CustomerName      string             `json:"customer_name"`
	CustomerWhatsapp  string             `json:"customer_whatsapp"`
}

func (q *Queries) GetSaleByIdWhatsapp(ctx context.Context, id pgtype.UUID) (GetSaleByIdWhatsappRow, error) {
	row := q.db.QueryRow(ctx, getSaleByIdWhatsapp, id)
	var i GetSaleByIdWhatsappRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CompanyID,
		&i.SaleAt,
		&i.DiscountAmount,
		&i.Subtotal,
		&i.TotalAmount,
		&i.DownPayment,
		&i.InstallmentsCount,
		&i.DueDays,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.BuyerDocument,
		&i.CustomerName,
		&i.CustomerWhatsapp,
	)
	return i, err
}

const getSalesPerformanceSummary = `-- name: GetSalesPerformanceSummary :one
SELECT COUNT(*) FILTER (
        WHERE date_trunc('month', sale_at) = date_trunc('month', CURRENT_DATE)
    ) AS current_month_count,
    COUNT(*) FILTER (
        WHERE date_trunc('month', sale_at) = date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
    ) AS last_month_count
FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
    AND sale_at >= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
`

type GetSalesPerformanceSummaryRow struct {
	CurrentMonthCount int64 `json:"current_month_count"`
	LastMonthCount    int64 `json:"last_month_count"`
}

func (q *Queries) GetSalesPerformanceSummary(ctx context.Context, companyID pgtype.UUID) (GetSalesPerformanceSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSalesPerformanceSummary, companyID)
	var i GetSalesPerformanceSummaryRow
	err := row.Scan(&i.CurrentMonthCount, &i.LastMonthCount)
	return i, err
}

const getTotalAmountByStatus = `-- name: GetTotalAmountByStatus :one
SELECT COALESCE(
        SUM(total_amount) FILTER (
            WHERE status = $2
                AND company_id = $1
                AND deleted_at IS NULL
        ),
        0
    )::FLOAT AS total_pending_amount
from sales
`

type GetTotalAmountByStatusParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Status    interface{} `json:"status"`
}

func (q *Queries) GetTotalAmountByStatus(ctx context.Context, arg GetTotalAmountByStatusParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalAmountByStatus, arg.CompanyID, arg.Status)
	var total_pending_amount float64
	err := row.Scan(&total_pending_amount)
	return total_pending_amount, err
}

const getTotalAmountIsPending = `-- name: GetTotalAmountIsPending :one
SELECT COALESCE(SUM(balance), 0)::numeric AS total_balance
FROM accounts_receivable
WHERE status IN ('pending', 'overdue', 'partial')
  AND company_id = $1
`

func (q *Queries) GetTotalAmountIsPending(ctx context.Context, companyID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalAmountIsPending, companyID)
	var total_balance pgtype.Numeric
	err := row.Scan(&total_balance)
	return total_balance, err
}

const getTotalAmountPaid = `-- name: GetTotalAmountPaid :one
SELECT COALESCE(
        SUM(total_amount) FILTER (
            WHERE status = 'paid'
                AND company_id = $1
                AND deleted_at IS NULL
        ),
        0
    )::FLOAT AS total_pending_amount
from sales
`

func (q *Queries) GetTotalAmountPaid(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalAmountPaid, companyID)
	var total_pending_amount float64
	err := row.Scan(&total_pending_amount)
	return total_pending_amount, err
}

const getTotalAmountPending = `-- name: GetTotalAmountPending :one
SELECT COALESCE(
        SUM(total_amount) FILTER (
            WHERE status = 'pending' OR status = 'overdue'
                AND company_id = $1
                AND deleted_at IS NULL
        ),
        0
    )::FLOAT AS total_pending_amount
from sales
`

func (q *Queries) GetTotalAmountPending(ctx context.Context, companyID pgtype.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalAmountPending, companyID)
	var total_pending_amount float64
	err := row.Scan(&total_pending_amount)
	return total_pending_amount, err
}

const getTotalAmountSummary = `-- name: GetTotalAmountSummary :one
SELECT coalesce(
        SUM(total_amount) FILTER (
            WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
        ),
        0
    )::FLOAT AS current_month_st,
    coalesce(
        SUM(total_amount) FILTER (
            WHERE date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
        ),
        0
    )::FLOAT AS last_month_st
FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
    AND created_at >= date_trunc('month', CURRENT_DATE - INTERVAL '1 month')
`

type GetTotalAmountSummaryRow struct {
	CurrentMonthSt float64 `json:"current_month_st"`
	LastMonthSt    float64 `json:"last_month_st"`
}

func (q *Queries) GetTotalAmountSummary(ctx context.Context, companyID pgtype.UUID) (GetTotalAmountSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTotalAmountSummary, companyID)
	var i GetTotalAmountSummaryRow
	err := row.Scan(&i.CurrentMonthSt, &i.LastMonthSt)
	return i, err
}

const listSales = `-- name: ListSales :many
SELECT id,
    sale_at,
    total_amount,
    status,
    created_at
FROM sales
WHERE company_id = $1
    AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListSalesRow struct {
	ID          pgtype.UUID        `json:"id"`
	SaleAt      pgtype.Timestamptz `json:"sale_at"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Status      interface{}        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSales(ctx context.Context, companyID pgtype.UUID) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleAt,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByCompanyAndStatus = `-- name: ListSalesByCompanyAndStatus :many
SELECT s.id AS sale_id,
    s.total_amount,
    s.discount_amount,
    s.status,
    s.sale_at,
    s.created_at AS sale_date,
    si.id AS item_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount,
    p.name AS product_name,
    COALESCE(c.full_name, '') AS customer_name
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
    INNER JOIN sale_items si ON s.id = si.sale_id
    INNER JOIN products p ON si.product_id = p.id
WHERE s.company_id = $1
    AND (
        (
            $2::text IS NULL
            OR $2::text = ''
        )
        OR s.status::text = $2::text
    )
ORDER BY s.created_at DESC
`

type ListSalesByCompanyAndStatusParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Column2   string      `json:"column_2"`
}

type ListSalesByCompanyAndStatusRow struct {
	SaleID         pgtype.UUID        `json:"sale_id"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	Status         interface{}        `json:"status"`
	SaleAt         pgtype.Timestamptz `json:"sale_at"`
	SaleDate       pgtype.Timestamptz `json:"sale_date"`
	ItemID         pgtype.UUID        `json:"item_id"`
	ProductID      pgtype.UUID        `json:"product_id"`
	Quantity       int32              `json:"quantity"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	Discount       pgtype.Numeric     `json:"discount"`
	ProductName    string             `json:"product_name"`
	CustomerName   string             `json:"customer_name"`
}

func (q *Queries) ListSalesByCompanyAndStatus(ctx context.Context, arg ListSalesByCompanyAndStatusParams) ([]ListSalesByCompanyAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listSalesByCompanyAndStatus, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesByCompanyAndStatusRow{}
	for rows.Next() {
		var i ListSalesByCompanyAndStatusRow
		if err := rows.Scan(
			&i.SaleID,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.Status,
			&i.SaleAt,
			&i.SaleDate,
			&i.ItemID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.Discount,
			&i.ProductName,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesWithDetails = `-- name: ListSalesWithDetails :many
SELECT -- Dados da venda
    s.id AS sale_id,
    s.sale_at,
    s.subtotal,
    s.discount_amount,
    s.total_amount,
    s.installments_count,
    s.payment_method,
    s.status AS sale_status,
    s.down_payment,
    -- Dados do cliente
    c.id AS customer_id,
    COALESCE(c.full_name, '') AS customer_name,
    -- Dados dos produtos (itens da venda)
    si.id AS sale_item_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount AS item_discount,
    p.name AS product_name,
    -- Parcelas (accounts_receivable)
    ar.id AS installment_id,
    ar.total_amount AS installment_total_amount,
    ar.balance AS installment_balance,
    ar.due_date,
    ar.installment_number,
    ar.status AS installment_status
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
    INNER JOIN sale_items si ON s.id = si.sale_id
    INNER JOIN products p ON si.product_id = p.id
    LEFT JOIN accounts_receivable ar ON s.id = ar.sale_id
WHERE s.company_id = $1 -- id da empresa
    AND s.deleted_at IS NULL
ORDER BY s.sale_at DESC,
    si.id,
    ar.installment_number
`

type ListSalesWithDetailsRow struct {
	SaleID                 pgtype.UUID        `json:"sale_id"`
	SaleAt                 pgtype.Timestamptz `json:"sale_at"`
	Subtotal               pgtype.Numeric     `json:"subtotal"`
	DiscountAmount         pgtype.Numeric     `json:"discount_amount"`
	TotalAmount            pgtype.Numeric     `json:"total_amount"`
	InstallmentsCount      int32              `json:"installments_count"`
	PaymentMethod          interface{}        `json:"payment_method"`
	SaleStatus             interface{}        `json:"sale_status"`
	DownPayment            pgtype.Numeric     `json:"down_payment"`
	CustomerID             pgtype.UUID        `json:"customer_id"`
	CustomerName           string             `json:"customer_name"`
	SaleItemID             pgtype.UUID        `json:"sale_item_id"`
	ProductID              pgtype.UUID        `json:"product_id"`
	Quantity               int32              `json:"quantity"`
	UnitPrice              pgtype.Numeric     `json:"unit_price"`
	ItemDiscount           pgtype.Numeric     `json:"item_discount"`
	ProductName            string             `json:"product_name"`
	InstallmentID          pgtype.UUID        `json:"installment_id"`
	InstallmentTotalAmount pgtype.Numeric     `json:"installment_total_amount"`
	InstallmentBalance     pgtype.Numeric     `json:"installment_balance"`
	DueDate                pgtype.Date        `json:"due_date"`
	InstallmentNumber      pgtype.Int4        `json:"installment_number"`
	InstallmentStatus      pgtype.Text        `json:"installment_status"`
}

func (q *Queries) ListSalesWithDetails(ctx context.Context, companyID pgtype.UUID) ([]ListSalesWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, listSalesWithDetails, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesWithDetailsRow{}
	for rows.Next() {
		var i ListSalesWithDetailsRow
		if err := rows.Scan(
			&i.SaleID,
			&i.SaleAt,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.InstallmentsCount,
			&i.PaymentMethod,
			&i.SaleStatus,
			&i.DownPayment,
			&i.CustomerID,
			&i.CustomerName,
			&i.SaleItemID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.ItemDiscount,
			&i.ProductName,
			&i.InstallmentID,
			&i.InstallmentTotalAmount,
			&i.InstallmentBalance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.InstallmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesWithDetailsPaginate = `-- name: ListSalesWithDetailsPaginate :many
WITH filtered_sales AS (
    -- Vendas distintas que casam com os filtros (busca, status, formas de pagamento e datas).
    -- Precisa ser resolvido antes de paginar, pois os JOINs com itens/parcelas multiplicam
    -- as linhas por venda e "count(DISTINCT ...) OVER()" não é suportado pelo Postgres.
    SELECT DISTINCT s.id, s.sale_at
    FROM sales s
        LEFT JOIN customers c ON s.customer_id = c.id
        INNER JOIN sale_items si ON s.id = si.sale_id
        INNER JOIN products p ON si.product_id = p.id
        LEFT JOIN accounts_receivable ar ON s.id = ar.sale_id
    WHERE s.company_id = $1
        AND s.deleted_at IS NULL
        -- Busca livre: nome do cliente ou nome do produto
        AND (
            $6::text = '' OR
            to_tsvector('portuguese_unaccent', coalesce(c.full_name, ''))
                @@ plainto_tsquery('portuguese_unaccent', $6::text)
            OR to_tsvector(
                'portuguese_unaccent',
                coalesce(p.name, '') || ' ' || coalesce(p.description, '')
            ) @@ plainto_tsquery('portuguese_unaccent', $6::text)
        )
        -- Status da venda (paid, pending, overdue, scheduled, canceled, partial). NULL = todos.
        AND (
            $7::account_status_enum IS NULL OR
            s.status = $7::account_status_enum
        )
        -- Forma de pagamento (cash, credit_card, pix, etc). NULL = todas.
        AND (
            $8::payment_method_enum IS NULL OR
            s.payment_method = $8::payment_method_enum
        )
        -- Data de pagamento/vencimento da parcela (accounts_receivable.due_date)
        AND ($9::date IS NULL OR ar.due_date >= $9::date)
        AND ($10::date IS NULL OR ar.due_date < ($10::date + INTERVAL '1 day'))
        -- Data da venda (sales.sale_at)
        AND ($11::date IS NULL OR s.sale_at >= $11::date)
        AND ($12::date IS NULL OR s.sale_at < ($12::date + INTERVAL '1 day'))
),
paginated_sales AS (
    -- Pagina por venda (não por linha), preservando o total antes do LIMIT/OFFSET.
    SELECT
        fs.id,
        count(*) OVER() AS total_count
    FROM filtered_sales fs
    ORDER BY
        CASE WHEN $4::text = 'sale_at' AND $5::text = 'asc'  THEN fs.sale_at END ASC,
        CASE WHEN $4::text = 'sale_at' AND $5::text = 'desc' THEN fs.sale_at END DESC,
        fs.sale_at DESC
    LIMIT $2
    OFFSET $3
)
SELECT
    -- Dados da venda
    s.id AS sale_id,
    s.sale_at,
    s.subtotal,
    s.discount_amount,
    s.total_amount,
    s.installments_count,
    s.payment_method,
    s.status AS sale_status,
    s.down_payment,
    -- Dados do cliente
    c.id AS customer_id,
    COALESCE(c.full_name, '') AS customer_name,
    -- Dados dos produtos (itens da venda)
    si.id AS sale_item_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount AS item_discount,
    p.name AS product_name,
    -- Parcelas (accounts_receivable)
    ar.id AS installment_id,
    ar.total_amount AS installment_total_amount,
    ar.balance AS installment_balance,
    ar.due_date,
    ar.installment_number,
    ar.status AS installment_status,
    ps.total_count
FROM paginated_sales ps
    INNER JOIN sales s ON s.id = ps.id
    LEFT JOIN customers c ON s.customer_id = c.id
    INNER JOIN sale_items si ON s.id = si.sale_id
    INNER JOIN products p ON si.product_id = p.id
    LEFT JOIN accounts_receivable ar ON s.id = ar.sale_id
ORDER BY
    CASE WHEN $4::text = 'sale_at'    AND $5::text = 'asc'  THEN s.sale_at END ASC,
    CASE WHEN $4::text = 'sale_at'    AND $5::text = 'desc' THEN s.sale_at END DESC,
    s.sale_at DESC,
    ar.installment_number ASC
`

type ListSalesWithDetailsPaginateParams struct {
	CompanyID        pgtype.UUID `json:"company_id"`
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
	SortBy           string      `json:"sort_by"`
	OrderBy          string      `json:"order_by"`
	Search           string      `json:"search"`
	SaleStatus       interface{} `json:"sale_status"`
	PaymentMethod    interface{} `json:"payment_method"`
	PaymentStartDate pgtype.Date `json:"payment_start_date"`
	PaymentEndDate   pgtype.Date `json:"payment_end_date"`
	SaleStartDate    pgtype.Date `json:"sale_start_date"`
	SaleEndDate      pgtype.Date `json:"sale_end_date"`
}

type ListSalesWithDetailsPaginateRow struct {
	SaleID                 pgtype.UUID        `json:"sale_id"`
	SaleAt                 pgtype.Timestamptz `json:"sale_at"`
	Subtotal               pgtype.Numeric     `json:"subtotal"`
	DiscountAmount         pgtype.Numeric     `json:"discount_amount"`
	TotalAmount            pgtype.Numeric     `json:"total_amount"`
	InstallmentsCount      int32              `json:"installments_count"`
	PaymentMethod          interface{}        `json:"payment_method"`
	SaleStatus             interface{}        `json:"sale_status"`
	DownPayment            pgtype.Numeric     `json:"down_payment"`
	CustomerID             pgtype.UUID        `json:"customer_id"`
	CustomerName           string             `json:"customer_name"`
	SaleItemID             pgtype.UUID        `json:"sale_item_id"`
	ProductID              pgtype.UUID        `json:"product_id"`
	Quantity               int32              `json:"quantity"`
	UnitPrice              pgtype.Numeric     `json:"unit_price"`
	ItemDiscount           pgtype.Numeric     `json:"item_discount"`
	ProductName            string             `json:"product_name"`
	InstallmentID          pgtype.UUID        `json:"installment_id"`
	InstallmentTotalAmount pgtype.Numeric     `json:"installment_total_amount"`
	InstallmentBalance     pgtype.Numeric     `json:"installment_balance"`
	DueDate                pgtype.Date        `json:"due_date"`
	InstallmentNumber      pgtype.Int4        `json:"installment_number"`
	InstallmentStatus      pgtype.Text        `json:"installment_status"`
	TotalCount             int64              `json:"total_count"`
}

func (q *Queries) ListSalesWithDetailsPaginate(ctx context.Context, arg ListSalesWithDetailsPaginateParams) ([]ListSalesWithDetailsPaginateRow, error) {
	rows, err := q.db.Query(ctx, listSalesWithDetailsPaginate,
		arg.CompanyID,
		arg.Limit,
		arg.Offset,
		arg.SortBy,
		arg.OrderBy,
		arg.Search,
		arg.SaleStatus,
		arg.PaymentMethod,
		arg.PaymentStartDate,
		arg.PaymentEndDate,
		arg.SaleStartDate,
		arg.SaleEndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesWithDetailsPaginateRow{}
	for rows.Next() {
		var i ListSalesWithDetailsPaginateRow
		if err := rows.Scan(
			&i.SaleID,
			&i.SaleAt,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.InstallmentsCount,
			&i.PaymentMethod,
			&i.SaleStatus,
			&i.DownPayment,
			&i.CustomerID,
			&i.CustomerName,
			&i.SaleItemID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.ItemDiscount,
			&i.ProductName,
			&i.InstallmentID,
			&i.InstallmentTotalAmount,
			&i.InstallmentBalance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.InstallmentStatus,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesWithDetailsPendingOverdue = `-- name: ListSalesWithDetailsPendingOverdue :many
SELECT -- Dados da venda
    s.id AS sale_id,
    s.sale_at,
    s.subtotal,
    s.discount_amount,
    s.total_amount,
    s.installments_count,
    s.payment_method,
    s.status AS sale_status,
    s.down_payment,
    -- Dados do cliente
    c.id AS customer_id,
    COALESCE(c.full_name, '') AS customer_name,
    -- Dados dos produtos (itens da venda)
    si.id AS sale_item_id,
    si.product_id,
    si.quantity,
    si.unit_price,
    si.discount AS item_discount,
    p.name AS product_name,
    -- Parcelas (accounts_receivable)
    ar.id AS installment_id,
    ar.total_amount AS installment_total_amount,
    ar.balance AS installment_balance,
    ar.due_date,
    ar.installment_number,
    ar.status AS installment_status
FROM sales s
    LEFT JOIN customers c ON s.customer_id = c.id
    INNER JOIN sale_items si ON s.id = si.sale_id
    INNER JOIN products p ON si.product_id = p.id
    LEFT JOIN accounts_receivable ar ON s.id = ar.sale_id
WHERE s.company_id = $1 -- id da empresa
    AND s.deleted_at IS NULL
    AND s.status IN ('pending', 'overdue')
ORDER BY s.sale_at DESC,
    si.id,
    ar.installment_number
`

type ListSalesWithDetailsPendingOverdueRow struct {
	SaleID                 pgtype.UUID        `json:"sale_id"`
	SaleAt                 pgtype.Timestamptz `json:"sale_at"`
	Subtotal               pgtype.Numeric     `json:"subtotal"`
	DiscountAmount         pgtype.Numeric     `json:"discount_amount"`
	TotalAmount            pgtype.Numeric     `json:"total_amount"`
	InstallmentsCount      int32              `json:"installments_count"`
	PaymentMethod          interface{}        `json:"payment_method"`
	SaleStatus             interface{}        `json:"sale_status"`
	DownPayment            pgtype.Numeric     `json:"down_payment"`
	CustomerID             pgtype.UUID        `json:"customer_id"`
	CustomerName           string             `json:"customer_name"`
	SaleItemID             pgtype.UUID        `json:"sale_item_id"`
	ProductID              pgtype.UUID        `json:"product_id"`
	Quantity               int32              `json:"quantity"`
	UnitPrice              pgtype.Numeric     `json:"unit_price"`
	ItemDiscount           pgtype.Numeric     `json:"item_discount"`
	ProductName            string             `json:"product_name"`
	InstallmentID          pgtype.UUID        `json:"installment_id"`
	InstallmentTotalAmount pgtype.Numeric     `json:"installment_total_amount"`
	InstallmentBalance     pgtype.Numeric     `json:"installment_balance"`
	DueDate                pgtype.Date        `json:"due_date"`
	InstallmentNumber      pgtype.Int4        `json:"installment_number"`
	InstallmentStatus      pgtype.Text        `json:"installment_status"`
}

func (q *Queries) ListSalesWithDetailsPendingOverdue(ctx context.Context, companyID pgtype.UUID) ([]ListSalesWithDetailsPendingOverdueRow, error) {
	rows, err := q.db.Query(ctx, listSalesWithDetailsPendingOverdue, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesWithDetailsPendingOverdueRow{}
	for rows.Next() {
		var i ListSalesWithDetailsPendingOverdueRow
		if err := rows.Scan(
			&i.SaleID,
			&i.SaleAt,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.TotalAmount,
			&i.InstallmentsCount,
			&i.PaymentMethod,
			&i.SaleStatus,
			&i.DownPayment,
			&i.CustomerID,
			&i.CustomerName,
			&i.SaleItemID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.ItemDiscount,
			&i.ProductName,
			&i.InstallmentID,
			&i.InstallmentTotalAmount,
			&i.InstallmentBalance,
			&i.DueDate,
			&i.InstallmentNumber,
			&i.InstallmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOverdueSalesAndAccountsGlobal = `-- name: UpdateOverdueSalesAndAccountsGlobal :many
WITH updated_accounts AS (
    UPDATE accounts_receivable
    SET status = 'overdue'
    WHERE status IN ('pending', 'partial')
        AND due_date::DATE < CURRENT_DATE
    RETURNING sale_id, due_date, balance
),
updated_sales AS (
    UPDATE sales
    SET status = 'overdue',
        updated_at = CURRENT_TIMESTAMP
    WHERE id IN (
            SELECT sale_id
            FROM updated_accounts
        )
        AND status NOT IN ('paid', 'canceled')
    RETURNING id AS sale_id, customer_id, company_id
)
SELECT
    us.sale_id,
    us.customer_id,
    us.company_id,
    ua.due_date,
    ua.balance
FROM updated_sales us
JOIN updated_accounts ua ON ua.sale_id = us.sale_id
`

type UpdateOverdueSalesAndAccountsGlobalRow struct {
	SaleID     pgtype.UUID    `json:"sale_id"`
	CustomerID pgtype.UUID    `json:"customer_id"`
	CompanyID  pgtype.UUID    `json:"company_id"`
	DueDate    pgtype.Date    `json:"due_date"`
	Balance    pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateOverdueSalesAndAccountsGlobal(ctx context.Context) ([]UpdateOverdueSalesAndAccountsGlobalRow, error) {
	rows, err := q.db.Query(ctx, updateOverdueSalesAndAccountsGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UpdateOverdueSalesAndAccountsGlobalRow{}
	for rows.Next() {
		var i UpdateOverdueSalesAndAccountsGlobalRow
		if err := rows.Scan(
			&i.SaleID,
			&i.CustomerID,
			&i.CompanyID,
			&i.DueDate,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSale = `-- name: UpdateSale :exec
UPDATE sales
SET discount_amount = $1,
    subtotal = $2,
    total_amount = $3,
    installments_count = $4,
    down_payment = $5,
    due_days = $6,
    payment_method = $7,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $8,
    status = $9
WHERE id = $10
    AND company_id = $11
`

type UpdateSaleParams struct {
	DiscountAmount    pgtype.Numeric `json:"discount_amount"`
	Subtotal          pgtype.Numeric `json:"subtotal"`
	TotalAmount       pgtype.Numeric `json:"total_amount"`
	InstallmentsCount int32          `json:"installments_count"`
	DownPayment       pgtype.Numeric `json:"down_payment"`
	DueDays           pgtype.Int4    `json:"due_days"`
	PaymentMethod     interface{}    `json:"payment_method"`
	UpdatedBy         pgtype.UUID    `json:"updated_by"`
	Status            interface{}    `json:"status"`
	ID                pgtype.UUID    `json:"id"`
	CompanyID         pgtype.UUID    `json:"company_id"`
}

func (q *Queries) UpdateSale(ctx context.Context, arg UpdateSaleParams) error {
	_, err := q.db.Exec(ctx, updateSale,
		arg.DiscountAmount,
		arg.Subtotal,
		arg.TotalAmount,
		arg.InstallmentsCount,
		arg.DownPayment,
		arg.DueDays,
		arg.PaymentMethod,
		arg.UpdatedBy,
		arg.Status,
		arg.ID,
		arg.CompanyID,
	)
	return err
}

const updateSaleStatus = `-- name: UpdateSaleStatus :exec
UPDATE sales
SET status = $1,
    updated_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $3
    AND company_id = $4
`

type UpdateSaleStatusParams struct {
	Status    interface{} `json:"status"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
}

func (q *Queries) UpdateSaleStatus(ctx context.Context, arg UpdateSaleStatusParams) error {
	_, err := q.db.Exec(ctx, updateSaleStatus,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
		arg.CompanyID,
	)
	return err
}
