// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions
SET
    status = 'cancelled',
    canceled_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelSubscription, id)
	return err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (
    company_id,
    plan_id,
    payment_method_id,
    external_subscription_id,
    status,
    current_period_start,
    current_period_end
)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateSubscriptionParams struct {
	CompanyID              pgtype.UUID        `json:"company_id"`
	PlanID                 pgtype.UUID        `json:"plan_id"`
	PaymentMethodID        pgtype.UUID        `json:"payment_method_id"`
	ExternalSubscriptionID pgtype.Text        `json:"external_subscription_id"`
	Status                 string             `json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.CompanyID,
		arg.PlanID,
		arg.PaymentMethodID,
		arg.ExternalSubscriptionID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}

const getSubscriptionByExternalSubscriptionId = `-- name: GetSubscriptionByExternalSubscriptionId :one
SELECT id, company_id, plan_id, payment_method_id, external_subscription_id, status, current_period_start, current_period_end, canceled_at, created_at, updated_at FROM subscriptions WHERE external_subscription_id = $1
`

func (q *Queries) GetSubscriptionByExternalSubscriptionId(ctx context.Context, externalSubscriptionID pgtype.Text) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByExternalSubscriptionId, externalSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PlanID,
		&i.PaymentMethodID,
		&i.ExternalSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionById = `-- name: GetSubscriptionById :one
SELECT id, company_id, plan_id, payment_method_id, external_subscription_id, status, current_period_start, current_period_end, canceled_at, created_at, updated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionById(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionById, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.PlanID,
		&i.PaymentMethodID,
		&i.ExternalSubscriptionID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionMethod = `-- name: UpdateSubscriptionMethod :exec
UPDATE subscriptions
SET
    payment_method_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSubscriptionMethodParams struct {
	ID              pgtype.UUID `json:"id"`
	PaymentMethodID pgtype.UUID `json:"payment_method_id"`
}

func (q *Queries) UpdateSubscriptionMethod(ctx context.Context, arg UpdateSubscriptionMethodParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionMethod, arg.ID, arg.PaymentMethodID)
	return err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :exec
UPDATE subscriptions
SET
    plan_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSubscriptionPlanParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionPlan, arg.ID, arg.PlanID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE subscriptions
SET
    status = $2,
    current_period_end = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID               pgtype.UUID        `json:"id"`
	Status           string             `json:"status"`
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.ID, arg.Status, arg.CurrentPeriodEnd)
	return err
}
