// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_payment_methods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscriptionPaymentMethod = `-- name: CreateSubscriptionPaymentMethod :one
INSERT INTO subscription_payment_methods (
    company_id,
    gateway_payment_method_id,
    type,
    card_brand,
    card_last4,
    card_exp_month,
    card_exp_year,
    is_default,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id
`

type CreateSubscriptionPaymentMethodParams struct {
	CompanyID              pgtype.UUID `json:"company_id"`
	GatewayPaymentMethodID string      `json:"gateway_payment_method_id"`
	Type                   string      `json:"type"`
	CardBrand              pgtype.Text `json:"card_brand"`
	CardLast4              pgtype.Text `json:"card_last4"`
	CardExpMonth           pgtype.Int4 `json:"card_exp_month"`
	CardExpYear            pgtype.Int4 `json:"card_exp_year"`
	IsDefault              pgtype.Bool `json:"is_default"`
	CreatedBy              pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSubscriptionPaymentMethod(ctx context.Context, arg CreateSubscriptionPaymentMethodParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPaymentMethod,
		arg.CompanyID,
		arg.GatewayPaymentMethodID,
		arg.Type,
		arg.CardBrand,
		arg.CardLast4,
		arg.CardExpMonth,
		arg.CardExpYear,
		arg.IsDefault,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSubscriptionPaymentMethod = `-- name: DeleteSubscriptionPaymentMethod :exec
DELETE FROM subscription_payment_methods WHERE id = $1
`

func (q *Queries) DeleteSubscriptionPaymentMethod(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionPaymentMethod, id)
	return err
}

const getSubscriptionPaymentMethodById = `-- name: GetSubscriptionPaymentMethodById :one
SELECT id, company_id, gateway_payment_method_id, type, card_brand, card_last4, card_exp_month, card_exp_year, is_default, created_by, updated_by, created_at, updated_at FROM subscription_payment_methods WHERE id = $1
`

func (q *Queries) GetSubscriptionPaymentMethodById(ctx context.Context, id pgtype.UUID) (SubscriptionPaymentMethod, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPaymentMethodById, id)
	var i SubscriptionPaymentMethod
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.GatewayPaymentMethodID,
		&i.Type,
		&i.CardBrand,
		&i.CardLast4,
		&i.CardExpMonth,
		&i.CardExpYear,
		&i.IsDefault,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionPaymentMethodsByCompanyId = `-- name: ListSubscriptionPaymentMethodsByCompanyId :many
SELECT id, company_id, gateway_payment_method_id, type, card_brand, card_last4, card_exp_month, card_exp_year, is_default, created_by, updated_by, created_at, updated_at FROM subscription_payment_methods WHERE company_id = $1
`

func (q *Queries) ListSubscriptionPaymentMethodsByCompanyId(ctx context.Context, companyID pgtype.UUID) ([]SubscriptionPaymentMethod, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPaymentMethodsByCompanyId, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPaymentMethod{}
	for rows.Next() {
		var i SubscriptionPaymentMethod
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.GatewayPaymentMethodID,
			&i.Type,
			&i.CardBrand,
			&i.CardLast4,
			&i.CardExpMonth,
			&i.CardExpYear,
			&i.IsDefault,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultSubscriptionPaymentMethod = `-- name: SetDefaultSubscriptionPaymentMethod :exec
UPDATE subscription_payment_methods SET is_default = $2, updated_by = $3 WHERE company_id = $1
`

type SetDefaultSubscriptionPaymentMethodParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	IsDefault pgtype.Bool `json:"is_default"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) SetDefaultSubscriptionPaymentMethod(ctx context.Context, arg SetDefaultSubscriptionPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, setDefaultSubscriptionPaymentMethod, arg.CompanyID, arg.IsDefault, arg.UpdatedBy)
	return err
}

const updateSubscriptionPaymentMethod = `-- name: UpdateSubscriptionPaymentMethod :exec
UPDATE subscription_payment_methods SET
    gateway_payment_method_id = $2,
    type = $3,
    card_brand = $4,
    card_last4 = $5,
    card_exp_month = $6,
    card_exp_year = $7,
    updated_at = NOW(),
    updated_by = $8
WHERE id = $1
`

type UpdateSubscriptionPaymentMethodParams struct {
	ID                     pgtype.UUID `json:"id"`
	GatewayPaymentMethodID string      `json:"gateway_payment_method_id"`
	Type                   string      `json:"type"`
	CardBrand              pgtype.Text `json:"card_brand"`
	CardLast4              pgtype.Text `json:"card_last4"`
	CardExpMonth           pgtype.Int4 `json:"card_exp_month"`
	CardExpYear            pgtype.Int4 `json:"card_exp_year"`
	UpdatedBy              pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateSubscriptionPaymentMethod(ctx context.Context, arg UpdateSubscriptionPaymentMethodParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionPaymentMethod,
		arg.ID,
		arg.GatewayPaymentMethodID,
		arg.Type,
		arg.CardBrand,
		arg.CardLast4,
		arg.CardExpMonth,
		arg.CardExpYear,
		arg.UpdatedBy,
	)
	return err
}
