// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
        name,
        email,
        username,
        password_hash,
        role,
        status,
        company_id,
        department_id,
        created_by,
        updated_by,
        created_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, email, username, password_hash, role, status, company_id, department_id, last_login_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Username     pgtype.Text        `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Status       interface{}        `json:"status"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.CompanyID,
		arg.DepartmentID,
		arg.CreatedBy,
		arg.UpdatedBy,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.DepartmentID,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, username, password_hash, role, status, company_id, department_id, last_login_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.DepartmentID,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, username, password_hash, role, status, company_id, department_id, last_login_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.DepartmentID,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, username, password_hash, role, status, company_id, department_id, last_login_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.CompanyID,
			&i.DepartmentID,
			&i.LastLoginAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
    AND deleted_at IS NULL
`

type UpdatePasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2,
    email = $3,
    username = $4,
    role = $5,
    status = $6,
    department_id = $7,
    updated_by = $8,
    updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
RETURNING id, name, email, username, password_hash, role, status, company_id, department_id, last_login_at, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	Username     pgtype.Text `json:"username"`
	Role         string      `json:"role"`
	Status       interface{} `json:"status"`
	DepartmentID pgtype.UUID `json:"department_id"`
	UpdatedBy    pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.Role,
		arg.Status,
		arg.DepartmentID,
		arg.UpdatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CompanyID,
		&i.DepartmentID,
		&i.LastLoginAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserCompanyAndRole = `-- name: UpdateUserCompanyAndRole :exec
UPDATE users
SET company_id = $2,
    role = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateUserCompanyAndRoleParams struct {
	ID        pgtype.UUID `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
	Role      string      `json:"role"`
}

func (q *Queries) UpdateUserCompanyAndRole(ctx context.Context, arg UpdateUserCompanyAndRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserCompanyAndRole, arg.ID, arg.CompanyID, arg.Role)
	return err
}
