// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: whatsapp_bot.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWhatsAppBotConfig = `-- name: CreateWhatsAppBotConfig :one


INSERT INTO whatsapp_bot_configs (
    company_id, instance_name, welcome_message, is_active
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, company_id, instance_name, welcome_message, is_active, created_at, updated_at
`

type CreateWhatsAppBotConfigParams struct {
	CompanyID      pgtype.UUID `json:"company_id"`
	InstanceName   string      `json:"instance_name"`
	WelcomeMessage string      `json:"welcome_message"`
	IsActive       bool        `json:"is_active"`
}

// queries/whatsapp_bot.sql
// ===== whatsapp_bot_configs =====
func (q *Queries) CreateWhatsAppBotConfig(ctx context.Context, arg CreateWhatsAppBotConfigParams) (WhatsappBotConfig, error) {
	row := q.db.QueryRow(ctx, createWhatsAppBotConfig,
		arg.CompanyID,
		arg.InstanceName,
		arg.WelcomeMessage,
		arg.IsActive,
	)
	var i WhatsappBotConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InstanceName,
		&i.WelcomeMessage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWhatsAppBotMenuOption = `-- name: CreateWhatsAppBotMenuOption :one

INSERT INTO whatsapp_bot_menu_options (
    bot_config_id, option_key, label, response_message, order_index
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, bot_config_id, option_key, label, response_message, order_index, created_at, updated_at
`

type CreateWhatsAppBotMenuOptionParams struct {
	BotConfigID     pgtype.UUID `json:"bot_config_id"`
	OptionKey       string      `json:"option_key"`
	Label           string      `json:"label"`
	ResponseMessage string      `json:"response_message"`
	OrderIndex      int32       `json:"order_index"`
}

// ===== whatsapp_bot_menu_options =====
func (q *Queries) CreateWhatsAppBotMenuOption(ctx context.Context, arg CreateWhatsAppBotMenuOptionParams) (WhatsappBotMenuOption, error) {
	row := q.db.QueryRow(ctx, createWhatsAppBotMenuOption,
		arg.BotConfigID,
		arg.OptionKey,
		arg.Label,
		arg.ResponseMessage,
		arg.OrderIndex,
	)
	var i WhatsappBotMenuOption
	err := row.Scan(
		&i.ID,
		&i.BotConfigID,
		&i.OptionKey,
		&i.Label,
		&i.ResponseMessage,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllMenuOptionsForBotConfig = `-- name: DeleteAllMenuOptionsForBotConfig :exec
DELETE FROM whatsapp_bot_menu_options
WHERE bot_config_id = $1
`

func (q *Queries) DeleteAllMenuOptionsForBotConfig(ctx context.Context, botConfigID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMenuOptionsForBotConfig, botConfigID)
	return err
}

const deleteWhatsAppBotConfig = `-- name: DeleteWhatsAppBotConfig :exec
DELETE FROM whatsapp_bot_configs
WHERE id = $1
`

func (q *Queries) DeleteWhatsAppBotConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWhatsAppBotConfig, id)
	return err
}

const deleteWhatsAppBotMenuOption = `-- name: DeleteWhatsAppBotMenuOption :exec
DELETE FROM whatsapp_bot_menu_options
WHERE id = $1
`

func (q *Queries) DeleteWhatsAppBotMenuOption(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWhatsAppBotMenuOption, id)
	return err
}

const getWhatsAppBotConfigByCompanyID = `-- name: GetWhatsAppBotConfigByCompanyID :one
SELECT id, company_id, instance_name, welcome_message, is_active, created_at, updated_at FROM whatsapp_bot_configs
WHERE company_id = $1
`

func (q *Queries) GetWhatsAppBotConfigByCompanyID(ctx context.Context, companyID pgtype.UUID) (WhatsappBotConfig, error) {
	row := q.db.QueryRow(ctx, getWhatsAppBotConfigByCompanyID, companyID)
	var i WhatsappBotConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InstanceName,
		&i.WelcomeMessage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWhatsAppBotConfigByInstanceName = `-- name: GetWhatsAppBotConfigByInstanceName :one
SELECT id, company_id, instance_name, welcome_message, is_active, created_at, updated_at FROM whatsapp_bot_configs
WHERE instance_name = $1 AND is_active = true
`

func (q *Queries) GetWhatsAppBotConfigByInstanceName(ctx context.Context, instanceName string) (WhatsappBotConfig, error) {
	row := q.db.QueryRow(ctx, getWhatsAppBotConfigByInstanceName, instanceName)
	var i WhatsappBotConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InstanceName,
		&i.WelcomeMessage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWhatsAppBotConfigWithOptionsByInstance = `-- name: GetWhatsAppBotConfigWithOptionsByInstance :many

SELECT
    c.id AS bot_config_id,
    c.company_id,
    c.instance_name,
    c.welcome_message,
    c.is_active,
    o.id AS option_id,
    o.option_key,
    o.label,
    o.response_message,
    o.order_index
FROM whatsapp_bot_configs c
LEFT JOIN whatsapp_bot_menu_options o ON o.bot_config_id = c.id
WHERE c.instance_name = $1 AND c.is_active = true
ORDER BY o.order_index ASC, o.option_key ASC
`

type GetWhatsAppBotConfigWithOptionsByInstanceRow struct {
	BotConfigID     pgtype.UUID `json:"bot_config_id"`
	CompanyID       pgtype.UUID `json:"company_id"`
	InstanceName    string      `json:"instance_name"`
	WelcomeMessage  string      `json:"welcome_message"`
	IsActive        bool        `json:"is_active"`
	OptionID        pgtype.UUID `json:"option_id"`
	OptionKey       pgtype.Text `json:"option_key"`
	Label           pgtype.Text `json:"label"`
	ResponseMessage pgtype.Text `json:"response_message"`
	OrderIndex      pgtype.Int4 `json:"order_index"`
}

// ===== consulta composta (config + opções de uma vez) =====
func (q *Queries) GetWhatsAppBotConfigWithOptionsByInstance(ctx context.Context, instanceName string) ([]GetWhatsAppBotConfigWithOptionsByInstanceRow, error) {
	rows, err := q.db.Query(ctx, getWhatsAppBotConfigWithOptionsByInstance, instanceName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWhatsAppBotConfigWithOptionsByInstanceRow{}
	for rows.Next() {
		var i GetWhatsAppBotConfigWithOptionsByInstanceRow
		if err := rows.Scan(
			&i.BotConfigID,
			&i.CompanyID,
			&i.InstanceName,
			&i.WelcomeMessage,
			&i.IsActive,
			&i.OptionID,
			&i.OptionKey,
			&i.Label,
			&i.ResponseMessage,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWhatsAppBotMenuOptionByKey = `-- name: GetWhatsAppBotMenuOptionByKey :one
SELECT id, bot_config_id, option_key, label, response_message, order_index, created_at, updated_at FROM whatsapp_bot_menu_options
WHERE bot_config_id = $1 AND option_key = $2
`

type GetWhatsAppBotMenuOptionByKeyParams struct {
	BotConfigID pgtype.UUID `json:"bot_config_id"`
	OptionKey   string      `json:"option_key"`
}

func (q *Queries) GetWhatsAppBotMenuOptionByKey(ctx context.Context, arg GetWhatsAppBotMenuOptionByKeyParams) (WhatsappBotMenuOption, error) {
	row := q.db.QueryRow(ctx, getWhatsAppBotMenuOptionByKey, arg.BotConfigID, arg.OptionKey)
	var i WhatsappBotMenuOption
	err := row.Scan(
		&i.ID,
		&i.BotConfigID,
		&i.OptionKey,
		&i.Label,
		&i.ResponseMessage,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWhatsAppBotMenuOptions = `-- name: ListWhatsAppBotMenuOptions :many
SELECT id, bot_config_id, option_key, label, response_message, order_index, created_at, updated_at FROM whatsapp_bot_menu_options
WHERE bot_config_id = $1
ORDER BY order_index ASC, option_key ASC
`

func (q *Queries) ListWhatsAppBotMenuOptions(ctx context.Context, botConfigID pgtype.UUID) ([]WhatsappBotMenuOption, error) {
	rows, err := q.db.Query(ctx, listWhatsAppBotMenuOptions, botConfigID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WhatsappBotMenuOption{}
	for rows.Next() {
		var i WhatsappBotMenuOption
		if err := rows.Scan(
			&i.ID,
			&i.BotConfigID,
			&i.OptionKey,
			&i.Label,
			&i.ResponseMessage,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWhatsAppBotActive = `-- name: SetWhatsAppBotActive :exec
UPDATE whatsapp_bot_configs
SET is_active = $2, updated_at = now()
WHERE id = $1
`

type SetWhatsAppBotActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetWhatsAppBotActive(ctx context.Context, arg SetWhatsAppBotActiveParams) error {
	_, err := q.db.Exec(ctx, setWhatsAppBotActive, arg.ID, arg.IsActive)
	return err
}

const updateWhatsAppBotConfig = `-- name: UpdateWhatsAppBotConfig :one
UPDATE whatsapp_bot_configs
SET
    welcome_message = $2,
    is_active = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, company_id, instance_name, welcome_message, is_active, created_at, updated_at
`

type UpdateWhatsAppBotConfigParams struct {
	ID             pgtype.UUID `json:"id"`
	WelcomeMessage string      `json:"welcome_message"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpdateWhatsAppBotConfig(ctx context.Context, arg UpdateWhatsAppBotConfigParams) (WhatsappBotConfig, error) {
	row := q.db.QueryRow(ctx, updateWhatsAppBotConfig, arg.ID, arg.WelcomeMessage, arg.IsActive)
	var i WhatsappBotConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InstanceName,
		&i.WelcomeMessage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWhatsAppBotInstanceName = `-- name: UpdateWhatsAppBotInstanceName :one
UPDATE whatsapp_bot_configs
SET
    instance_name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, company_id, instance_name, welcome_message, is_active, created_at, updated_at
`

type UpdateWhatsAppBotInstanceNameParams struct {
	ID           pgtype.UUID `json:"id"`
	InstanceName string      `json:"instance_name"`
}

func (q *Queries) UpdateWhatsAppBotInstanceName(ctx context.Context, arg UpdateWhatsAppBotInstanceNameParams) (WhatsappBotConfig, error) {
	row := q.db.QueryRow(ctx, updateWhatsAppBotInstanceName, arg.ID, arg.InstanceName)
	var i WhatsappBotConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.InstanceName,
		&i.WelcomeMessage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWhatsAppBotMenuOption = `-- name: UpdateWhatsAppBotMenuOption :one
UPDATE whatsapp_bot_menu_options
SET
    label = $2,
    response_message = $3,
    order_index = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, bot_config_id, option_key, label, response_message, order_index, created_at, updated_at
`

type UpdateWhatsAppBotMenuOptionParams struct {
	ID              pgtype.UUID `json:"id"`
	Label           string      `json:"label"`
	ResponseMessage string      `json:"response_message"`
	OrderIndex      int32       `json:"order_index"`
}

func (q *Queries) UpdateWhatsAppBotMenuOption(ctx context.Context, arg UpdateWhatsAppBotMenuOptionParams) (WhatsappBotMenuOption, error) {
	row := q.db.QueryRow(ctx, updateWhatsAppBotMenuOption,
		arg.ID,
		arg.Label,
		arg.ResponseMessage,
		arg.OrderIndex,
	)
	var i WhatsappBotMenuOption
	err := row.Scan(
		&i.ID,
		&i.BotConfigID,
		&i.OptionKey,
		&i.Label,
		&i.ResponseMessage,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
