// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
package mocks

import (
	"context"
	"reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	plansFeatureDomain "github.com/ProTrack-Solutions/protrack-api/internal/plan_features/domain"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// MockPlanFeatureServiceInterface é o mock para PlanFeatureServiceInterface.
type MockPlanFeatureServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPlanFeatureServiceInterfaceMockRecorder
}

// MockPlanFeatureServiceInterfaceMockRecorder registra as expectativas.
type MockPlanFeatureServiceInterfaceMockRecorder struct {
	mock *MockPlanFeatureServiceInterface
}

// NewMockPlanFeatureServiceInterface cria uma nova instância do mock.
func NewMockPlanFeatureServiceInterface(ctrl *gomock.Controller) *MockPlanFeatureServiceInterface {
	mock := &MockPlanFeatureServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPlanFeatureServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockPlanFeatureServiceInterface) EXPECT() *MockPlanFeatureServiceInterfaceMockRecorder {
	return m.recorder
}

// CreatePlanFeatureTx mocks o método CreatePlanFeatureTx.
func (m *MockPlanFeatureServiceInterface) CreatePlanFeatureTx(ctx context.Context, tx db.DBTX, planId uuid.UUID, req []plansFeatureDomain.CreatePlanFeatureRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlanFeatureTx", ctx, tx, planId, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPlanFeatureServiceInterfaceMockRecorder) CreatePlanFeatureTx(ctx, tx, planId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlanFeatureTx", reflect.TypeOf((*MockPlanFeatureServiceInterface)(nil).CreatePlanFeatureTx), ctx, tx, planId, req)
}

// ListFeaturesByPlanID mocks o método ListFeaturesByPlanID.
func (m *MockPlanFeatureServiceInterface) ListFeaturesByPlanID(ctx context.Context, planId uuid.UUID) ([]plansFeatureDomain.PlanFeatureResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeaturesByPlanID", ctx, planId)
	ret0, _ := ret[0].([]plansFeatureDomain.PlanFeatureResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlanFeatureServiceInterfaceMockRecorder) ListFeaturesByPlanID(ctx, planId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeaturesByPlanID", reflect.TypeOf((*MockPlanFeatureServiceInterface)(nil).ListFeaturesByPlanID), ctx, planId)
}
