// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/plans/service (interfaces: RepositoryInterface)
package mocks

import (
	"context"
	"reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	"github.com/jackc/pgx/v5/pgtype"
	"go.uber.org/mock/gomock"
)

// MockRepositoryInterface é o mock da interface de repositório de plans.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder registra as expectativas.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface cria um novo mock.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna a estrutura de expectativas.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreatePlans mocks o método CreatePlans.
func (m *MockRepositoryInterface) CreatePlans(ctx context.Context, arg db.CreatePlanParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlans", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) CreatePlans(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlans", reflect.TypeOf((*MockRepositoryInterface)(nil).CreatePlans), ctx, arg)
}

// GetPlanByID mocks o método GetPlanByID.
func (m *MockRepositoryInterface) GetPlanByID(ctx context.Context, planId pgtype.UUID) (db.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanByID", ctx, planId)
	ret0, _ := ret[0].(db.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetPlanByID(ctx, planId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPlanByID), ctx, planId)
}

// ListPlans mocks o método ListPlans.
func (m *MockRepositoryInterface) ListPlans(ctx context.Context) ([]db.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans", ctx)
	ret0, _ := ret[0].([]db.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockRepositoryInterface)(nil).ListPlans), ctx)
}

// ListPlansByActiveStatus mocks o método ListPlansByActiveStatus.
func (m *MockRepositoryInterface) ListPlansByActiveStatus(ctx context.Context, active pgtype.Bool) ([]db.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlansByActiveStatus", ctx, active)
	ret0, _ := ret[0].([]db.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListPlansByActiveStatus(ctx, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlansByActiveStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).ListPlansByActiveStatus), ctx, active)
}

// UpdatePlan mocks o método UpdatePlan.
func (m *MockRepositoryInterface) UpdatePlan(ctx context.Context, arg db.UpdatePlanParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdatePlan(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdatePlan), ctx, arg)
}

// TogglePlanActiveStatus mocks o método TogglePlanActiveStatus.
func (m *MockRepositoryInterface) TogglePlanActiveStatus(ctx context.Context, arg db.TogglePlanActiveStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TogglePlanActiveStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) TogglePlanActiveStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TogglePlanActiveStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).TogglePlanActiveStatus), ctx, arg)
}
