// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: mock de ServiceInterface para testes do handler de plans.
package mocks

import (
	"context"
	"reflect"

	"github.com/ProTrack-Solutions/protrack-api/internal/plans/domain"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// ServiceInterface define o contrato de serviço de plans consumido pelo handler.
type ServiceInterface interface {
	CreatePlans(ctx context.Context, req domain.CreatePlanRequest) error
	GetPlanByID(ctx context.Context, planId uuid.UUID) (domain.PlanResponse, error)
	ListPlans(ctx context.Context) ([]domain.PlanResponse, error)
	ListPlansByActiveStatus(ctx context.Context, active bool) ([]domain.PlanResponse, error)
	UpdatePlan(ctx context.Context, planId uuid.UUID, req domain.UpdatePlanParams) error
	TogglePlanActiveStatus(ctx context.Context, planId uuid.UUID, active bool) error
}

// MockServiceInterface é o mock da interface de serviço de plans.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder registra as expectativas do serviço.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface cria um novo mock de serviço.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna a estrutura de expectativas.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreatePlans mocks o método CreatePlans.
func (m *MockServiceInterface) CreatePlans(ctx context.Context, req domain.CreatePlanRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlans", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) CreatePlans(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlans", reflect.TypeOf((*MockServiceInterface)(nil).CreatePlans), ctx, req)
}

// GetPlanByID mocks o método GetPlanByID.
func (m *MockServiceInterface) GetPlanByID(ctx context.Context, planId uuid.UUID) (domain.PlanResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanByID", ctx, planId)
	ret0, _ := ret[0].(domain.PlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetPlanByID(ctx, planId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanByID", reflect.TypeOf((*MockServiceInterface)(nil).GetPlanByID), ctx, planId)
}

// ListPlans mocks o método ListPlans.
func (m *MockServiceInterface) ListPlans(ctx context.Context) ([]domain.PlanResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlans", ctx)
	ret0, _ := ret[0].([]domain.PlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlans", reflect.TypeOf((*MockServiceInterface)(nil).ListPlans), ctx)
}

// ListPlansByActiveStatus mocks o método ListPlansByActiveStatus.
func (m *MockServiceInterface) ListPlansByActiveStatus(ctx context.Context, active bool) ([]domain.PlanResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlansByActiveStatus", ctx, active)
	ret0, _ := ret[0].([]domain.PlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListPlansByActiveStatus(ctx, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlansByActiveStatus", reflect.TypeOf((*MockServiceInterface)(nil).ListPlansByActiveStatus), ctx, active)
}

// UpdatePlan mocks o método UpdatePlan.
func (m *MockServiceInterface) UpdatePlan(ctx context.Context, planId uuid.UUID, req domain.UpdatePlanParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlan", ctx, planId, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) UpdatePlan(ctx, planId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlan", reflect.TypeOf((*MockServiceInterface)(nil).UpdatePlan), ctx, planId, req)
}

// TogglePlanActiveStatus mocks o método TogglePlanActiveStatus.
func (m *MockServiceInterface) TogglePlanActiveStatus(ctx context.Context, planId uuid.UUID, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TogglePlanActiveStatus", ctx, planId, active)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) TogglePlanActiveStatus(ctx, planId, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TogglePlanActiveStatus", reflect.TypeOf((*MockServiceInterface)(nil).TogglePlanActiveStatus), ctx, planId, active)
}
