// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain (interfaces: ServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/meta_whatsapp/mocks/mock_service.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain ServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetCompanyConfig mocks base method.
func (m *MockServiceInterface) GetCompanyConfig(ctx context.Context, companyId uuid.UUID) (*domain.CompanyWhatsAppConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyConfig", ctx, companyId)
	ret0, _ := ret[0].(*domain.CompanyWhatsAppConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyConfig indicates an expected call of GetCompanyConfig.
func (mr *MockServiceInterfaceMockRecorder) GetCompanyConfig(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyConfig", reflect.TypeOf((*MockServiceInterface)(nil).GetCompanyConfig), ctx, companyId)
}

// HandleWebhookEvent mocks base method.
func (m *MockServiceInterface) HandleWebhookEvent(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebhookEvent", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebhookEvent indicates an expected call of HandleWebhookEvent.
func (mr *MockServiceInterfaceMockRecorder) HandleWebhookEvent(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhookEvent", reflect.TypeOf((*MockServiceInterface)(nil).HandleWebhookEvent), ctx, payload)
}

// ListApprovedTemplates mocks base method.
func (m *MockServiceInterface) ListApprovedTemplates(ctx context.Context) ([]domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApprovedTemplates", ctx)
	ret0, _ := ret[0].([]domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApprovedTemplates indicates an expected call of ListApprovedTemplates.
func (mr *MockServiceInterfaceMockRecorder) ListApprovedTemplates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApprovedTemplates", reflect.TypeOf((*MockServiceInterface)(nil).ListApprovedTemplates), ctx)
}

// SendMessage mocks base method.
func (m *MockServiceInterface) SendMessage(ctx context.Context, companyId uuid.UUID, req domain.SendMessageRequest) (*domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, companyId, req)
	ret0, _ := ret[0].(*domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockServiceInterfaceMockRecorder) SendMessage(ctx, companyId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockServiceInterface)(nil).SendMessage), ctx, companyId, req)
}

// SyncMonthlyUsage mocks base method.
func (m *MockServiceInterface) SyncMonthlyUsage(ctx context.Context, companyId uuid.UUID, periodStart, periodEnd time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncMonthlyUsage", ctx, companyId, periodStart, periodEnd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncMonthlyUsage indicates an expected call of SyncMonthlyUsage.
func (mr *MockServiceInterfaceMockRecorder) SyncMonthlyUsage(ctx, companyId, periodStart, periodEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncMonthlyUsage", reflect.TypeOf((*MockServiceInterface)(nil).SyncMonthlyUsage), ctx, companyId, periodStart, periodEnd)
}

// UpsertCompanyConfig mocks base method.
func (m *MockServiceInterface) UpsertCompanyConfig(ctx context.Context, companyId uuid.UUID, req domain.UpsertCompanyConfigRequest) (*domain.CompanyWhatsAppConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCompanyConfig", ctx, companyId, req)
	ret0, _ := ret[0].(*domain.CompanyWhatsAppConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCompanyConfig indicates an expected call of UpsertCompanyConfig.
func (mr *MockServiceInterfaceMockRecorder) UpsertCompanyConfig(ctx, companyId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCompanyConfig", reflect.TypeOf((*MockServiceInterface)(nil).UpsertCompanyConfig), ctx, companyId, req)
}
