// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain (interfaces: MetaClientInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/meta_whatsapp/mocks/mock_meta_client.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain MetaClientInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMetaClientInterface is a mock of MetaClientInterface interface.
type MockMetaClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetaClientInterfaceMockRecorder
	isgomock struct{}
}

// MockMetaClientInterfaceMockRecorder is the mock recorder for MockMetaClientInterface.
type MockMetaClientInterfaceMockRecorder struct {
	mock *MockMetaClientInterface
}

// NewMockMetaClientInterface creates a new mock instance.
func NewMockMetaClientInterface(ctrl *gomock.Controller) *MockMetaClientInterface {
	mock := &MockMetaClientInterface{ctrl: ctrl}
	mock.recorder = &MockMetaClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaClientInterface) EXPECT() *MockMetaClientInterfaceMockRecorder {
	return m.recorder
}

// SendTemplateMessage mocks base method.
func (m *MockMetaClientInterface) SendTemplateMessage(ctx context.Context, phoneNumberID, accessToken string, req domain.SendMessageRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplateMessage", ctx, phoneNumberID, accessToken, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTemplateMessage indicates an expected call of SendTemplateMessage.
func (mr *MockMetaClientInterfaceMockRecorder) SendTemplateMessage(ctx, phoneNumberID, accessToken, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplateMessage", reflect.TypeOf((*MockMetaClientInterface)(nil).SendTemplateMessage), ctx, phoneNumberID, accessToken, req)
}
