// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/meta_whatsapp/mocks/mock_repository.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain RepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountMessagesInPeriod mocks base method.
func (m *MockRepositoryInterface) CountMessagesInPeriod(ctx context.Context, arg db.CountMessagesInPeriodParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMessagesInPeriod", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMessagesInPeriod indicates an expected call of CountMessagesInPeriod.
func (mr *MockRepositoryInterfaceMockRecorder) CountMessagesInPeriod(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMessagesInPeriod", reflect.TypeOf((*MockRepositoryInterface)(nil).CountMessagesInPeriod), ctx, arg)
}

// CreateWhatsAppMessage mocks base method.
func (m *MockRepositoryInterface) CreateWhatsAppMessage(ctx context.Context, arg db.CreateWhatsAppMessageParams) (db.WhatsappMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWhatsAppMessage", ctx, arg)
	ret0, _ := ret[0].(db.WhatsappMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWhatsAppMessage indicates an expected call of CreateWhatsAppMessage.
func (mr *MockRepositoryInterfaceMockRecorder) CreateWhatsAppMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWhatsAppMessage", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateWhatsAppMessage), ctx, arg)
}

// GetCompanyWhatsAppConfig mocks base method.
func (m *MockRepositoryInterface) GetCompanyWhatsAppConfig(ctx context.Context, companyId pgtype.UUID) (db.CompanyWhatsappConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyWhatsAppConfig", ctx, companyId)
	ret0, _ := ret[0].(db.CompanyWhatsappConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyWhatsAppConfig indicates an expected call of GetCompanyWhatsAppConfig.
func (mr *MockRepositoryInterfaceMockRecorder) GetCompanyWhatsAppConfig(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyWhatsAppConfig", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCompanyWhatsAppConfig), ctx, companyId)
}

// GetEligibleTemplateByName mocks base method.
func (m *MockRepositoryInterface) GetEligibleTemplateByName(ctx context.Context, arg db.GetEligibleTemplateByNameParams) (db.WhatsappTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEligibleTemplateByName", ctx, arg)
	ret0, _ := ret[0].(db.WhatsappTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEligibleTemplateByName indicates an expected call of GetEligibleTemplateByName.
func (mr *MockRepositoryInterfaceMockRecorder) GetEligibleTemplateByName(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEligibleTemplateByName", reflect.TypeOf((*MockRepositoryInterface)(nil).GetEligibleTemplateByName), ctx, arg)
}

// GetMessageByMetaID mocks base method.
func (m *MockRepositoryInterface) GetMessageByMetaID(ctx context.Context, metaMessageID pgtype.Text) (db.WhatsappMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByMetaID", ctx, metaMessageID)
	ret0, _ := ret[0].(db.WhatsappMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByMetaID indicates an expected call of GetMessageByMetaID.
func (mr *MockRepositoryInterfaceMockRecorder) GetMessageByMetaID(ctx, metaMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByMetaID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetMessageByMetaID), ctx, metaMessageID)
}

// ListApprovedTemplates mocks base method.
func (m *MockRepositoryInterface) ListApprovedTemplates(ctx context.Context) ([]db.WhatsappTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApprovedTemplates", ctx)
	ret0, _ := ret[0].([]db.WhatsappTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApprovedTemplates indicates an expected call of ListApprovedTemplates.
func (mr *MockRepositoryInterfaceMockRecorder) ListApprovedTemplates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApprovedTemplates", reflect.TypeOf((*MockRepositoryInterface)(nil).ListApprovedTemplates), ctx)
}

// MarkUsageSyncedWithStripe mocks base method.
func (m *MockRepositoryInterface) MarkUsageSyncedWithStripe(ctx context.Context, arg db.MarkUsageSyncedWithStripeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsageSyncedWithStripe", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsageSyncedWithStripe indicates an expected call of MarkUsageSyncedWithStripe.
func (mr *MockRepositoryInterfaceMockRecorder) MarkUsageSyncedWithStripe(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsageSyncedWithStripe", reflect.TypeOf((*MockRepositoryInterface)(nil).MarkUsageSyncedWithStripe), ctx, arg)
}

// UpdateWhatsAppMessageStatus mocks base method.
func (m *MockRepositoryInterface) UpdateWhatsAppMessageStatus(ctx context.Context, arg db.UpdateWhatsAppMessageStatusParams) (db.WhatsappMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWhatsAppMessageStatus", ctx, arg)
	ret0, _ := ret[0].(db.WhatsappMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWhatsAppMessageStatus indicates an expected call of UpdateWhatsAppMessageStatus.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateWhatsAppMessageStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWhatsAppMessageStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateWhatsAppMessageStatus), ctx, arg)
}

// UpsertCompanyWhatsAppConfig mocks base method.
func (m *MockRepositoryInterface) UpsertCompanyWhatsAppConfig(ctx context.Context, arg db.UpsertCompanyWhatsAppConfigParams) (db.CompanyWhatsappConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCompanyWhatsAppConfig", ctx, arg)
	ret0, _ := ret[0].(db.CompanyWhatsappConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertCompanyWhatsAppConfig indicates an expected call of UpsertCompanyWhatsAppConfig.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertCompanyWhatsAppConfig(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCompanyWhatsAppConfig", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertCompanyWhatsAppConfig), ctx, arg)
}

// UpsertMonthlyUsage mocks base method.
func (m *MockRepositoryInterface) UpsertMonthlyUsage(ctx context.Context, arg db.UpsertMonthlyUsageParams) (db.WhatsappUsageMonthly, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMonthlyUsage", ctx, arg)
	ret0, _ := ret[0].(db.WhatsappUsageMonthly)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertMonthlyUsage indicates an expected call of UpsertMonthlyUsage.
func (mr *MockRepositoryInterfaceMockRecorder) UpsertMonthlyUsage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMonthlyUsage", reflect.TypeOf((*MockRepositoryInterface)(nil).UpsertMonthlyUsage), ctx, arg)
}
