// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain (interfaces: SubscriptionsServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/meta_whatsapp/mocks/mock_subscriptions_service.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/meta_whatsapp/domain SubscriptionsServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ProTrack-Solutions/protrack-api/internal/subscriptions/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionsServiceInterface is a mock of SubscriptionsServiceInterface interface.
type MockSubscriptionsServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionsServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockSubscriptionsServiceInterfaceMockRecorder is the mock recorder for MockSubscriptionsServiceInterface.
type MockSubscriptionsServiceInterfaceMockRecorder struct {
	mock *MockSubscriptionsServiceInterface
}

// NewMockSubscriptionsServiceInterface creates a new mock instance.
func NewMockSubscriptionsServiceInterface(ctrl *gomock.Controller) *MockSubscriptionsServiceInterface {
	mock := &MockSubscriptionsServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSubscriptionsServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionsServiceInterface) EXPECT() *MockSubscriptionsServiceInterfaceMockRecorder {
	return m.recorder
}

// GetSubscriptionByCompanyID mocks base method.
func (m *MockSubscriptionsServiceInterface) GetSubscriptionByCompanyID(ctx context.Context, companyID uuid.UUID) (domain.SubscriptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByCompanyID", ctx, companyID)
	ret0, _ := ret[0].(domain.SubscriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByCompanyID indicates an expected call of GetSubscriptionByCompanyID.
func (mr *MockSubscriptionsServiceInterfaceMockRecorder) GetSubscriptionByCompanyID(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByCompanyID", reflect.TypeOf((*MockSubscriptionsServiceInterface)(nil).GetSubscriptionByCompanyID), ctx, companyID)
}
