// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: mock de ServiceInterface para testes do handler de companies.
package mocks

import (
	"context"
	"reflect"

	"github.com/ProTrack-Solutions/protrack-api/internal/companies/domain"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// ServiceInterface define o contrato de serviço que o handler consome.
// Usado apenas para geração de mocks de testes.
type ServiceInterface interface {
	DeleteCompany(ctx context.Context, req domain.DeleteCompanyParams) error
	GetCompanyByDocument(ctx context.Context, document string) (domain.CompanyResponse, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (domain.CompanyResponse, error)
	ListCompanies(ctx context.Context) ([]domain.CompanyResponse, error)
	SetCompanyStatus(ctx context.Context, req domain.SetCompanyStatusParams) (int64, error)
	UpdateCompany(ctx context.Context, id uuid.UUID, req domain.UpdateCompanyRequest) (domain.CompanyResponse, error)
}

// MockServiceInterface é o mock da interface de serviço de companies.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder é o recorder de chamadas.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface cria uma nova instância do mock.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteCompany mocks o método DeleteCompany.
func (m *MockServiceInterface) DeleteCompany(ctx context.Context, req domain.DeleteCompanyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompany", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) DeleteCompany(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompany", reflect.TypeOf((*MockServiceInterface)(nil).DeleteCompany), ctx, req)
}

// GetCompanyByDocument mocks o método GetCompanyByDocument.
func (m *MockServiceInterface) GetCompanyByDocument(ctx context.Context, document string) (domain.CompanyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByDocument", ctx, document)
	ret0, _ := ret[0].(domain.CompanyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetCompanyByDocument(ctx, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByDocument", reflect.TypeOf((*MockServiceInterface)(nil).GetCompanyByDocument), ctx, document)
}

// GetCompanyByID mocks o método GetCompanyByID.
func (m *MockServiceInterface) GetCompanyByID(ctx context.Context, id uuid.UUID) (domain.CompanyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByID", ctx, id)
	ret0, _ := ret[0].(domain.CompanyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetCompanyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByID", reflect.TypeOf((*MockServiceInterface)(nil).GetCompanyByID), ctx, id)
}

// ListCompanies mocks o método ListCompanies.
func (m *MockServiceInterface) ListCompanies(ctx context.Context) ([]domain.CompanyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanies", ctx)
	ret0, _ := ret[0].([]domain.CompanyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListCompanies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanies", reflect.TypeOf((*MockServiceInterface)(nil).ListCompanies), ctx)
}

// SetCompanyStatus mocks o método SetCompanyStatus.
func (m *MockServiceInterface) SetCompanyStatus(ctx context.Context, req domain.SetCompanyStatusParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCompanyStatus", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) SetCompanyStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompanyStatus", reflect.TypeOf((*MockServiceInterface)(nil).SetCompanyStatus), ctx, req)
}

// UpdateCompany mocks o método UpdateCompany.
func (m *MockServiceInterface) UpdateCompany(ctx context.Context, id uuid.UUID, req domain.UpdateCompanyRequest) (domain.CompanyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompany", ctx, id, req)
	ret0, _ := ret[0].(domain.CompanyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) UpdateCompany(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompany", reflect.TypeOf((*MockServiceInterface)(nil).UpdateCompany), ctx, id, req)
}
