// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: mock de RepositoryInterface para testes do service de companies.
package mocks

import (
	"context"
	"reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	"github.com/jackc/pgx/v5/pgtype"
	"go.uber.org/mock/gomock"
)

// MockRepositoryInterface é o mock de RepositoryInterface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder é o recorder de chamadas do mock.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface cria uma nova instância do mock.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateCompany mocks o método CreateCompany.
func (m *MockRepositoryInterface) CreateCompany(ctx context.Context, arg db.CreateCompanyParams) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", ctx, arg)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CreateCompany(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateCompany), ctx, arg)
}

// DeleteCompany mocks o método DeleteCompany.
func (m *MockRepositoryInterface) DeleteCompany(ctx context.Context, arg db.DeleteCompanyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCompany", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) DeleteCompany(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteCompany), ctx, arg)
}

// GetCompanyByDocument mocks o método GetCompanyByDocument.
func (m *MockRepositoryInterface) GetCompanyByDocument(ctx context.Context, document pgtype.Text) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByDocument", ctx, document)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetCompanyByDocument(ctx, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByDocument", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCompanyByDocument), ctx, document)
}

// GetCompanyByID mocks o método GetCompanyByID.
func (m *MockRepositoryInterface) GetCompanyByID(ctx context.Context, id pgtype.UUID) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyByID", ctx, id)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetCompanyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyByID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCompanyByID), ctx, id)
}

// ListCompanies mocks o método ListCompanies.
func (m *MockRepositoryInterface) ListCompanies(ctx context.Context) ([]db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompanies", ctx)
	ret0, _ := ret[0].([]db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListCompanies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompanies", reflect.TypeOf((*MockRepositoryInterface)(nil).ListCompanies), ctx)
}

// CountCompanies mocks o método CountCompanies.
func (m *MockRepositoryInterface) CountCompanies(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCompanies", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CountCompanies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCompanies", reflect.TypeOf((*MockRepositoryInterface)(nil).CountCompanies), ctx)
}

// SetCompanyStatus mocks o método SetCompanyStatus.
func (m *MockRepositoryInterface) SetCompanyStatus(ctx context.Context, arg db.SetCompanyStatusParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCompanyStatus", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) SetCompanyStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompanyStatus", reflect.TypeOf((*MockRepositoryInterface)(nil).SetCompanyStatus), ctx, arg)
}

// UpdateCompany mocks o método UpdateCompany.
func (m *MockRepositoryInterface) UpdateCompany(ctx context.Context, arg db.UpdateCompanyParams) (db.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompany", ctx, arg)
	ret0, _ := ret[0].(db.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateCompany(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateCompany), ctx, arg)
}
