// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/products/service (interfaces: PlansServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/products/mocks/mock_plans_service.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/products/service PlansServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ProTrack-Solutions/protrack-api/internal/plans/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPlansServiceInterface is a mock of PlansServiceInterface interface.
type MockPlansServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPlansServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPlansServiceInterfaceMockRecorder is the mock recorder for MockPlansServiceInterface.
type MockPlansServiceInterfaceMockRecorder struct {
	mock *MockPlansServiceInterface
}

// NewMockPlansServiceInterface creates a new mock instance.
func NewMockPlansServiceInterface(ctrl *gomock.Controller) *MockPlansServiceInterface {
	mock := &MockPlansServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPlansServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlansServiceInterface) EXPECT() *MockPlansServiceInterfaceMockRecorder {
	return m.recorder
}

// GetPlanByID mocks base method.
func (m *MockPlansServiceInterface) GetPlanByID(ctx context.Context, planId uuid.UUID) (domain.PlanResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanByID", ctx, planId)
	ret0, _ := ret[0].(domain.PlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanByID indicates an expected call of GetPlanByID.
func (mr *MockPlansServiceInterfaceMockRecorder) GetPlanByID(ctx, planId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanByID", reflect.TypeOf((*MockPlansServiceInterface)(nil).GetPlanByID), ctx, planId)
}
