// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/products/service (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/products/mocks/mock_repository.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/products/service RepositoryInterface
package mocks

import (
	"context"
	"reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	"github.com/ProTrack-Solutions/protrack-api/internal/products/repository"
	"github.com/jackc/pgx/v5/pgtype"
	"go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountProducts mocks base method.
func (m *MockRepositoryInterface) CountProducts(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProducts", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProducts indicates an expected call of CountProducts.
func (mr *MockRepositoryInterfaceMockRecorder) CountProducts(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProducts", reflect.TypeOf((*MockRepositoryInterface)(nil).CountProducts), ctx, companyId)
}

// CountProductsByCompany mocks base method.
func (m *MockRepositoryInterface) CountProductsByCompany(ctx context.Context, companyID pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProductsByCompany", ctx, companyID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProductsByCompany indicates an expected call of CountProductsByCompany.
func (mr *MockRepositoryInterfaceMockRecorder) CountProductsByCompany(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProductsByCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).CountProductsByCompany), ctx, companyID)
}

// CreateProduct mocks base method.
func (m *MockRepositoryInterface) CreateProduct(ctx context.Context, arg db.CreateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockRepositoryInterfaceMockRecorder) CreateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateProduct), ctx, arg)
}

// DecrementStock mocks base method.
func (m *MockRepositoryInterface) DecrementStock(ctx context.Context, arg db.DecrementStockParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementStock", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementStock indicates an expected call of DecrementStock.
func (mr *MockRepositoryInterfaceMockRecorder) DecrementStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementStock", reflect.TypeOf((*MockRepositoryInterface)(nil).DecrementStock), ctx, arg)
}

// DeleteProduct mocks base method.
func (m *MockRepositoryInterface) DeleteProduct(ctx context.Context, arg db.DeleteProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockRepositoryInterfaceMockRecorder) DeleteProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteProduct), ctx, arg)
}

// GetCostTotalStock mocks base method.
func (m *MockRepositoryInterface) GetCostTotalStock(ctx context.Context, companyId pgtype.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCostTotalStock", ctx, companyId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCostTotalStock indicates an expected call of GetCostTotalStock.
func (mr *MockRepositoryInterfaceMockRecorder) GetCostTotalStock(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCostTotalStock", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCostTotalStock), ctx, companyId)
}

// GetInventoryReport mocks base method.
func (m *MockRepositoryInterface) GetInventoryReport(ctx context.Context, arg db.GetInventoryReportParams) ([]db.GetInventoryReportRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryReport", ctx, arg)
	ret0, _ := ret[0].([]db.GetInventoryReportRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryReport indicates an expected call of GetInventoryReport.
func (mr *MockRepositoryInterfaceMockRecorder) GetInventoryReport(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryReport", reflect.TypeOf((*MockRepositoryInterface)(nil).GetInventoryReport), ctx, arg)
}

// GetProductByBarcode mocks base method.
func (m *MockRepositoryInterface) GetProductByBarcode(ctx context.Context, barcode pgtype.Text) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByBarcode", ctx, barcode)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByBarcode indicates an expected call of GetProductByBarcode.
func (mr *MockRepositoryInterfaceMockRecorder) GetProductByBarcode(ctx, barcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByBarcode", reflect.TypeOf((*MockRepositoryInterface)(nil).GetProductByBarcode), ctx, barcode)
}

// GetProductById mocks base method.
func (m *MockRepositoryInterface) GetProductById(ctx context.Context, id pgtype.UUID) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductById", ctx, id)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductById indicates an expected call of GetProductById.
func (mr *MockRepositoryInterfaceMockRecorder) GetProductById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetProductById), ctx, id)
}

// GetProductsPerformanceSummary mocks base method.
func (m *MockRepositoryInterface) GetProductsPerformanceSummary(ctx context.Context, companyId pgtype.UUID) (db.GetProductsPerformanceSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsPerformanceSummary", ctx, companyId)
	ret0, _ := ret[0].(db.GetProductsPerformanceSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsPerformanceSummary indicates an expected call of GetProductsPerformanceSummary.
func (mr *MockRepositoryInterfaceMockRecorder) GetProductsPerformanceSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsPerformanceSummary", reflect.TypeOf((*MockRepositoryInterface)(nil).GetProductsPerformanceSummary), ctx, companyId)
}

// GetTop5BestSellingProducts mocks base method.
func (m *MockRepositoryInterface) GetTop5BestSellingProducts(ctx context.Context, companyId pgtype.UUID) ([]db.GetTop5BestSellingProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTop5BestSellingProducts", ctx, companyId)
	ret0, _ := ret[0].([]db.GetTop5BestSellingProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTop5BestSellingProducts indicates an expected call of GetTop5BestSellingProducts.
func (mr *MockRepositoryInterfaceMockRecorder) GetTop5BestSellingProducts(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop5BestSellingProducts", reflect.TypeOf((*MockRepositoryInterface)(nil).GetTop5BestSellingProducts), ctx, companyId)
}

// ListProductBuCategoryIdAndDate mocks base method.
func (m *MockRepositoryInterface) ListProductBuCategoryIdAndDate(ctx context.Context, arg db.ListProductsByCategoryAndDateParams) ([]db.ListProductsByCategoryAndDateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductBuCategoryIdAndDate", ctx, arg)
	ret0, _ := ret[0].([]db.ListProductsByCategoryAndDateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductBuCategoryIdAndDate indicates an expected call of ListProductBuCategoryIdAndDate.
func (mr *MockRepositoryInterfaceMockRecorder) ListProductBuCategoryIdAndDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductBuCategoryIdAndDate", reflect.TypeOf((*MockRepositoryInterface)(nil).ListProductBuCategoryIdAndDate), ctx, arg)
}

// ListProductsByCategoryId mocks base method.
func (m *MockRepositoryInterface) ListProductsByCategoryId(ctx context.Context, arg db.ListProductsByCategoryIdParams) ([]db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByCategoryId", ctx, arg)
	ret0, _ := ret[0].([]db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByCategoryId indicates an expected call of ListProductsByCategoryId.
func (mr *MockRepositoryInterfaceMockRecorder) ListProductsByCategoryId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByCategoryId", reflect.TypeOf((*MockRepositoryInterface)(nil).ListProductsByCategoryId), ctx, arg)
}

// ListProductsByCompany mocks base method.
func (m *MockRepositoryInterface) ListProductsByCompany(ctx context.Context, companyId pgtype.UUID) ([]db.ListProductsByCompanyRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByCompany", ctx, companyId)
	ret0, _ := ret[0].([]db.ListProductsByCompanyRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByCompany indicates an expected call of ListProductsByCompany.
func (mr *MockRepositoryInterfaceMockRecorder) ListProductsByCompany(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).ListProductsByCompany), ctx, companyId)
}

// ListProductsByCompanyPaginated mocks base method.
func (m *MockRepositoryInterface) ListProductsByCompanyPaginated(ctx context.Context, arg db.ListProductsByCompanyPaginatedParams) ([]db.ListProductsByCompanyPaginatedRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByCompanyPaginated", ctx, arg)
	ret0, _ := ret[0].([]db.ListProductsByCompanyPaginatedRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByCompanyPaginated indicates an expected call of ListProductsByCompanyPaginated.
func (mr *MockRepositoryInterfaceMockRecorder) ListProductsByCompanyPaginated(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByCompanyPaginated", reflect.TypeOf((*MockRepositoryInterface)(nil).ListProductsByCompanyPaginated), ctx, arg)
}

// ListProductsByDate mocks base method.
func (m *MockRepositoryInterface) ListProductsByDate(ctx context.Context, arg db.ListProductsByDateParams) ([]db.ListProductsByDateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByDate", ctx, arg)
	ret0, _ := ret[0].([]db.ListProductsByDateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByDate indicates an expected call of ListProductsByDate.
func (mr *MockRepositoryInterfaceMockRecorder) ListProductsByDate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByDate", reflect.TypeOf((*MockRepositoryInterface)(nil).ListProductsByDate), ctx, arg)
}

// UpdateProduct mocks base method.
func (m *MockRepositoryInterface) UpdateProduct(ctx context.Context, arg db.UpdateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, arg)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateProduct), ctx, arg)
}

// WithTx mocks base method.
func (m *MockRepositoryInterface) WithTx(tx db.DBTX) *repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*repository.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTx), tx)
}
