// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/customers/service (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/customers/mocks/mock_repository.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/customers/service RepositoryInterface
package mocks

import (
	"context"
	"reflect"

	"github.com/ProTrack-Solutions/protrack-api/internal/customers/repository"
	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	"github.com/jackc/pgx/v5/pgtype"
	"go.uber.org/mock/gomock"
)

// MockRepositoryInterface é o mock de RepositoryInterface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder é o recorder de chamadas do mock.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface cria uma nova instância do mock.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateCustomer mocks o método CreateCustomer.
func (m *MockRepositoryInterface) CreateCustomer(ctx context.Context, arg db.CreateCustomersParams) (pgtype.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, arg)
	ret0, _ := ret[0].(pgtype.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CreateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockRepositoryInterface)(nil).CreateCustomer), ctx, arg)
}

// DeleteCustomer mocks o método DeleteCustomer.
func (m *MockRepositoryInterface) DeleteCustomer(ctx context.Context, arg db.DeleteCustomerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) DeleteCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockRepositoryInterface)(nil).DeleteCustomer), ctx, arg)
}

// GetCustomerByCPF mocks o método GetCustomerByCPF.
func (m *MockRepositoryInterface) GetCustomerByCPF(ctx context.Context, cpf string) (db.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByCPF", ctx, cpf)
	ret0, _ := ret[0].(db.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetCustomerByCPF(ctx, cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByCPF", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCustomerByCPF), ctx, cpf)
}

// GetCustomerById mocks o método GetCustomerById.
func (m *MockRepositoryInterface) GetCustomerById(ctx context.Context, id pgtype.UUID) (db.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerById", ctx, id)
	ret0, _ := ret[0].(db.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetCustomerById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerById", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCustomerById), ctx, id)
}

// ListCustomers mocks o método ListCustomers.
func (m *MockRepositoryInterface) ListCustomers(ctx context.Context, companyID pgtype.UUID) ([]db.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, companyID)
	ret0, _ := ret[0].([]db.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListCustomers(ctx, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockRepositoryInterface)(nil).ListCustomers), ctx, companyID)
}

// UpdateBalanceDueCustomer mocks o método UpdateBalanceDueCustomer.
func (m *MockRepositoryInterface) UpdateBalanceDueCustomer(ctx context.Context, arg db.UpdateBalanceDueCustomerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceDueCustomer", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateBalanceDueCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceDueCustomer", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateBalanceDueCustomer), ctx, arg)
}

// UpdateCustomer mocks o método UpdateCustomer.
func (m *MockRepositoryInterface) UpdateCustomer(ctx context.Context, arg db.UpdateCustomerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateCustomer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateCustomer), ctx, arg)
}

// CountCustomers mocks o método CountCustomers.
func (m *MockRepositoryInterface) CountCustomers(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCustomers", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CountCustomers(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCustomers", reflect.TypeOf((*MockRepositoryInterface)(nil).CountCustomers), ctx, companyId)
}

// GetCustomersPerformanceSummary mocks o método GetCustomersPerformanceSummary.
func (m *MockRepositoryInterface) GetCustomersPerformanceSummary(ctx context.Context, companyId pgtype.UUID) (db.GetCustomersPerformanceSummaryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersPerformanceSummary", ctx, companyId)
	ret0, _ := ret[0].(db.GetCustomersPerformanceSummaryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) GetCustomersPerformanceSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersPerformanceSummary", reflect.TypeOf((*MockRepositoryInterface)(nil).GetCustomersPerformanceSummary), ctx, companyId)
}

// UpdateCustomerBalance mocks o método UpdateCustomerBalance.
func (m *MockRepositoryInterface) UpdateCustomerBalance(ctx context.Context, arg db.UpdateCustomerBalanceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomerBalance", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) UpdateCustomerBalance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomerBalance", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateCustomerBalance), ctx, arg)
}

// ListCustomersPaginate mocks o método ListCustomersPaginate.
func (m *MockRepositoryInterface) ListCustomersPaginate(ctx context.Context, arg db.ListCustomersPaginateParams) ([]db.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomersPaginate", ctx, arg)
	ret0, _ := ret[0].([]db.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) ListCustomersPaginate(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomersPaginate", reflect.TypeOf((*MockRepositoryInterface)(nil).ListCustomersPaginate), ctx, arg)
}

// CountCustomersByCompany mocks o método CountCustomersByCompany.
func (m *MockRepositoryInterface) CountCustomersByCompany(ctx context.Context, companyId pgtype.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCustomersByCompany", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockRepositoryInterfaceMockRecorder) CountCustomersByCompany(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCustomersByCompany", reflect.TypeOf((*MockRepositoryInterface)(nil).CountCustomersByCompany), ctx, companyId)
}

// WithTx mocks o método WithTx.
func (m *MockRepositoryInterface) WithTx(tx db.DBTX) *repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*repository.Repository)
	return ret0
}

func (mr *MockRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTx), tx)
}
