// Code generated by MockGen (go.uber.org/mock). DO NOT EDIT.
// Source: mock de ServiceInterface para testes do handler de customers.
package mocks

import (
	"context"
	"reflect"

	"github.com/ProTrack-Solutions/protrack-api/internal/customers/domain"
	globalDomain "github.com/ProTrack-Solutions/protrack-api/internal/domain"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// ServiceInterface define o contrato de serviço que o handler consome.
// Usado apenas para geração de mocks de testes.
type ServiceInterface interface {
	CreateCustomer(ctx context.Context, req domain.CreateCustomersRequest) (uuid.UUID, error)
	DeleteCustomer(ctx context.Context, req domain.DeleteCustomerRequest) error
	GetCustomerByCPF(ctx context.Context, cpf string) (domain.CustomerResponse, error)
	GetCustomerById(ctx context.Context, id uuid.UUID) (domain.CustomerResponse, error)
	ListCustomers(ctx context.Context, companyId uuid.UUID) ([]domain.CustomerResponse, error)
	UpdateBalanceDueCustomer(ctx context.Context, id uuid.UUID, req domain.UpdateBalanceDueCustomerRequest) error
	UpdateCustomer(ctx context.Context, id uuid.UUID, req domain.UpdateCustomerRequest) error
	CountCustomers(ctx context.Context, companyId uuid.UUID) (int64, error)
	GetCustomersPerformanceSummary(ctx context.Context, companyId uuid.UUID) (float64, error)
	ListCustomersPaginated(ctx context.Context, companyId uuid.UUID, pagination globalDomain.PaginationParams) (domain.CustomerPaginatedResponse, error)
}

// MockServiceInterface é o mock da interface de serviço de customers.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder é o recorder de chamadas.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface cria uma nova instância do mock.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT retorna o objeto de expectativas.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateCustomer mocks o método CreateCustomer.
func (m *MockServiceInterface) CreateCustomer(ctx context.Context, req domain.CreateCustomersRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, req)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) CreateCustomer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockServiceInterface)(nil).CreateCustomer), ctx, req)
}

// DeleteCustomer mocks o método DeleteCustomer.
func (m *MockServiceInterface) DeleteCustomer(ctx context.Context, req domain.DeleteCustomerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) DeleteCustomer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockServiceInterface)(nil).DeleteCustomer), ctx, req)
}

// GetCustomerByCPF mocks o método GetCustomerByCPF.
func (m *MockServiceInterface) GetCustomerByCPF(ctx context.Context, cpf string) (domain.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerByCPF", ctx, cpf)
	ret0, _ := ret[0].(domain.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetCustomerByCPF(ctx, cpf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerByCPF", reflect.TypeOf((*MockServiceInterface)(nil).GetCustomerByCPF), ctx, cpf)
}

// GetCustomerById mocks o método GetCustomerById.
func (m *MockServiceInterface) GetCustomerById(ctx context.Context, id uuid.UUID) (domain.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomerById", ctx, id)
	ret0, _ := ret[0].(domain.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetCustomerById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomerById", reflect.TypeOf((*MockServiceInterface)(nil).GetCustomerById), ctx, id)
}

// ListCustomers mocks o método ListCustomers.
func (m *MockServiceInterface) ListCustomers(ctx context.Context, companyId uuid.UUID) ([]domain.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx, companyId)
	ret0, _ := ret[0].([]domain.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListCustomers(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockServiceInterface)(nil).ListCustomers), ctx, companyId)
}

// UpdateBalanceDueCustomer mocks o método UpdateBalanceDueCustomer.
func (m *MockServiceInterface) UpdateBalanceDueCustomer(ctx context.Context, id uuid.UUID, req domain.UpdateBalanceDueCustomerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceDueCustomer", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) UpdateBalanceDueCustomer(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceDueCustomer", reflect.TypeOf((*MockServiceInterface)(nil).UpdateBalanceDueCustomer), ctx, id, req)
}

// UpdateCustomer mocks o método UpdateCustomer.
func (m *MockServiceInterface) UpdateCustomer(ctx context.Context, id uuid.UUID, req domain.UpdateCustomerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockServiceInterfaceMockRecorder) UpdateCustomer(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockServiceInterface)(nil).UpdateCustomer), ctx, id, req)
}

// CountCustomers mocks o método CountCustomers.
func (m *MockServiceInterface) CountCustomers(ctx context.Context, companyId uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCustomers", ctx, companyId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) CountCustomers(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCustomers", reflect.TypeOf((*MockServiceInterface)(nil).CountCustomers), ctx, companyId)
}

// GetCustomersPerformanceSummary mocks o método GetCustomersPerformanceSummary.
func (m *MockServiceInterface) GetCustomersPerformanceSummary(ctx context.Context, companyId uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersPerformanceSummary", ctx, companyId)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) GetCustomersPerformanceSummary(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersPerformanceSummary", reflect.TypeOf((*MockServiceInterface)(nil).GetCustomersPerformanceSummary), ctx, companyId)
}

// ListCustomersPaginated mocks o método ListCustomersPaginated.
func (m *MockServiceInterface) ListCustomersPaginated(ctx context.Context, companyId uuid.UUID, pagination globalDomain.PaginationParams) (domain.CustomerPaginatedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomersPaginated", ctx, companyId, pagination)
	ret0, _ := ret[0].(domain.CustomerPaginatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockServiceInterfaceMockRecorder) ListCustomersPaginated(ctx, companyId, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomersPaginated", reflect.TypeOf((*MockServiceInterface)(nil).ListCustomersPaginated), ctx, companyId, pagination)
}
