// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProTrack-Solutions/protrack-api/internal/subscription_management/service (interfaces: RepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/subscription_management/mocks/mock_repository.go -package=mocks github.com/ProTrack-Solutions/protrack-api/internal/subscription_management/service RepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/ProTrack-Solutions/protrack-api/internal/database/sqlc"
	repository "github.com/ProTrack-Solutions/protrack-api/internal/subscription_management/repository"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetSubscriptionDetailsByCompanyID mocks base method.
func (m *MockRepositoryInterface) GetSubscriptionDetailsByCompanyID(ctx context.Context, companyId pgtype.UUID) (db.GetSubscriptionDetailsByCompanyIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionDetailsByCompanyID", ctx, companyId)
	ret0, _ := ret[0].(db.GetSubscriptionDetailsByCompanyIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionDetailsByCompanyID indicates an expected call of GetSubscriptionDetailsByCompanyID.
func (mr *MockRepositoryInterfaceMockRecorder) GetSubscriptionDetailsByCompanyID(ctx, companyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionDetailsByCompanyID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetSubscriptionDetailsByCompanyID), ctx, companyId)
}

// WithTx mocks base method.
func (m *MockRepositoryInterface) WithTx(tx db.DBTX) *repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(*repository.Repository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepositoryInterface)(nil).WithTx), tx)
}
